### ISSUE TITLE
Transmission: Authentication error

### ISSUE THREAD

**Issue by froggay** [SickRage/SickRage#1289]
**Branch/Commit**: master /2016.03.28-2-6-g7902d12
**OS**: windows 7
**What you did**: transmission setup in config/search/
**What happened**: 
transmission test is ok, i get message : 

> "Success: Connected and Authenticated"

but when i go to manage/manageTorrents/ i have a 404 error message
and when i launch a search, the torrent is not sent to transmission daemon
i have a error messsage " 
> SEARCHQUEUE-MANUAL-77398 :: Transmission: Authentication Failed"

Logs: http://pastebin.com/f2Fm1nnv

my transmission deamon is coming from a french ISP DSL box ( freebox )
same transmission parameters works fine with transmission remote

**Comment by miigotu** [comment]
Make sure you dont have `/rpc` on the end of the path settings, SR adds this part automatically.

**Comment by miigotu** [comment]
Will need to know more about your settings/debug to help. Transmission works just fine in SR here (its what I use)

**Comment by froggay** [comment]
i think the problem is linked to the transmission server used by "freebox" .

the server only authorize  this url  `http://192.168.1.254:9091/transmission/rpc` (without last slash)
`http://192.168.1.254:9091/transmission/rpc/`  is rejected with "HTTP/1.1 401 Unauthorized" error

the trailing slash is automatically added by sickrage, so it will not work.

Is it possible to prevent sickrage from adding this trailing slash in the url ?

this issue has been noticed to "freebox" developper too
http://dev.freebox.fr/bugs/task/19407

**Comment by miigotu** [comment]
`the trailing slash is automatically added by sickrage, so it will not work.`

If you adjust the way you set the url, it shouldnt.

In the host box, put the ip and port only. In the rpc url put `transmission`. SR will add the /rpc part for you.

![image](https://cloud.githubusercontent.com/assets/390379/14136654/c7520356-f618-11e5-811a-bc4d8019dd8c.png)

**Comment by froggay** [comment]
yes it's what i have done, and the test is ok

![2016-03-30 10_57_01-sickrage - config - episode search](https://cloud.githubusercontent.com/assets/17068466/14137052/4a93a574-f666-11e5-941c-cc8fac6119f9.png)

but , i think the transmission client automatically add a slash at the end and convert utl to `http://192.168.1.254:9091/transmission/rpc/` which is rejected by transmission server 

![image](https://cloud.githubusercontent.com/assets/17068466/14137137/c6eb122e-f666-11e5-9c8d-07d3f2d59680.png)



![image](https://cloud.githubusercontent.com/assets/17068466/14137238/3902caaa-f667-11e5-9310-894cb5a1f63e.png)

**Comment by miigotu** [comment]
The web ui isnt at the rpc url, it is at: `http://user:pass@ip:port/`m which is redirected to `http://ip:port/transmission/web/`

**Comment by miigotu** [comment]
Since this is the proxy_pass configuration for nginx failing and not SickRage, I'm going to close this.
They need to also forward `/` on port 9091, not just `/transmission/rpc`

**Comment by sebiiiii** [comment]
see #1920 for a workaround (iptables -f)
