### ISSUE TITLE
Search not behave as expected (T411)

### ISSUE THREAD

**Issue by mtache** [SickRage/SickRage#2037]
Hello everyone,

I don't understand the behaviour of my Sickrage: it downloads a 720p Bluray quality of a season instead of the 1080p WEB DL it found.
My quality settings are Custom: HD 720p as "available" and HD 1080p as "prefered". I use 2 trackers.
After finding the 1080p WEB DL season pack on the first tracker, it says "Checking if we should keep searching after we've found House.Of.Cards.2013.S04.COMPLETE.VOSTFR.1080p.webrip.HEVC.x265-f3f3" and it searches on the second tracker (why not...). Then, it finds a 720p Bluray seasin pack and it downloads it.
There is also the line "Adding multi-ep result for full-season torrent. Set the episodes you don't want to 'don't download' in your torrent client if desired!" in the log that I don't understand.
Maybe the issue is caused by the search plugin of the first tracker I use (T411) since it behaves differently when I disable the second tracker (it doesn't download a season pack as expected but 13 different single episodes).

Cheers

Branch: master
Commit: 34d0987400b3d50f550f55472d417c4e5b263f55
Version: 2016.06.14-1
Database Version: 44.0
OS: Linux-3.10.101-16-osmc-armv7l-with-debian-8.5
What you did: Set a whole season as wanted to cause backlog search
What happened: A 720p Bluray quality of the season is downloaded
What you expected: The found 1080p WEB DL quality of the season to be downloaded
Logs: http://pastebin.com/KE1wmkqY

**Comment by neoatomic** [comment]
There are multiple problems with the example pack you ask about.

`VOSTFR.1080p.webrip.HEVC.x265`

First `VOSTFR` `HEVC` could be set as ignored words adn so skipped. So check for that.
Second I dont think `x265` is recognized as HD 1080p as that needs to be `x264`

You can read a little more about quality recognition on this page. : 
https://github.com/SickRage/SickRage/wiki/Quality-Settings
