### ISSUE TITLE
Please re-enable NapiProjekt subtitle provider

### ISSUE THREAD

**Issue by murbaniak** [SickRage/SickRage#2381]
According to the https://github.com/Diaoul/subliminal/issues/536 the NapiProjekt downloads subtitles in MicroDVD format. This may cause the problems for some users BUT it is not an issue in Kodi or VLC. The NapiProjekt has been deactivated in Subliminal for now but it can be easily re-enabled manually in SickRage. There is no reason to disable this provider as it is working well for most users. Please re-enable it in SickRage. Fix is easy and let's leave the user a choice if he/she wants to use this provider or not. Fix in SickRage is trivial:

in file ./sickbeard/subtitles.py line 48:
if 'napiprojekt' not in provider_manager.names():
    provider_manager.register('napiprojekt = subliminal.providers.napiprojekt:NapiProjektProvider')

Cheers,
Maciej

**Comment by neoatomic** [comment]
@murbaniak Thanks for the report.

@miigotu I leave this call to you, if you want to re-add it.

**Comment by miigotu** [comment]
Its not just the issue of mDVD, its also that the subs are in Windows-1250 and cause encoding errors. When subliminal updates to make it work better we will update subliminal in SR. We no longer have any patches applied to the subliminal code supplied with SR.

**Comment by murbaniak** [comment]
miigotu, I am not talking about patch for subliminal in SR, it is just ability for a user to use this provider if he/she wants to by manually registering a provider in  ./sickbeard/subtitles.py. For example in my case it is working ok because I am using Windows-1250 in Kodi. You are not breaking anything by enabling this provider to be used in SR. And if Windows-1250 encoding is a problem for any user, he/she does not have to enable it at all.

**Comment by miigotu** [comment]
There is nothing stopping you from enabling it yourself locally, but for the case of 10's of thousands of users who don't know of the problems with napi and the exceptions that get thrown because of the subs it will not be done in the main repo until it is fixed up upstream. Sorry.
