### ISSUE TITLE
Mako Error ommon.py:587, in __missing__: raise KeyError(key) # ... so the key is invalid / on Synology

### ISSUE THREAD

**Issue by cgrauls** [SickRage/SickRage#2510]
Hello,

SickRage Configuration
  SickRage Info:
Branch: master
Commit: 660b56c2a337da7fd3735bcefef985bbeff08b9f
Version: warning: tag '2016.10.18-1' is really 'v2016.10.18-1' here 2016.10.18-1
Database Version: 44.0
  Python Version: 2.7.11 (default, Dec 17 2015, 15:58:38) [GCC 4.7.3 20130102 (prerelease)]
  SSL Version: OpenSSL 1.0.2e 3 Dec 2015
  OS: Linux-3.10.77-x86_64-with-glibc2.2.5
  Locale: en_US.UTF-8

  User: sickbeard-custom
  Program Folder: /usr/local/sickbeard-custom/var/SickBeard
  Config File: /usr/local/sickbeard-custom/var/config.ini
  Database File: /usr/local/sickbeard-custom/var/sickbeard.db
  Cache Folder: /usr/local/sickbeard-custom/var/cache
  Log Folder: /usr/local/sickbeard-custom/var/Logs
  Arguments: ['--daemon', '--pidfile', '/usr/local/sickbeard-custom/var/sickbeard-custom.pid', '--config', '/usr/local/sickbeard-custom/var/config.ini', '--datadir', '/usr/local/sickbeard-custom/var/']

this is running on a Synology. installed like described on 
https://github.com/SickRage/SickRage/wiki/Switching-your-Synology's-Sickrage-to-the-new-repository

When I add a show trough IMDB ( as with normal search the show is not displayed)
And I click on the show I get 
File /volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/common.py:587, in __missing__:
raise KeyError(key) # ... so the key is invalid
KeyError: None

**Comment by miigotu** [comment]
Restart SR.

**Comment by channouze** [comment]
@miigotu Thanks it solved the issue (Error appeared with adding both through IMDB and Trakt). Could we at least add a hint to restart SR in the error message please?
