### ISSUE TITLE
Honor Downloaded Quality over Preferred Quality

### ISSUE THREAD

**Issue by rflack1717** [SickRage/SickRage#2512]
SickRage doesn't seem to honor or prioritize the 'Downloaded' quality over the 'Preferred' quality in cases where it is superior. For example, I have a show which is 'Preferred' at 1080p WEB-DL (this is working fine). I have manually added the 1080p Bluray file rips to this show, replacing the existing files, and finally have selected the series and marked it as 'Downloaded: 1080p Bluray'. The quality, however, remains yellow and the next backlog search that runs seeks to replace the 1080p Bluray with a 1080p WEB-DL.

Clearly this is not the desired behaviour I was expecting :) Is there any way this can be handled better, or to make SickRage follow the quality chain and not override higher qualities with lower ones?

Branch: master
Commit: 660b56c2a337da7fd3735bcefef985bbeff08b9f
Version: 2016.10.18-1
Database Version: 44.0

**Comment by miigotu** [comment]
Just add the 1080 Bluray to the preferred too, or dont used a preferred list.
