### ISSUE TITLE
Unable to start

### ISSUE THREAD

**Issue by alecbruce** [SickRage/SickRage#2583]
Branch/Commit:
OS: raspberry pi2
What you did: unable to start sickrage on reboot
What happened: below error
What you expected: ran fine 1week ago
Logs:
```
~ $ python /opt/sickrage/SickBeard.py

Traceback (most recent call last):
File "/opt/sickrage/SickBeard.py", line 562, in <module>
SickRage().start()
File "/opt/sickrage/SickBeard.py", line 311, in start
sickbeard.initialize(consoleLogging=self.console_logging)
File "/opt/sickrage/sickbeard/__init__.py", line 1301, in initialize
providerList = providers.makeProviderList()
File "/opt/sickrage/sickbeard/providers/__init__.py", line 72, in makeProviderList
return [x.provider for x in (getProviderModule(y) for y in __all__) if x]
AttributeError: 'module' object has no attribute 'provider'
```
Sickrage worked perfectly last week, but now I'm unable to start it. Any suggestions. If I have to reinstall, how do I save all my settings without the UI running?

**Comment by miigotu** [comment]
Since you didnt give me all of the information above I am a little limited in how much I can help.
If you installed by pip, you are in the wrong place.
If you installed from zip/tarball there are other steps.
If you installed by git, can you post the output of this?:
```bash
python2.7 -V
cd /opt/sickrage
git remote show origin | grep URL
git fetch origin
git status
git reset --hard origin/master
./SickBeard.py
```

**Comment by alecbruce** [comment]
miigotu you're a legend. That fixed it, but I'd be interested in what originally went wrong so I can ensure the same problems don't occur at startup.

Here's the output:

> pi@baldwin:~
> 
>  $ python2.7 -V
> Python 2.7.9
> pi@baldwin:~ $ cd /opt/sickrage
> pi@baldwin:/opt/sickrage $ git remote show origin | grep URL
>   Fetch URL: https://github.com/SickRage/SickRage.git
>   Push  URL: https://github.com/SickRage/SickRage.git
> pi@baldwin:/opt/sickrage $ git fetch origin
> remote: Counting objects: 112, done.
> remote: Compressing objects: 100% (13/13), done.
> remote: Total 112 (delta 84), reused 82 (delta 82), pack-reused 16
> Receiving objects: 100% (112/112), 82.46 KiB | 0 bytes/s, done.
> Resolving deltas: 100% (84/84), completed with 75 local objects.
> From https://github.com/SickRage/SickRage
>    68db29a..d15b700  master     -> origin/master
>    68db29a..29737f6  develop    -> origin/develop
> pi@baldwin:/opt/sickrage $ git status
> On branch master
> Your branch is behind 'origin/master' by 9 commits, and can be fast-forwarded.
>   (use "git pull" to update your local branch)
> Changes not staged for commit:
>   (use "git add <file>..." to update what will be committed)
>   (use "git checkout -- <file>..." to discard changes in working directory)
> 
> 	modified:   gui/slick/views/config_providers.mako
> 	modified:   lib/network_timezones/network_timezones.txt
> 	modified:   sickbeard/providers/extratorrent.py
> 	modified:   sickbeard/providers/iptorrents.py
> 	modified:   sickbeard/providers/newpct.py
> 
> Untracked files:
>   (use "git add <file>..." to include in what will be committed)
> 
> 	sickrage/providers/torrent/kat.py
> 
> no changes added to commit (use "git add" and/or "git commit -a")
> pi@baldwin:/opt/sickrage $ git reset --hard origin/master
> HEAD is now at d15b700 Merge branch 'develop'
> pi@baldwin:/opt/sickrage $ ./SickBeard.py
> 01:12:59 INFO::MAIN :: 288810: Unable to find IMDb show info in the database
> 01:12:59 INFO::MAIN :: Starting SickRage [master] using '/opt/sickrage/config.ini'
> 01:12:59 INFO::TORNADO :: Starting SickRage on http://0.0.0.0:8081/
> 01:12:59 INFO::TORNADO :: Could not start webserver on port 8081, already in use!

**Comment by miigotu** [comment]
don't modify source files and then open issues when you break it -.-.

Find out whats on port 8081, if it's sr reboot and start it like normal, if its something else start SR with a different port like `SickBeard.py -p 8082`
