### ISSUE TITLE
[APP SUBMITTED]: Thread-13 :: [d15b700] Missing time zone for network: Canal+ Cyfrowy. Check valid network is set in indexer (theTVDB) before filing issue.

### ISSUE THREAD

**Issue by kapeer** [SickRage/SickRage#2584]
### INFO
Python Version: **2.7.12 (default, Jul  1 2016, 15:12:24) [GCC 5.4.0 20160609]**
Operating System: **Linux-3.13.0-92-generic-x86_64-with-Ubuntu-16.04-xenial**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@d15b7003f8663b76d01fcbf0566389b2f31e0564
No Log available with ERRORS:
### ERROR
```
Thread-13 :: [d15b700] Missing time zone for network: Canal+ Cyfrowy. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by bobbysteel** [comment]
Patch submitted
