### ISSUE TITLE
[APP SUBMITTED]: Thread-13 :: [a1bf3b3] Missing time zone for network: #0. Check valid network is set in indexer (theTVDB) before filing issue.

### ISSUE THREAD

**Issue by Danny89530** [SickRage/SickRage#2636]
### INFO
Python Version: **2.7.3 (default, Jun 20 2016, 16:18:47) [GCC 4.7.2]**
Operating System: **Linux-3.2.0-4-686-pae-i686-with-debian-7.11**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@a1bf3b30a9a0d6319c09fb0cf48d2d468dbf4e61
No Log available with ERRORS:
### ERROR
```
Thread-13 :: [a1bf3b3] Missing time zone for network: #0. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by skalvaro** [comment]
Same error encountered after update.

Branch: master
Commit: a1bf3b30a9a0d6319c09fb0cf48d2d468dbf4e61
Version: v2016.10.28-1
Database Version: 44.0
Python Version: 2.7.5 (default, Sep 15 2016, 22:37:39) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
SSL Versie: OpenSSL 1.0.1e-fips 11 Feb 2013
OS: Linux-3.10.0-327.36.3.el7.x86_64-x86_64-with-centos-7.2.1511-Core
Locale: en_US.UTF-8

**Comment by ripper1967** [comment]
You have a show without a ? for a network, open the shows page  then use simple view under network find the show with  #0. Do a full update on that show it will fix it. Or under mass update  do a  full update on all shows will fix it as well as long as the show with the ?  has a network assigned at thetvdb.

**Comment by Tom-Whi** [comment]
### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@a1bf3b30a9a0d6319c09fb0cf48d2d468dbf4e61
No Log available with ERRORS:
### ERROR
```
Thread-498 :: [a1bf3b3] Missing time zone for network: #0. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators
