### ISSUE TITLE
[APP SUBMITTED]: Thread-25 :: [5ba0a52] Missing time zone for network: National Geographic (AU). Check valid network is set in indexer (theTVDB) before filing issue.

### ISSUE THREAD

**Issue by abetancort** [SickRage/SickRage#3143]
### INFO
Python Version: **2.7.13 (default, Dec 19 2016, 02:32:04) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.77-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@5ba0a5263267c8f7fc568325de523ef869dccf7f
No Log available with ERRORS:
### ERROR
```
Thread-25 :: [5ba0a52] Missing time zone for network: National Geographic (AU). Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by abetancort** [comment]
What do you need me to upload?

**Comment by sharkykh** [comment]
Hey @abetancort,
You don't need to upload anything.
I have requested that a time zone for this network be added.
:)
