### ISSUE TITLE
Unpacking Failed with Invalid Rar Archive Usage

### ISSUE THREAD

**Issue by deepsh4h** [SickRage/SickRage#3314]
Branch: master
Commit: 66babc76d28646807c1040a3e225072b410489ad
Version: v2017.03.02-1
OS: Ubuntu 14.04
What you did: Auto/Manual Post Processing
What happened: Failed to unpack

PS:- unrar is already installed in system directory /usr/local/bin/ & /usr/bin

Logs:
```
2017-03-04 17:11:06 INFO POSTPROCESSOR-AUTO :: Auto post processing task for /home/Downloads completed
2017-03-04 17:11:06 INFO POSTPROCESSOR-AUTO :: XX.rar : Unpacking failed: Unpacking Failed with Invalid Rar Archive Usage. Is unrar installed and on the system PATH?
2017-03-04 17:11:06 INFO POSTPROCESSOR-AUTO :: XX.rar : Unpacking failed: Unpacking Failed with Invalid Rar Archive Usage. Is unrar installed and on the system PATH?
2017-03-04 17:11:06 INFO POSTPROCESSOR-AUTO :: Some items were not processed.

```

**Comment by miigotu** [comment]
make sure `unrar` is in the unrar location box on post processing settings page.

**Comment by deepsh4h** [comment]
[https://imgbox.com/smp7sR0N](url)
It is already there, still the problem persists.

**Comment by miigotu** [comment]
Do you have unrar-nonfree installed or unrar-free?

**Comment by deepsh4h** [comment]
I have both of them installed

**Comment by miigotu** [comment]
```
sudo apt purge unrar-free unrar-nonfree --autoremove
sudo apt install unrar-nonfree
echo $PATH | grep -o $(dirname `which unrar`)
```
What is the last line of output after running that ^?
This is something wrong with your system/install method. unrar works flawlessly on linux, only windows has a bit of confusion.

**Comment by deepsh4h** [comment]
````
Package unrar-nonfree is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'unrar-nonfree' has no installation candidate
root@server2:~# echo $PATH | grep -o $(dirname `which unrar`)
/usr/local/bin

````

**Comment by deepsh4h** [comment]
Fixed this by removing already installed unrar package : apt-get remove unrar 

and installed the apt-get install unrar-free

**Comment by miigotu** [comment]
Either one should work, but glad it is working for you now.

**Comment by rubio2** [comment]
I have the same problem, please, check this https://github.com/SickRage/SickRage/issues/4108 @miigotu
