### ISSUE TITLE
Where the Quality setting go?

### ISSUE THREAD

**Issue by zuperjotmeil** [SickRage/SickRage#3583]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch: master | Now: 02/04/2017 08:23 PM
OS: Linux vortexbox 3.12.5-301.fc20.i686+PAE #1 SMP Mon Dec 16 18:42:48 EST 2013 i686 i686 i386 GNU/Linux
What you did: Try to find Quality Settings
What happened: Don't find them
What you expected: Before was a menu to setup general custom quality settings.
Logs:
![image](https://cloud.githubusercontent.com/assets/14860992/24591974/3a2a2492-17e4-11e7-8fd2-1fc397c16e49.png)

**Comment by sharkykh** [comment]
Shows -> Add shows -> Add New Show or Add Existing Show

There you can change the default settings and then "Save as default".

**Comment by zuperjotmeil** [comment]
This is not what I am looking for:

[image: Imagen integrada 1]

Before there was a menu where you can set your own Preferred Qualities:
[image: Imagen integrada 2]

Saludos Cordiales,


Álvaro Enrique Gajardo Vodanovic <aegajardo@gmail.com>
Celular +56 9 61551615
<http://cl.linkedin.com/pub/alvaro-gajardo/33/137/6a0/>

2017-04-02 20:53 GMT-03:00 sharkykh <notifications@github.com>:

**Comment by sharkykh** [comment]
The images are not visible.
Preferred qualities can be set when you select "Custom..." quality. This applies when you edit a show, too.

**Comment by zuperjotmeil** [comment]
I know that, but before there was a menu like the ones for General setting,
Search Providers, etc to set my own setting like:

MyHD720p = Allowed (SD DVD, 720p HDTV, 720p WEB-DL) Preferred (720p Bluray)

or

MyAll = Allowed (SDTV, SD DVD, 720p HDTV, 720p WEB-DL, 1080p WEB-DL)
Preferred (4K UHD)

I mean, one can set his own preferred quality saved sets so it appears in
the menu you say as an option, instead of selecting one by one what is
wanted.



Saludos Cordiales,


Álvaro Enrique Gajardo Vodanovic <aegajardo@gmail.com>
Celular +56 9 61551615
<http://cl.linkedin.com/pub/alvaro-gajardo/33/137/6a0/>

2017-04-02 21:13 GMT-03:00 sharkykh <notifications@github.com>:

**Comment by sharkykh** [comment]
Oh, I understand.
I didn't see anything like this, other than manually setting a custom quality configuration globally or per show.

Maybe you should wait for someone that's been using SickRage for longer than I have (month or two) to answer.

**Comment by zuperjotmeil** [comment]
Ok, thanks for your help anyways.

Good luck

Saludos Cordiales,


Álvaro Enrique Gajardo Vodanovic <aegajardo@gmail.com>
Celular +56 9 61551615
<http://cl.linkedin.com/pub/alvaro-gajardo/33/137/6a0/>

2017-04-02 21:25 GMT-03:00 sharkykh <notifications@github.com>:

**Comment by sharkykh** [comment]
@zuperjotmeil 
There are two forks of SickRage, I'm pretty sure now that you were referring to the other one.
