### ISSUE TITLE
"Fix" for 3517 broke something else

### ISSUE THREAD

**Issue by paulwitt** [SickRage/SickRage#3593]
Getting this error now when I try to start up:
```
Traceback (most recent call last):
  File "/mnt/sda3/sickrage/SickBeard.py", line 494, in <module>
    SickRage().start()
  File "/mnt/sda3/sickrage/SickBeard.py", line 242, in start
    sickbeard.initialize(consoleLogging=self.console_logging)
  File "/mnt/sda3/sickrage/sickbeard/__init__.py", line 1100, in initialize
    helpers.manage_torrents_url(reset=True)
  File "/mnt/sda3/sickrage/sickbeard/helpers.py", line 1897, in manage_torrents_url
    sickbeard.CLIENT_WEB_URLS['torrent'] = ('', torrent_ui_url)[test_exists(torrent_ui_url)]
  File "/mnt/sda3/sickrage/sickbeard/helpers.py", line 1886, in test_exists
    h = requests.head(url)
  File "/mnt/sda3/sickrage/lib/requests/api.py", line 93, in head
    return request('head', url, **kwargs)
  File "/mnt/sda3/sickrage/lib/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/mnt/sda3/sickrage/lib/requests/sessions.py", line 454, in request
    prep = self.prepare_request(req)
  File "/mnt/sda3/sickrage/lib/requests/sessions.py", line 388, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/mnt/sda3/sickrage/lib/requests/models.py", line 293, in prepare
    self.prepare_url(url, params)
  File "/mnt/sda3/sickrage/lib/requests/models.py", line 353, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?
```

Not sure what's causing it but /sickbeard/__init__.py was edited in this commit:
https://github.com/SickRage/SickRage/commit/c53b55fbd000d73bdcd84900bae2afc3bfff15a3

Line 1100 was what was added (see error) and when I manually remove that line it starts up.  Turning off auto-updates for now until this is fixed.  Please let me know if you need more info on my settings.

**Comment by sharkykh** [comment]
This was fixed on the newest commit. You can already update.

**Comment by rharing** [comment]
i am on the latest master yet i also see a similar error:
`  File "SickBeard.py", line 242, in start
    sickbeard.initialize(consoleLogging=self.console_logging)
  File "/home/ronald/.sickrage/sickbeard/__init__.py", line 1100, in initialize
    helpers.manage_torrents_url(reset=True)
  File "/home/ronald/.sickrage/sickbeard/helpers.py", line 1897, in manage_torrents_url
    sickbeard.CLIENT_WEB_URLS['torrent'] = ('', torrent_ui_url)[test_exists(torrent_ui_u
  File "/home/ronald/.sickrage/sickbeard/helpers.py", line 1886, in test_exists
    h = requests.head(url)
  File "/home/ronald/.sickrage/lib/requests/api.py", line 93, in head
    return request('head', url, **kwargs)
  File "/home/ronald/.sickrage/lib/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/ronald/.sickrage/lib/requests/sessions.py", line 454, in request
    prep = self.prepare_request(req)
  File "/home/ronald/.sickrage/lib/requests/sessions.py", line 388, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/ronald/.sickrage/lib/requests/models.py", line 293, in prepare
    self.prepare_url(url, params)
  File "/home/ronald/.sickrage/lib/requests/models.py", line 353, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant
`

**Comment by sharkykh** [comment]
@rharing It doesn't seem like you are on the latest master.
What is your OS?

**Comment by paulwitt** [comment]
The problem is that this error keeps the app from running and being able to
patch to the latest commit. You have to manually edit the file or
reinstall.

**Comment by rharing** [comment]
i am on linux and did a git pull to get the latest version. however git log show me the latest commit is 4b3dad8eec3e238b1cadc809acf8e0e26deb9eb3 from april 4, i dont mind manually editing the file but i dont know which url to edit or enable/disable

**Comment by sharkykh** [comment]
```
git checkout master
git fetch
git reset --hard origin/master
```
Try that please

**Comment by rharing** [comment]
did that but still failing to start:
git checkout master
git fetch
git reset --hard origin/master
Already on 'master'
Your branch is up-to-date with 'origin/master'.
HEAD is now at 1d28b35 Update node packages and grunt....please grunt all js changes in each PR
/programs/SickRage on  master ⌚ 13:46:47
$ systemctl status sickrage.service
● sickrage.service - LSB: starts instance of SickRage
   Loaded: loaded (/etc/init.d/sickrage; bad; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2017-04-14 13:46:47 CEST; 10s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 15794 ExecStart=/etc/init.d/sickrage start (code=exited, status=1/FAILURE)

Apr 14 13:46:47 ronald-XPS-13-9343 sickrage[15794]:     hooks=merge_hooks(request.hooks, self.hooks),
Apr 14 13:46:47 ronald-XPS-13-9343 sickrage[15794]:   File "/home/ronald/.sickrage/lib/requests/models.py", line 293, in prepare
Apr 14 13:46:47 ronald-XPS-13-9343 sickrage[15794]:     self.prepare_url(url, params)
Apr 14 13:46:47 ronald-XPS-13-9343 sickrage[15794]:   File "/home/ronald/.sickrage/lib/requests/models.py", line 353, in prepare_url
Apr 14 13:46:47 ronald-XPS-13-9343 sickrage[15794]:     raise MissingSchema(error)
Apr 14 13:46:47 ronald-XPS-13-9343 sickrage[15794]: requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant
Apr 14 13:46:47 ronald-XPS-13-9343 systemd[1]: sickrage.service: Control process exited, code=exited status=1
Apr 14 13:46:47 ronald-XPS-13-9343 systemd[1]: Failed to start LSB: starts instance of SickRage.
Apr 14 13:46:47 ronald-XPS-13-9343 systemd[1]: sickrage.service: Unit entered failed state.
Apr 14 13:46:47 ronald-XPS-13-9343 systemd[1]: sickrage.service: Failed with result 'exit-code'.

**Comment by sharkykh** [comment]
When you're debugging an issue with SickRage, please don't run it using the service. It makes it easier to see the issues.

You should be able to run:
```shell
python /home/ronald/.sickrage/SickBeard.py --force-update
```
Tell me the output of this command

**Comment by rharing** [comment]
yes when i run it manuallyby python SickBeard.py after the --force-update it starts again

**Comment by sharkykh** [comment]
And if you stop SickRage now,
then run `systemctl restart sickrage.service`
does it work?

**Comment by rharing** [comment]
nope allthough i use: /etc/init.d/sickrage start resulting in
[....] Starting sickrage (via systemctl): sickrage.serviceJob for sickrage.service failed because the 

> control process exited with error code. See "systemctl status sickrage.service" and "journalctl -xe" for details.
>  failed!
> 
> ~ ⌚ 0:06:44
> $ 
> 
> ~ ⌚ 0:07:15
> $ systemctl status sickrage.service
> ● sickrage.service - LSB: starts instance of SickRage
>    Loaded: loaded (/etc/init.d/sickrage; bad; vendor preset: enabled)
>    Active: failed (Result: exit-code) since Sat 2017-04-15 00:06:44 CEST; 1min 43s ago
>      Docs: man:systemd-sysv-generator(8)
>   Process: 6243 ExecStart=/etc/init.d/sickrage start (code=exited, status=1/FAILURE)
> 
> Apr 15 00:06:44 ronald-XPS-13-9343 sickrage[6243]:     hooks=merge_hooks(request.hooks, self.hooks),
> Apr 15 00:06:44 ronald-XPS-13-9343 sickrage[6243]:   File "/home/ronald/.sickrage/lib/requests/models.py", line 293, in prepare
> Apr 15 00:06:44 ronald-XPS-13-9343 sickrage[6243]:     self.prepare_url(url, params)
> Apr 15 00:06:44 ronald-XPS-13-9343 sickrage[6243]:   File "/home/ronald/.sickrage/lib/requests/models.py", line 353, in prepare_url
> Apr 15 00:06:44 ronald-XPS-13-9343 sickrage[6243]:     raise MissingSchema(error)
> Apr 15 00:06:44 ronald-XPS-13-9343 sickrage[6243]: requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant 
> Apr 15 00:06:44 ronald-XPS-13-9343 systemd[1]: sickrage.service: Control process exited, code=exited status=1
> Apr 15 00:06:44 ronald-XPS-13-9343 systemd[1]: Failed to start LSB: starts instance of SickRage.
> Apr 15 00:06:44 ronald-XPS-13-9343 systemd[1]: sickrage.service: Unit entered failed state.
> Apr 15 00:06:44 ronald-XPS-13-9343 systemd[1]: sickrage.service: Failed with result 'exit-code'.
> lines 1-16/16 (END)
> 

>

**Comment by sharkykh** [comment]
I doesn't make sense. I think you are trying to run SickRage from a different location.
I don't use Linux so I'm not sure, but try checking your runscript config,
I think it's something like `cat /etc/default/sickrage`

**Comment by rharing** [comment]
yes indeed good catch i didnt install in home/.sickrage and in /etc/defaults the directories were set to that, didnt have that problem before though, however it is working now thanks
