### ISSUE TITLE
SickRage not starting on Synology

### ISSUE THREAD

**Issue by soothingone** [SickRage/SickRage#3595]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS: DSM 6.1-15047 Update 2
What you did: Updated DSM
What happened: Package (sickbeard-custom) not unable to start
What you expected: For the package to start
Logs: Cannot see anything in the logs
```
PASTE LOGS HERE
```

**Comment by sharkykh** [comment]
Try following the steps this user made:
https://github.com/SickRage/SickRage/issues/3594

**Comment by soothingone** [comment]
Well, all well and good that it was fixed in an update, but when you cant get it to start, its hard to get the fixed update in :)

I ended up reinstalling, with manually backing up the dbs and settings, and then it still wouldnt start, so I ended up running a "chown -r sickbeard-custom *" whn in the /volume1/@appstore/sickbeard-custom/var/ folder, this solved it

**Comment by sharkykh** [comment]
I'm hoping it will be simpler in the future,
you could update SickRage even if it stopped loading.
