### ISSUE TITLE
Add webrip as possibility in the preferred quality of a show setting.

### ISSUE THREAD

**Issue by BenjV** [SickRage/SickRage#3609]
Would it be possible to add "webrip" to the preferred quality per show.
At the moment if you choose for web-dl then sometimes you get a webrip and they are not the same.
If you use subtitles that are made for web-dl they don't sync to a webrip version.

**Comment by miigotu** [comment]
The subtitle downloader uses the original release name, it has nothing to do with the quality SickRage assigns to it. We wont be splitting webrip/webdl.

**Comment by BenjV** [comment]
You misunderstand it.
It has nothing to do with the subtitle downloader.

The issue is that when you select web-dl for a serie you sometimes get a webrip version.
I don't want a webrip version if I select web-dl. I want a web-dl version!
Most often the quality of webrip is not so good and there are often no subtitles to be found for webrip versions.

**Comment by miigotu** [comment]
so add webrip to ignored words ....
