### ISSUE TITLE
[APP SUBMITTED]: SHOWQUEUE-FORCE-UPDATE :: [4b3dad8] No data returned from theTVDB, unable to update this show.

### ISSUE THREAD

**Issue by cooleo007** [SickRage/SickRage#3614]
### INFO
Python Version: **2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]**
Operating System: **Linux-3.13.0-37-generic-x86_64-with-LinuxMint-17.3-rosa**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@4b3dad8eec3e238b1cadc809acf8e0e26deb9eb3
No Log available with ERRORS:
### ERROR
```
SHOWQUEUE-FORCE-UPDATE :: [4b3dad8] No data returned from theTVDB, unable to update this show.
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by sharkykh** [comment]
@cooleo007 What show did this happen on?

**Comment by cooleo007** [comment]
I'll check and let you know.
