### ISSUE TITLE
[APP SUBMITTED]: invalid literal for int() with base 10: 'n/a'

### ISSUE THREAD

**Issue by cooleo007** [SickRage/SickRage#3615]
### INFO
Python Version: **2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]**
Operating System: **Linux-3.13.0-37-generic-x86_64-with-LinuxMint-17.3-rosa**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@4b3dad8eec3e238b1cadc809acf8e0e26deb9eb3
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-295647 :: [ilCorsaroNero] :: [4b3dad8] Failed parsing provider. Traceback: Traceback (most recent call last):
  File "/home/leo/.sickrage/sickbeard/providers/ilcorsaronero.py", line 268, in search
    leechers = int(leechers.strip('[]'))
ValueError: invalid literal for int() with base 10: 'n/a'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by wvermeulen** [comment]
### INFO
Python Version: **2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]**
Operating System: **Linux-4.4.0-72-generic-x86_64-with-LinuxMint-18.1-serena**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@4b3dad8eec3e238b1cadc809acf8e0e26deb9eb3
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-MANUAL-311969 :: [ilCorsaroNero] :: [4b3dad8] Failed parsing provider. Traceback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/providers/ilcorsaronero.py", line 268, in search
    leechers = int(leechers.strip('[]'))
ValueError: invalid literal for int() with base 10: 'n/a'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators
