### ISSUE TITLE
Feature request: Add Brazilian Portuguese to the list of Metadata languages

### ISSUE THREAD

**Issue by chmercesmoreira** [SickRage/SickRage#3617]
Hello, currently there is no brazilian portuguese on the list (pt-BR/pob), there is only portuguese from Portugal (pt/por) that is a lot different from the brazilian one.

**Comment by sharkykh** [comment]
IIRC metadata languages are derived from the indexer, and TheTVDB.com only supports certain languages.

**Comment by chmercesmoreira** [comment]
ok... Thank you.

**Comment by sharkykh** [comment]
I believe this will be available with [TVDB API v2](https://github.com/SickRage/SickRage/pull/3588).
