### ISSUE TITLE
Manual Processing and without "delete files" ticked it still deletes files after processing

### ISSUE THREAD

**Issue by piejanssens** [SickRage/SickRage#3623]
In addition I have noticed in the past that even when processing fails some files are deleted (including mkv), this can be quite frustrating losing a valuable file.......

**Comment by sharkykh** [comment]
There are some known issues with Post-Processing right now.
#3358 will probably fix most of them, but it's probably gonna take some more time till it's merged.

Try using `copy` method for now (or anything other than `move` for that matter).
Shouldn't delete anything.
