### ISSUE TITLE
Post-processing continually extracting non-SickRage archives in download dir

### ISSUE THREAD

**Issue by connexx2** [SickRage/SickRage#3625]
Branch/Commit: master/4b3dad8
OS: Windows Server 2008 (32-bit)

Post-processing is constantly extracting non-TV releases that reside in my download directory.  It extracts the entire file, doesn't do anything with it, then extracts again on the next processing cycle, and so on.  This isn't default behavior is it?  I've had the same config for nearly 2 years and this never happened.  Other than this issue, post-processing is working fine for all of my configured shows, it just takes 2-3x longer than it should because SickRage is usually stuck in the middle of a processing cycle unraring movies.

Screenshot of behavior: [http://i.imgur.com/OFt3F4n.jpg](http://i.imgur.com/OFt3F4n.jpg)
My post-processing settings; [http://i.imgur.com/jDzHxAI.jpg](http://i.imgur.com/jDzHxAI.jpg)

Any idea what could be going on?

**Comment by miigotu** [comment]
Non-SickRage downloads should not be in SickRage's Download dir.
This is why there is a setting in the client config to set the dir for SR downloads, so that they are not in the same place as other downloads.
