### ISSUE TITLE
Karma's a B*tch! not uploading

### ISSUE THREAD

**Issue by m3rbmw** [SickRage/SickRage#3627]
2017-04-14 12:58:24 POSTPROCESSOR-AUTO :: Processing Failed
2017-04-14 12:57:20 POSTPROCESSOR-AUTO :: Processing failed for /media/Downloads/Karma's a B-tch! - s01e01 - Scorned Furies.mp4: 

v2017.04.03-1

I have all 14 episodes and I would like to import them but even though I have tried MULTIPLE combinations of characters I cannot get SickRage to recognise them.

I cannot use the * in the name and I have tried it with correct spelling and # & @ ! $ characters but nothing is working.

The folder is labelled Karma's a B-tch! but using the - doesn't work either.

**Comment by OmgImAlexis** [comment]
As it states in the issue template that you deleted please provide logs, the version of Sickrage you're running, etc. otherwise this will be closed.

**Comment by miigotu** [comment]
Why cant you use * in the name?
```bash
dusted@ROG:~/Projects/SickRage: touch "Karma's a B*tch! - s01e01 - Scorned Furies.mp4"
dusted@ROG:~/Projects/SickRage: ls Karma\'s\ a\ B\*tch\!\ -\ s01e01\ -\ Scorned\ Furies.mp4 
Karma's a B*tch! - s01e01 - Scorned Furies.mp4
```

**Comment by m3rbmw** [comment]
Because * is an unusable character in Windows. You CANNOT use it in a filename!

**Comment by miigotu** [comment]
Add the show to SR by "Add Existing" and use the "Karma's a B-tch!" folder, edit the show and on the advanced tab add a scene exception "Karma's a B-tch!

**Comment by sharkykh** [comment]
@m3rbmw Closing this as I'm assuming @miigotu's solution worked for you.
