### ISSUE TITLE
Cannot enable HTTPS/SSL

### ISSUE THREAD

**Issue by Aesculapius** [SickRage/SickRage#3628]
Branch/Commit: Master
OS: Linux
What you did: Try to enable SSL with my own certificates
What happened: SSL is automatically disabled because of lack of write permissions
What you expected: It should just eat my served certificate and work :-)
Logs:
```
2017-04-14 09:49:51 INFO TORNADO :: Starting SickRage on http://0.0.0.0:8081/
2017-04-14 09:49:51 WARNING MAIN :: Disabled HTTPS because of missing CERT and KEY files
2017-04-14 09:49:51 INFO MAIN :: Unable to create CERT/KEY files, disabling HTTPS
AA IOError: [Errno 13] Permission denied: '/opt/sickrage/server.key'
AA io.open(ssl_key, 'wb').write(crypto.dump_privatekey(crypto.FILETYPE_PEM, pkey))
AA File "/opt/sickrage/sickbeard/helpers.py", line 854, in create_https_certificates
AA Traceback (most recent call last):
2017-04-14 09:49:51 ERROR MAIN :: [4b3dad8] Error creating SSL key and certificate
2017-04-14 09:49:50 INFO MAIN :: Starting SickRage [master] using '/opt/sickrage/config.ini'
```

As I get it needs write permissions in case there has to be generated a self signed certificate, I have my own, signed, domain certificate that I want to use. So I replaced the server.key and crt files with the correct certificate files, but somehow, sickrage wants to write over them.

How do I get sickrage to use my own signed certificates?

**Comment by Aesculapius** [comment]
Ah, and when I copied the certificate files into the sickrage dir, and re-enable the HTTPS option, it seems to work - before I symlinked them, because when the certificates get renewed I'd like to spare myself from copying them over again to all the different places...

**Comment by miigotu** [comment]
Likely because SickRage does not have permissions to read the original key. Add SickRage to the group that they key belongs to and set permissions for the group to be able to read the key/cert.
