### ISSUE TITLE
Can't install inside container; Causes container to crash

### ISSUE THREAD

**Issue by danjng** [SickRage/SickRage#3632]
Spun up ubuntu container, started it, ran through install instructions here: https://www.htpcbeginner.com/install-sickrage-on-ubuntu/

Went to start service, then container host dies.

Ideas?

**Comment by OmgImAlexis** [comment]
As it states in the template you deleted you need to provide details with what happened along with logs. Just telling us a third-party site's guide isn't working doesn't help anyone at all and will likely cause this issue to be closed.

**Comment by danjng** [comment]
I think the issue had something to do with my database or existing configuration. I tried the same thing with a VM and it killed the VM (crash and reboot).

Once I cleared out the existing settings and databases and let SickRage start from a clean slate, everything was fine (and still seems fine).
