### ISSUE TITLE
[Poll] Does anyone would like maximum size function ?

### ISSUE THREAD

**Issue by ArthurGarnier** [SickRage/SickRage#3635]
Hi,

I watch my shows with Plex from dedicated server, so the size of my episode is important if I want to stream it with my ADSL and sometimes SickRage takes the first episode out (For example 720p x264 : 2,4GB) and few hours later a new episode is released (720 or 1080p x264 ou x265 1,6GB). 

The torrent size is already accessible with most providers, so I could dev this feature pretty easily. 

Does anyone would like this feature too ?

**Comment by OmgImAlexis** [comment]
Ref: http://feathub.com/SickRage/SickRage/+77
