### ISSUE TITLE
PushBullet Bug?

### ISSUE THREAD

**Issue by DJ-BrianC** [SickRage/SickRage#3641]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS: ReadyNas316
What you did:Tried to update pushbullet device list
What happened:Just keeps spinning
What you expected:The dropdown to populate
Logs:
```
PASTE LOGS HERE
```

**Comment by sharkykh** [comment]
We can't help you without logs. Enable logs in the config then try again, go to View Logs, select Level: Debug and copy then paste the logs using http://pastebin.com

**Comment by bicodegas** [comment]
I'm having the same problem on Ubuntu Trusty 14.04. Testing notification SickRage says it was successful but I don't receive it. And no device is shown on "Device List". Here's the Log:

> AA SSLError: [Errno 8] _ssl.c:510: EOF occurred in violation of protocol
> AA raise requests_exception
> AA File "/home/*******/.sickrage/sickbeard/helpers.py", line 1503, in handle_requests_exception
> 2017-04-20 16:07:27 DEBUG    Thread-35 :: Traceback (most recent call last):
> 2017-04-20 16:07:27 DEBUG    Thread-35 :: Request failed: [Errno 8] _ssl.c:510: EOF occurred in violation of protocol
> 2017-04-20 16:07:27 DEBUG    Thread-35 :: Testing Pushbullet authentication and retrieving the device list.
> AA SSLError: [Errno 8] _ssl.c:510: EOF occurred in violation of protocol
> AA raise requests_exception
> AA File "/home/*******/.sickrage/sickbeard/helpers.py", line 1503, in handle_requests_exception
> 2017-04-20 16:07:27 DEBUG    Thread-36 :: Traceback (most recent call last):
> 2017-04-20 16:07:27 DEBUG    Thread-36 :: Request failed: [Errno 8] _ssl.c:510: EOF occurred in violation of protocol
> 2017-04-20 16:07:27 DEBUG    Thread-36 :: Testing Pushbullet authentication and retrieving the device list.
> 2017-04-20 16:07:24 DEBUG    Thread-36 :: Pushbullet notification sent.
> AA SSLError: [Errno 8] _ssl.c:510: EOF occurred in violation of protocol
> AA raise requests_exception
> AA File "/home/*******/.sickrage/sickbeard/helpers.py", line 1503, in handle_requests_exception
> 2017-04-20 16:07:24 DEBUG    Thread-36 :: Traceback (most recent call last):
> 2017-04-20 16:07:24 DEBUG    Thread-36 :: Request failed: [Errno 8] _ssl.c:510: EOF occurred in violation of protocol
> 2017-04-20 16:07:24 DEBUG    Thread-36 :: Pushbullet devices: u''
> 2017-04-20 16:07:24 DEBUG    Thread-36 :: Pushbullet api: '**********************************'
> 2017-04-20 16:07:24 DEBUG    Thread-36 :: Pushbullet message: u'Testing Pushbullet settings from SickRage'
> 2017-04-20 16:07:24 DEBUG    Thread-36 :: Pushbullet event: u'Test'
> 2017-04-20 16:07:24 DEBUG    Thread-36 :: Sending a test Pushbullet notification

Cheers

**Comment by sharkykh** [comment]
Not sure but this can't hurt. Try to update your system's OpenSSL.

@miigotu any thoughts on this?

**Comment by disrani** [comment]
I was getting the same error for the past few weeks. Updating python to 2.7.9 fixed the issue for me.

**Comment by sharkykh** [comment]
@DJ-BrianC @bicodegas What are your Python versions?
Please try the fix suggested by @disrani if it applies to you.

**Comment by bicodegas** [comment]
Yes it does, my python version was 2.7.6. I updated as @disrani suggested and it fixes the issue. Sickrage now checks the devices and sends notifications as usual.
Thanks.

**Comment by DJ-BrianC** [comment]
I have a readynas 316. I'm not sure I can do this as everything is packed based from the ap store.

**Comment by sharkykh** [comment]
@DJ-BrianC do you have ssh access?
Try running `python --version` first

**Comment by DJ-BrianC** [comment]
Python package installed. No change.

**Comment by sharkykh** [comment]
@DJ-BrianC What about
> do you have ssh access?
Try running `python --version` first

**Comment by Mhynlo** [comment]
The package that is in the app store pulls python from the Debian Jessie repo. The latest version on the ReadyNAS is python version 2.7.9 at this time. I suspect the issue should be resolved now...
