### ISSUE TITLE
T411 provider has to be modified

### ISSUE THREAD

**Issue by jery19** [SickRage/SickRage#3646]
Site managers asked to change the tracker url from http://t411.download to http://tracker.t411.ai.
Old address should stop working in couple of days...
More info on the t411.ai main page (in frech).

**Comment by sharkykh** [comment]
Thank you for the notice,
however SickRage is not using the tracker address for anything.
So I don't think we need to change anything.

**Comment by jery19** [comment]
Thank you for confirming that.
