### ISSUE TITLE
[APP SUBMITTED]: Series result returned zero

### ISSUE THREAD

**Issue by Veldkornet** [SickRage/SickRage#3654]
### INFO
Python Version: **2.7.13 (default, Dec 22 2016, 09:22:15) [GCC 6.2.1 20160822]**
Operating System: **Linux-3.10.102-x86_64-with**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@1d28b358576b35b101bb0f662858ae5296d2ef8b
No Log available with ERRORS:
### ERROR
```
SHOWQUEUE-ADD :: [1d28b35] Unable to look up the show in /opt/video/Prison Break on theTVDB using ID 75340, not using the NFO. Delete .nfo and try adding manually again.: Series result returned zero
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by Veldkornet** [comment]
FYI, this happens even when adding the show from scratch

**Comment by sharkykh** [comment]
Have you tried what the error suggests?

**Comment by sharkykh** [comment]
Also please enable debug logs and try again, then post the debug logs of this action here..

**Comment by Veldkornet** [comment]
As I said, it happens even if the show doesn't exist. Just this specific show.
I'll try get the debug log up, not sure why it didn't get sent automatically.

**Comment by sharkykh** [comment]
> As I said, it happens even if the show doesn't exist. Just this specific show.

That doesn't answer my question...
In the folder `/opt/video/Prison Break`, do you have an `nfo` file?
Try removing it and trying again.

**Comment by Veldkornet** [comment]
No, there are no nfo files.

If you add the series from scratch, there is not even a folder. Everything gets created when the show is added.

**Comment by sharkykh** [comment]
Oh, sorry, didn't realize that.

Well, this is weird. And you say it only happens for Prison Break...
It works for me.
You added using **Shows** -> **Add Shows** -> **Add New Show**, or somewhere else?

**Comment by Veldkornet** [comment]
Well it added other (new and existing) shows, which is what's strange.
I tried adding it from scratch and from an existing folder.

I'm running it from [this ](https://hub.docker.com/r/linuxserver/sickrage/)Docker image on a Synology NAS.

**Comment by Veldkornet** [comment]
In a strange turn of events, I manually saved that xml as the nfo in the folder; and now it is working.... :-/

**Comment by sharkykh** [comment]
Was it able to download all of the episode information?
Show display page looks ok?

And still, don't know what the issue is...

**Comment by Veldkornet** [comment]
Yup, seems to be fine weirdly enough...

**Comment by janusn** [comment]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-4.4.59+-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@1ed315660d99f6673a3bb53363fdff6902b89429
No Log available with ERRORS:
### ERROR
```
SHOWQUEUE-ADD :: [1ed3156] Unable to look up the show in /volume2/Media/shared/TV Shows/His Dark Materials on theTVDB using ID 360295, not using the NFO. Delete .nfo and try adding manually again.: Series result returned zero
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
