### ISSUE TITLE
[APP SUBMITTED]: tuple indices must be integers, not NoneType

### ISSUE THREAD

**Issue by Wizerd** [SickRage/SickRage#3656]
### INFO
Python Version: **2.7.12 (default, Aug 20 2016, 20:35:21) [GCC 5.2.0]**
Operating System: **Linux-3.4.6-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@6e623682fca3cf37363bdb409ef0074908f1e359
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-MANUAL-246941 :: [GinggDaddy] :: [6e62368] Exception while searching GinggDaddy. Error: TypeError('tuple indices must be integers, not NoneType',)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by Wizerd** [comment]
An feedback on this one?

**Comment by sharkykh** [comment]
@Wizerd could you post the debug logs of this?
The automatic issue submitter didn't for some reason.

**Comment by bwguy** [comment]
### INFO
Python Version: **2.7.12 (default, Aug 20 2016, 20:35:21) [GCC 5.2.0]**
Operating System: **Linux-4.2.8-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@e1af3a8af8dacccfb9c7adf45f08090a68875af2
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-264234 :: [GingaDaddy] :: [e1af3a8] Exception while searching GingaDaddy. Error: TypeError('tuple indices must be integers, not NoneType',)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by bwguy** [comment]
### INFO
Python Version: **2.7.12 (default, Aug 20 2016, 20:35:21) [GCC 5.2.0]**
Operating System: **Linux-4.2.8-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@e1af3a8af8dacccfb9c7adf45f08090a68875af2
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-258204 :: [GingaDaddy] :: [e1af3a8] Exception while searching GingaDaddy. Error: TypeError('tuple indices must be integers, not NoneType',)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by bwguy** [comment]
### INFO
Python Version: **2.7.12 (default, Aug 20 2016, 20:35:21) [GCC 5.2.0]**
Operating System: **Linux-4.2.8-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@e1af3a8af8dacccfb9c7adf45f08090a68875af2
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-316951 :: [GingaDaddy] :: [e1af3a8] Exception while searching GingaDaddy. Error: TypeError('tuple indices must be integers, not NoneType',)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by sharkykh** [comment]
@Wizerd @bwguy Need debug logs to figure this one out.

**Comment by jhomack** [comment]
I have similar/same problem.  This is my error log:

AA TypeError: tuple indices must be integers, not NoneType
AA 't': ('search', 'tvsearch')[self.use_tv_search],
AA File "C:\SickRage\Sickrage\sickbeard\providers\newznab.py", line 286, in search
AA items_list += self.search(search_string, ep_obj=episode)
AA File "C:\SickRage\Sickrage\sickrage\providers\GenericProvider.py", line 155, in find_search_results
AA searchResults = curProvider.find_search_results(show, episodes, search_mode, manualSearch, downCurQuality)
AA File "C:\SickRage\Sickrage\sickbeard\search.py", line 481, in searchProviders
AA TypeError: tuple indices must be integers, not NoneType
AA 't': ('search', 'tvsearch')[self.use_tv_search],
AA File "C:\SickRage\Sickrage\sickbeard\providers\newznab.py", line 286, in search
AA items_list += self.search(search_string, ep_obj=episode)
AA File "C:\SickRage\Sickrage\sickrage\providers\GenericProvider.py", line 155, in find_search_results
AA searchResults = curProvider.find_search_results(show, episodes, search_mode, manualSearch, downCurQuality)
AA File "C:\SickRage\Sickrage\sickbeard\search.py", line 481, in searchProviders
AA Traceback (most recent call last):
2017-05-10 12:36:40 ERROR    SEARCHQUEUE-RETRY-311945 :: [GDaddy] :: [b5b2262] Exception while searching GDaddy. Error: TypeError('tuple indices must be integers, not NoneType',)

**Comment by sharkykh** [comment]
@jhomack 
I don't have an account, can you try to open this link with your credentials and give me the output you get?
https://www.gingadaddy.com/api?t=caps&apikey=your_api_key

**Comment by jhomack** [comment]
this stuff all new to me; don't feel comfortable opening link with my
credentials
I mean no harm or to offend

**Comment by bwguy** [comment]
I got this error when I opened the link using my details:

[cid:image001.png@01D2CA4A.7E9FD3C0]

Nothing else is shown

**Comment by jhomack** [comment]
I made the changes on line 286 in newznab.py per comments/commit above and so far no more error messages! Thank you for help and quick response.

Joe

**Comment by bwguy** [comment]
Thankyou so much.  Seems to have resolved for me too!!

**Comment by bwguy** [comment]
OK the error is now gone but it never finds any series even though when a manual search is done on the site, there's files there

**Comment by sharkykh** [comment]
My guess is they changed something in their API.
Is there any API documentation on the site for logged in users?

**Comment by bwguy** [comment]
Never mind, I got something to download by adding api.php at the end

https://www.gingadaddy.com/api.php

Thanks again for the help

**Comment by kearon** [comment]
### INFO
Python Version: **2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]**
Operating System: **Linux-4.10.0-20-generic-x86_64-with-Ubuntu-17.04-zesty**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@c56813972dbd79b774fab271b990881af464aa7a
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-262407 :: [GingaDaddy] :: [c568139] Exception while searching GingaDaddy. Error: TypeError('tuple indices must be integers, not NoneType',)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by kearon** [comment]
### INFO
Python Version: **2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]**
Operating System: **Linux-4.10.0-20-generic-x86_64-with-Ubuntu-17.04-zesty**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@c56813972dbd79b774fab271b990881af464aa7a
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-84336 :: [GingaDaddy] :: [c568139] Exception while searching GingaDaddy. Error: TypeError('tuple indices must be integers, not NoneType',)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by kearon** [comment]
### INFO
Python Version: **2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]**
Operating System: **Linux-4.10.0-20-generic-x86_64-with-Ubuntu-17.04-zesty**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@c56813972dbd79b774fab271b990881af464aa7a
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-110381 :: [GingaDaddy] :: [c568139] Exception while searching GingaDaddy. Error: TypeError('tuple indices must be integers, not NoneType',)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by kearon** [comment]
### INFO
Python Version: **2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]**
Operating System: **Linux-4.10.0-20-generic-x86_64-with-Ubuntu-17.04-zesty**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@c56813972dbd79b774fab271b990881af464aa7a
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-281696 :: [GingaDaddy] :: [c568139] Exception while searching GingaDaddy. Error: TypeError('tuple indices must be integers, not NoneType',)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by kearon** [comment]
### INFO
Python Version: **2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]**
Operating System: **Linux-4.10.0-20-generic-x86_64-with-Ubuntu-17.04-zesty**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@c56813972dbd79b774fab271b990881af464aa7a
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-261096 :: [GingaDaddy] :: [c568139] Exception while searching GingaDaddy. Error: TypeError('tuple indices must be integers, not NoneType',)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by kearon** [comment]
### INFO
Python Version: **2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]**
Operating System: **Linux-4.10.0-20-generic-x86_64-with-Ubuntu-17.04-zesty**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@c56813972dbd79b774fab271b990881af464aa7a
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-260315 :: [GingaDaddy] :: [c568139] Exception while searching GingaDaddy. Error: TypeError('tuple indices must be integers, not NoneType',)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by kearon** [comment]
### INFO
Python Version: **2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]**
Operating System: **Linux-4.10.0-20-generic-x86_64-with-Ubuntu-17.04-zesty**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@c56813972dbd79b774fab271b990881af464aa7a
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-81942 :: [GingaDaddy] :: [c568139] Exception while searching GingaDaddy. Error: TypeError('tuple indices must be integers, not NoneType',)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by kearon** [comment]
### INFO
Python Version: **2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]**
Operating System: **Linux-4.10.0-20-generic-x86_64-with-Ubuntu-17.04-zesty**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@c56813972dbd79b774fab271b990881af464aa7a
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-162781 :: [GingaDaddy] :: [c568139] Exception while searching GingaDaddy. Error: TypeError('tuple indices must be integers, not NoneType',)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by kearon** [comment]
### INFO
Python Version: **2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]**
Operating System: **Linux-4.10.0-20-generic-x86_64-with-Ubuntu-17.04-zesty**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@c56813972dbd79b774fab271b990881af464aa7a
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-273085 :: [GingaDaddy] :: [c568139] Exception while searching GingaDaddy. Error: TypeError('tuple indices must be integers, not NoneType',)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by kearon** [comment]
### INFO
Python Version: **2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]**
Operating System: **Linux-4.10.0-20-generic-x86_64-with-Ubuntu-17.04-zesty**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@c56813972dbd79b774fab271b990881af464aa7a
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-296762 :: [GingaDaddy] :: [c568139] Exception while searching GingaDaddy. Error: TypeError('tuple indices must be integers, not NoneType',)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by kearon** [comment]
### INFO
Python Version: **2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]**
Operating System: **Linux-4.10.0-20-generic-x86_64-with-Ubuntu-17.04-zesty**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@c56813972dbd79b774fab271b990881af464aa7a
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-260449 :: [GingaDaddy] :: [c568139] Exception while searching GingaDaddy. Error: TypeError('tuple indices must be integers, not NoneType',)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by kearon** [comment]
### INFO
Python Version: **2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]**
Operating System: **Linux-4.10.0-20-generic-x86_64-with-Ubuntu-17.04-zesty**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@c56813972dbd79b774fab271b990881af464aa7a
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-82283 :: [GingaDaddy] :: [c568139] Exception while searching GingaDaddy. Error: TypeError('tuple indices must be integers, not NoneType',)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by kearon** [comment]
### INFO
Python Version: **2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]**
Operating System: **Linux-4.10.0-20-generic-x86_64-with-Ubuntu-17.04-zesty**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@c56813972dbd79b774fab271b990881af464aa7a
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-290508 :: [GingaDaddy] :: [c568139] Exception while searching GingaDaddy. Error: TypeError('tuple indices must be integers, not NoneType',)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by kearon** [comment]
### INFO
Python Version: **2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]**
Operating System: **Linux-4.10.0-20-generic-x86_64-with-Ubuntu-17.04-zesty**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@c56813972dbd79b774fab271b990881af464aa7a
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-269159 :: [GingaDaddy] :: [c568139] Exception while searching GingaDaddy. Error: TypeError('tuple indices must be integers, not NoneType',)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by sharkykh** [comment]
@Wizerd @bwguy @kearon @jhomack 
#3748 went live. You can now update SickRage since the issue is resolved.

**Comment by kearon** [comment]
Sorry for all the multiple submits.
That update fixed the problem.
Thanks,
