### ISSUE TITLE
Show not updating

### ISSUE THREAD

**Issue by fouilloux** [SickRage/SickRage#3680]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:master
OS: openelec/kodi
What you did: I launched Sickrage in order to update my shows, for the first since since december 2016
What happened: All of the show seems to be in the state they were in the end of 2016: All of the episodes that were aired since do not appear, or appears as "not aired yet" (and I know for sure they were). I tried to refresh them, but nothing worked. 
What you expected: I expected to have the shows updated
Logs:
```
2017-04-27 18:29:21 INFO     DAILYSEARCHER :: No new released episodes found ...
2017-04-27 18:29:21 INFO     DAILYSEARCHER :: Searching for new released episodes ...
```

**Comment by sharkykh** [comment]
If you didn't run SickRage for a long time you should either wait for it to do a show refresh (does it once a day at a time specified in the config), or force a full update manually by going to **Manage > Mass Update** and selecting the checkbox under the **Update** column header, then clicking **Submit**. Let it run, it can take some time, depending on how many shows you have (you can see the progress in **Tools > Server Status**)

Also make sure the shows aren't paused.

**Comment by fouilloux** [comment]
Hi! It worked, thank you very much. How can I modify the topic to indicate the problem is solved?

**Comment by sharkykh** [comment]
You just close it (I'll do it now)

**Comment by fouilloux** [comment]
thank you very much!
