### ISSUE TITLE
[APP SUBMITTED]: Thread-14 :: [1d28b35] "/Apps/bin/git" version returned : /bin/sh: /Apps/bin/git: No such file or directory, treat as error for now

### ISSUE THREAD

**Issue by luigose** [SickRage/SickRage#3684]
### INFO
Python Version: **2.7.11 (default, May 12 2016, 12:24:40) [GCC 5.3.0]**
Operating System: **Linux-4.2.8-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: ****
Commit: SickRage/SickRage@1d28b358576b35b101bb0f662858ae5296d2ef8b
No Log available with ERRORS:
### ERROR
```
Thread-14 :: [1d28b35] "/Apps/bin/git" version returned : /bin/sh: /Apps/bin/git: No such file or directory, treat as error for now
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by luigose** [comment]
### INFO
Python Version: **2.7.11 (default, May 12 2016, 12:24:40) [GCC 5.3.0]**
Operating System: **Linux-4.2.8-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: ****
Commit: SickRage/SickRage@1d28b358576b35b101bb0f662858ae5296d2ef8b
No Log available with ERRORS:
### ERROR
```
MAIN :: [1d28b35] "/Apps/bin/git" version returned : /bin/sh: /Apps/bin/git: No such file or directory, treat as error for now
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by sharkykh** [comment]
@luigose You need to install git on your system.
This is usually done by running `sudo apt-get install git`
