### ISSUE TITLE
[APP SUBMITTED]: POSTPROCESSOR-AUTO :: [558cd35] Could not send notification to NotifyMyAndroid

### ISSUE THREAD

**Issue by pichorra** [SickRage/SickRage#3688]
### INFO
Python Version: **2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]**
Operating System: **Linux-3.13.0-117-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@558cd35a9c7dee197cced35a0db9361de1c41ca3
No Log available with ERRORS:
### ERROR
```
POSTPROCESSOR-AUTO :: [558cd35] Could not send notification to NotifyMyAndroid
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by sharkykh** [comment]
@pichorra 
Check your API key.
If your account on NMA is new I think it takes like 10 minutes for it to be available for messages.

**Comment by pichorra** [comment]
Thank you, but I opened the call without wanting to.
