### ISSUE TITLE
Torrent Download location problem when DL client is running on NAS

### ISSUE THREAD

**Issue by MadsDegn** [SickRage/SickRage#3689]
Branch/Commit: Master
OS: Ubuntu Server 16.04.2 / QNAP / Transmission
What you did: Changed my Torrent download location to a non default one as per.: https://github.com/SickRage/SickRage/issues/3625 
Setup: Ubuntu Server running Sickrage along with a QNAP NAS running Tranmission. Server is connected to the NAS via network shares.
What happened: When running non-default DL location from Sickrage, it changes the DL Dir in transmission to something that would only make sense for the server. "/networkshare/dl/completed". But that doesn't make sense for the NAS since it wants something like: "/share/MD0_DATA/dl/completed". This means that SR forces Transmission to create a new directory, which it decides to create on the RAM disk of all places. The RAM disk is only 32mb, so that fills up quickly and crashes the NAS. Luckily it's fixed by a restart. But still super annoying. 
Sadly, since SR can't leave unrelated content alone anymore, it means that each and every time I want to DL something else, I'll have to specify a path for that one thing.

**Comment by sharkykh** [comment]
@MadsDegn 
I'm not seeing anything in the code that's preventing you from entering any path you wish for Transmission (in Config -> Search Settings -> Torrent Search -> Downloaded files location).
Maybe I didn't understand you correctly.
You **can't** put `/share/MD0_DATA/dl/completed` in there?

**Comment by MadsDegn** [comment]
@sharkykh 
Ah right, that never even crossed my mind. I just pressed browse and picked a path from there. 
I just tested it, and it seems to be the solution :)
