### ISSUE TITLE
[APP SUBMITTED]: no element found: line 325, column 94

### ISSUE THREAD

**Issue by ragga64** [SickRage/SickRage#3694]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@558cd35a9c7dee197cced35a0db9361de1c41ca3
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-269653 :: [Usenet-Crawler] :: [558cd35] Unable to parse the XML of The.Goldbergs.S02.1080p.WEB-DL.DD+.5.1.x264-TrollHD, not splitting it
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by sharkykh** [comment]
I feel like this is a one-off,
Perhaps a case of a bad nzb file.
