### ISSUE TITLE
[APP SUBMITTED]: no element found: line 328, column 83

### ISSUE THREAD

**Issue by gkeen316** [SickRage/SickRage#3695]
### INFO
Python Version: **2.7.7 (default, Jun  1 2014, 14:17:13) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@558cd35a9c7dee197cced35a0db9361de1c41ca3
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-248741 :: [Usenet-Crawler] :: [558cd35] Unable to parse the XML of 2.Broke.Girls.S02.1080p.AMZN.WEB-DL.DD+.5.1.H.264-CasStudio, not splitting it
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by sharkykh** [comment]
I feel like this is a one-off,
Perhaps a case of a bad nzb file.
