### ISSUE TITLE
Nyaa Torrent has shut down

### ISSUE THREAD

**Issue by Issam2204** [SickRage/SickRage#3704]
Nyaa Torrent has been shut down.

Source: 
https://www.reddit.com/r/trackers/comments/68zyj4/update_nyaa_is_most_likely_gone_for_good/

https://torrentfreak.com/anime-torrent-site-nyaa-goes-down-after-domain-name-deactivation-170502/

**Comment by DaCaemboe** [comment]
https://nyaa.si up
