### ISSUE TITLE
HorribleSubs new RSS feed

### ISSUE THREAD

**Issue by stvkno** [SickRage/SickRage#3705]
http://horriblesubs.info/rss.php?res=all for all qualities
http://horriblesubs.info/rss.php?res=720
http://horriblesubs.info/rss.php?res=sd for 480/sd
http://horriblesubs.info/rss.php?res=1080 for 1080p

can this be used for the horriblesubs search?

**Comment by h3llrais3r** [comment]
This can be added manually as an rss provider.
No need to add this to the HorribleSubs provider.

![image](https://cloud.githubusercontent.com/assets/1945295/25721955/97fccb64-3112-11e7-9f2c-18ed51004935.png)

**Comment by sharkykh** [comment]
>Rss is typically not added to the provider,
@h3llrais3r Umm... HorribleSubs has a
