### ISSUE TITLE
Schedule Broken On Latest Update

### ISSUE THREAD

**Issue by HPMSGEN8** [SickRage/SickRage#3707]
Hi Team

Please see the below.

Branch/Commit: master / 53474edc0c971aa678bbbe0e925744963c8f47e7
OS: Synology DSM 6
What you did: Update To Latest Version
What happened: Schedule Broken
What you expected: Show Shows
Logs:
```
Mako Error
A mako error has occured. 
If this happened during an update a simple page refresh may be the solution. 
Mako errors that happen during updates may be a one time error if there were significant ui changes. 
Show/Hide Error

 File /usr/local/sickbeard-custom/var/SickBeard/gui/slick/views/schedule.mako:299, in render_content:
<%
KeyError: 'epstatus'
```

**Comment by sharkykh** [comment]
Have you tried to restart SickRage?

**Comment by HPMSGEN8** [comment]
Yes tons of time. Shutdown as well for an clean start still nothing

**Comment by sharkykh** [comment]
@HPMSGEN8 
Then I think you need to delete the mako cache.
Shutdown SickRage, go to the SR Data folder, inside cache folder, delete `mako`.
Restart SR.

**Comment by HPMSGEN8** [comment]
Is that the Path that i see in the error or can you provide the location for me please.

**Comment by sharkykh** [comment]
@HPMSGEN8 No, in your Data folder. I can't see from the logs where it is located.
Go to `http://SickRageIP:8081/config` and look for `Cache Folder:`
there's a folder named `mako` in there, delete it then start SR again.

**Comment by HPMSGEN8** [comment]
I edited the post as i found it. Thanks a lot it is working now :)
