### ISSUE TITLE
[APP SUBMITTED]: CHECKVERSION :: [53474ed] git rev-parse HEAD returned : , treat as error for now

### ISSUE THREAD

**Issue by DonZalmrol** [SickRage/SickRage#3708]
### INFO
Python Version: **2.7.13 (default, Dec 22 2016, 09:22:15) [GCC 6.2.1 20160822]**
Operating System: **Linux-3.10.102-x86_64-with**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@53474edc0c971aa678bbbe0e925744963c8f47e7
No Log available with ERRORS:
### ERROR
```
CHECKVERSION :: [53474ed] git rev-parse HEAD returned : , treat as error for now
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by sharkykh** [comment]
@DonZalmrol check git is installed on your system
try running `git version` in your terminal
