### ISSUE TITLE
Snatched Episodes showing in SCHEDULE

### ISSUE THREAD

**Issue by trancen** [SickRage/SickRage#3714]
Last update introduced SNATCHED episodes into the Schedule screen.  

I would prefer not to see what has been already snatched and only display upcoming shows. 

Branch: master
Commit: 53474edc0c971aa678bbbe0e925744963c8f47e7
Version: v2017.05.02-1
Database Version: 44.0

**Comment by sharkykh** [comment]
Merged to master
