### ISSUE TITLE
Episode not found in file re-scan

### ISSUE THREAD

**Issue by TheRealNoob** [SickRage/SickRage#3725]
So this is a pretty simple bug.  Episode not found in file scan due to the name of the episode.  I have followed recommended naming convention.
File name:  Marvel's Agents of S.H.I.E.L.D. - S01E02 - 0-8-4 - 720p WEB-DL.mkv

I suspect it is the use of the dashes that causes the issue.  When I remove the episode name (0-8-4) from the file it is identified correctly.  Logs below.

Branch/Commit:  Master / e1af3a8af8dacccfb9c7adf45f08090a68875af2
OS:  Windows-2012ServerR2-6.3.9600
What you did:  Re-Scan Files on TV Show
What happened:  Episode not found
What you expected:  Episode to be found
Logs:
```
2017-05-07 11:01:45 INFO SHOWQUEUE-REFRESH :: 263365: No episode number found in D:\TV Shows\Marvel's Agents of S.H.I.E.L.D\Season 1\Marvel's Agents of S.H.I.E.L.D. - S01E02 - 0-8-4 - 720p WEB-DL.mkv, ignoring it
2017-05-07 11:01:45 INFO SHOWQUEUE-REFRESH :: 263365: parse_result: S01 [ABD: False] [ANIME: False] [whichReg: [u'season_only']]
2017-05-07 11:01:41 INFO SHOWQUEUE-REFRESH :: Performing refresh on Marvel's Agents of S.H.I.E.L.D.
```

**Comment by h3llrais3r** [comment]
It's most likely related to the dashes in the episode name like you mentioned.
Since the separtor in the pattern is a dash, it tries to split it on the dashes with this result.
Can I advise you another naming pattern which should not give any problems?
I use it for all my series and didn't have an issue yet:

![image](https://cloud.githubusercontent.com/assets/1945295/25783729/759bab98-3361-11e7-90bf-1a9c5c2f2bde.png)

**Comment by h3llrais3r** [comment]
I did some debugging and I found out that there is something in the code that causes the 'no match' result.
@miigotu @sharkykh 
Any idea why this is done?
https://github.com/SickRage/SickRage/blob/develop/sickbeard/name_parser/parser.py#L149

Because the 'no_season' regex parses more than 4 extra_ep_num values, the matches are cleared and nothing could be found. I just tested it myself by putting the value to > 10 and now it parses with success.

What's the purpose of this check? Perhaps this can even be removed?

**Comment by sharkykh** [comment]
@h3llrais3r Yeah I asked @miigotu about this some time ago: https://github.com/SickRage/SickRage/issues/2925#issuecomment-280966290

**Comment by sharkykh** [comment]
> I just tested it myself by putting the value to > 10 and now it parses with success.

@h3llrais3r I think SR parses it as extra episodes... then it's gonna add them to the database and maybe cause some issues?

**Comment by h3llrais3r** [comment]
Ok, I saw the reasons, but shouldn't it be better to just skip that regex than to clear the matches and break the loop?

**Comment by TheRealNoob** [comment]
Is it not simpler and more fool-proof to do a query like:  *X(S|s)##(E|e)##X*
example:  *XS01e01X*
Where X is the same character on both sides of S01e01.  This seems better to me.

**Comment by h3llrais3r** [comment]
@TheRealNoob 
It's not that simple... all regexes are used when parsing...
See https://github.com/SickRage/SickRage/blob/develop/sickbeard/name_parser/regexes.py

**Comment by TheRealNoob** [comment]
I'm not expecting that  changes be made to accomodate a single episode, but I think it must be possible.  Especially considering I am following the recommended naming convention.

**Comment by h3llrais3r** [comment]
Can you show me your settings than and also where you got those recommended naming convention?
IMHO it's never a good idea to put spaces and dashes in names, certainly not for media files.
That's why I always use the pattern with the dots.

**Comment by TheRealNoob** [comment]
It's Sickrage's default naming convention, and Plex's recommended.

Season %S/%SN - S%0SE%0E - %EN - %QN

**Comment by miigotu** [comment]
@h3llrais3r add that show, add a file for that episode, and try your suggested changes.  There is absolutely a better way to fix the >10 episodes problem, the code was just added to prevent mass wrong parses added to the db, so it definitely can be improved.

**Comment by xpedicion** [comment]
I just switched to SickRage and when I imported my library, I ran into the same problem with this episode, as well. But let me add to the frenzy.

```
2017-05-09 19:19:52 INFO SHOWQUEUE-REFRESH :: 78804: No episode number found in /share/Multimedia/Serien/Doctor Who (2005)/Season 00/Doctor Who (2005) - S00E61-E65 - Pond Life - SDTV.avi, ignoring it
2017-05-09 19:19:52 INFO SHOWQUEUE-REFRESH :: 78804: parse_result: S00 [ABD: False] [ANIME: False] [whichReg: [u'season_only']]
2017-05-09 19:19:47 INFO SHOWQUEUE-REFRESH :: Performing refresh on Doctor Who (2005)
```
I figured that there was a 4 episode limit. I tried a few different names, and it would catch it (incorrectly of course but correctly according to the name) when named for example
```
Doctor Who (2005) - S00E61E62E63E64 - Pond Life - SDTV.avi
```
but not when having a 5th episode added in any way.

**Comment by miigotu** [comment]
The seldom instance that it does not correctly match one file, is MUCh better than it incorrectly matching one like `Two and a Half Men - S11E21 - Dial 1-900-Mix-a-Lot - 720p HDTV.mkv` and creating 900 episodes in the show.

**Comment by xpedicion** [comment]
Well, no doubt about that!

**Comment by h3llrais3r** [comment]
> @h3llrais3r add that show, add a file for that episode, and try your suggested changes. There is absolutely a better way to fix the >10 episodes problem, the code was just added to prevent mass wrong parses added to the db, so it definitely can be improved.
@miigotu I have tested the proposed change locally and it works for that show. So basicly we are skipping that specific regex match, not all matches...

**Comment by sharkykh** [comment]
@h3llrais3r Don't you also need to change `break` to `continue`?

**Comment by miigotu** [comment]
```python
if len(tmp_episodes) > 4:
    result.score = 0 - cur_regex_num
    continue
```

**Comment by TheRealNoob** [comment]
I updated to the latest master.  It did find my episode this time:
Marvel's Agents of S.H.I.E.L.D. - S01E02 - 0-8-4 - 720p WEB-DL.mkv

Thank you all for the great work you do :)
-TheRealNoob
