### ISSUE TITLE
[APP SUBMITTED]: set_site_message() takes exactly 4 arguments (3 given)

### ISSUE THREAD

**Issue by buzolich** [SickRage/SickRage#3726]
### INFO
Python Version: **2.7.13 (default, Feb 11 2017, 12:22:40) [GCC 6.3.1 20170109]**
Operating System: **Linux-4.9.19-unRAID-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@
No Log available with ERRORS:
### ERROR
```
Thread-20 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 287, in async_call
    result = function(**kwargs)
TypeError: set_site_message() takes exactly 4 arguments (3 given)

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by buzolich** [comment]
### INFO
Python Version: **2.7.13 (default, Feb 11 2017, 12:22:40) [GCC 6.3.1 20170109]**
Operating System: **Linux-4.9.19-unRAID-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@
No Log available with ERRORS:
### ERROR
```
Thread-15 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 287, in async_call
    result = function(**kwargs)
TypeError: set_site_message() takes exactly 4 arguments (3 given)

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by buzolich** [comment]
### INFO
Python Version: **2.7.13 (default, Feb 11 2017, 12:22:40) [GCC 6.3.1 20170109]**
Operating System: **Linux-4.9.19-unRAID-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@
No Log available with ERRORS:
### ERROR
```
Thread-16 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 287, in async_call
    result = function(**kwargs)
TypeError: set_site_message() takes exactly 4 arguments (3 given)

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by ragga64** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@b5b2262ad0acfd0ca679b1964950a147dfc5e193
No Log available with ERRORS:
### ERROR
```
Thread-500 :: [b5b2262] Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\SickRage\sickbeard\webserve.py", line 287, in async_call
    result = function(**kwargs)
TypeError: set_site_message() takes exactly 4 arguments (3 given)

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by sharkykh** [comment]
This happens only once,
when you update to b5b2262ad0acfd0ca679b1964950a147dfc5e193
After SickRage restarts (after said update) this shouldn't happen again.

@ragga64 @buzolich
