### ISSUE TITLE
Permission denied on mapped folder

### ISSUE THREAD

**Issue by Lucky38i** [SickRage/SickRage#3731]
To lay things out I set the following in /etc/fstab

```//<PC-Name>//kodi /mnt/kodi   cifs   rw,user=<username>,pass=<pass>    0  0```

This is a storage drive on my main PC that's been shared and sharing status for everyone is set to read and write (ik not safe). I put the secure stuff like PC-Name and pass in that form for secure purposes. it's properly filled in on the file.

it mounted just fine and from SSH I can view the mapped drive, it's contents as-well as create folders using `sudo mkdir`.

So when I set the root dir to /mnt/kodi on SickRage it outputs with permission denied whenever I try to add a show

Branch/Commit: [master](https://github.com/SickRage/SickRage/tree/master)
OS: Ubuntu Server 16.04.2
What you did: Set root directory to a mounted shared drive
What happened: Permission denied when adding show
What you expected: To Add show
Logs:
```
2017-05-08 19:47:07 ERROR Thread-14 :: [b5b2262] Unable to create the folder /mnt/kodi/Game of Thrones, can't add the show
AA IOError: [Errno 13] Permission denied: u'/mnt/kodi/test/sickrage-20170508194039.zip'
```

**Comment by sharkykh** [comment]
(Might be wrong, don't use Linux much)
Why would you need to use `sudo` when making a dir on the mount?
If you've given write permissions to the share login username, it should work without `sudo`.

When you get it working without `sudo`, check using SR.
Also, make sure that SR is not running as `root` user as it is not recommended. (Check in http://localhost:8081/config)

**Comment by Lucky38i** [comment]
@sharkykh SR is running as it's own user, how do I do it without sudo it says permission denied

**Comment by sharkykh** [comment]
Again, not sure,

but according to [this](https://wiki.ubuntu.com/MountWindowsSharesPermanently#Special_permissions) you need to add `uid=x` or `gid=x` to the mount options
If the SR user and your user are not the same, I'd suggest you [create a group](https://superuser.com/questions/624745/ubuntu-server-create-group-create-user-user-specific-access) and use `gid=[group_id]`

Another answer I found suggested adding `file_mode=0777,dir_mode=0777` to the options. I feel like that's too broad.

**Comment by sharkykh** [comment]
@Lucky38i 
Did any of it helped?

**Comment by Lucky38i** [comment]
@sharkykh Thanks for the suggestions it worked out relatively well. Sorry for the long response, Uni taking up my time. I gave the PC a static IP and used that instead of the PC's name also
The code below resolved the issue:
`//<PC-IP>/Kodi    /mnt/kodi     cifs user=guest, pass=, file_mode=0777, dir_mode=0777    0 0`
