### ISSUE TITLE
Remove search provider Nyaa.se (taken down)

### ISSUE THREAD

**Issue by sanlor** [SickRage/SickRage#3743]
Hello,

Unfortunately, nyaa.se was taken down and probably wont come back (at least not with that domain name). https://nyaa.pantsu.cat/ is supposed to replace it but I don't know if it actually will.
I believe that it should be removed from the list, since it wont work anyway.

Thanks!

**Comment by sharkykh** [comment]
I already removed it in https://github.com/SickRage/SickRage/commit/88506c12b6395c78339fd845a5aff6ef49b3499b
Please update your SickRage to the latest version.

If you want you may add the RSS feed of the nyaa.pantsu site as a custom torrent provider.
https://nyaa.pantsu.cat/feed?
