### ISSUE TITLE
Usenet-Crawler

### ISSUE THREAD

**Issue by nicktagz** [SickRage/SickRage#3751]
Please remove usenet-crawler from the repos.  The site is gone and the program keeps throwing errors.  Thank you.

**Comment by sharkykh** [comment]
@nicktagz Please provide proof (like an article from a reliable source or a message from the site moderators)

**Comment by nastarius** [comment]
[https://usenetreviewz.com/usenet-crawler-throws-in-the-towel](url)

**Comment by fieldingtron** [comment]
That article references an uptime monitor on their site --> https://usenetreviewz.com/usenet-crawler-review/ It looks like a lot of ups and downs recently so I imagine its throwing errors

**Comment by sharkykh** [comment]
http://usenet-crawler.com/

> Lately the site has not been very good. Loading times were terrible. 
> A few months ago we moved from a single beefy server to smaller servers to cut down costs. 
> While this has been working well in the beginning, it does not anymore. I spent hours on it but simply it has become too troublesome to maintain almost 40 instances alone. 
> Therefore I'm taking a radical decision. While our savings are low I have spent almost $1000 on a new server. 
> It has two E2600 processors, 256 GB RAM, 10 TB disks, 500 GB SSDS and plenty of spare room to upgrade. 
> This months server costs have reached almost $2000. I'm to blame here, I should have anticipated better. 
> 
> Anyway we will be back in a few days tops. 
> 
> 5/13 4:00 - New server delivered 
> 5/13 4:45 - Installed host operating system (Debian) 
> 5/13 6:30 - Installed guest operating system (CloudLinux) 
> 5/13 17:00 - Reverse proxy using openlitespeed has been prepared and chat is accessible at http://chat.usenet-crawler.com 
> 5/13 21:00 - Websocket proxying fixed and ssl certificate installed for https://chat.usenet-crawler.com

**Comment by XxUnkn0wnxX** [comment]
its not dead, its in recovery. just give admin some time to get it back up

**Comment by sharkykh** [comment]
Looks like it's up again.

**Comment by steveschow** [comment]
its up right now but I'm still getting errors, according to sickrage log it says that it tried to use the following URL, which is at least part of the problem:

`https://www.usenet-crawler.com/api?apikey=XXXXXXXX`

The usenet-crawler API authentication is not found in a subdir of the site... when I try to use it manually via web browser, its here:

`https://www.usenet-crawler!apikey=XXXXXXX`

I don't know if that is related but I can login to the site directly with the key but sickrage is producing only errors
