### ISSUE TITLE
Add new provider Nyaa.si

### ISSUE THREAD

**Issue by MrCoolse** [SickRage/SickRage#3753]
Add https://nyaa.si as a provider.

Seems like they are trying to recreate nyaa again and a horriblesub and many other is using the new provider already!

**Comment by kriegalex** [comment]
Some minimal work should be done to check the multiple clones that spawned after Nyaa closed. For now, "nyaa.si" and "nyaa.pantsu.cat" seem to be popular but they don't necessarly have the same torrents.

**Comment by stvkno** [comment]
@kriegalex admin of horriblesubs says they dont trust nyaa.pantsu.cat and wont be posting any of their torrents there and to use nyaa.si, so i think we should use nyaa.si @sharkyh

**Comment by sharkykh** [comment]
@stvkno I agree. I'm also helping them a little bit over at https://github.com/nyaadevs/nyaa
Currently I'm waiting on [my pull request over there](https://github.com/nyaadevs/nyaa/pull/51) to get merged so the RSS feed will become usable for SickRage.

**Comment by OmgImAlexis** [comment]
@sharkykh do they have plans for an actual API for just RSS?

**Comment by sharkykh** [comment]
@OmgImAlexis They are planning an API. There's currently only an upload API.
I'd say they're leaning quite positively towards Torznab. ([Based on this discussion](https://github.com/nyaadevs/nyaa/issues/18))
