### ISSUE TITLE
Cannot find  several series from tvdb while  you see them in the portal 

### ISSUE THREAD

**Issue by Biersmurf** [SickRage/SickRage#3761]
Maybe weird but I noticed  that I cannot find several series when I try to add them   but when I go to the tvdb.com website I do notice  the same  name .
As an example "Billions,Gotham,Humans  cannot be found  in Sickrage.

Am I the only one ?

**Comment by sharkykh** [comment]
Go into the **Mass Update** page. Maybe you already have those shows in your database and you didn't notice?

**Comment by sharkykh** [comment]
![image](https://cloud.githubusercontent.com/assets/10238474/26099834/aad35bd8-3a34-11e7-83a8-7083c23068e6.png)

When you search for a new show and you already have it in your database, it just doesn't show in the search results.

There's an issue about this #3631

**Comment by Biersmurf** [comment]
No i tried om purpose Some " weird" series , also checken with a friend ego experience  the same

Groet Waldo

Op 16 mei 2017 om 11:40 heeft Kfir Hadas <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


[image]<https://cloud.githubusercontent.com/assets/10238474/26099834/aad35bd8-3a34-11e7-83a8-7083c23068e6.png>

When you search for a new show and you already have it in your database, it just doesn't show in the search results.

There's an issue about this #3631<https://github.com/SickRage/SickRage/issues/3631>

**Comment by sharkykh** [comment]
@Biersmurf 
Indexer Language is set to English?

**Comment by Biersmurf** [comment]
yes we both  have it on english ( what else 😉 )

________________________________
Van: Kfir Hadas <notifications@github.com>
Verzonden: dinsdag 16 mei 2017 13:59:47
Aan: SickRage/SickRage
CC: Waldo Hogendoorn; Mention
Onderwerp: Re: [SickRage/SickRage] Cannot find several series from tvdb while you see them in the portal (#3761)


@Biersmurf<https://github.com/biersmurf>
Indexer Language is set to English?

**Comment by sharkykh** [comment]
Try enabling debug logs in General Configuration > Advanced Settings > Enable debug logs,
try to search again, then go to http://localhost:8081/errorlogs/viewlog/?min_level=10
and post the logs here. Maybe there's something there

**Comment by Biersmurf** [comment]
Just did a Mass update Alain and they are in ! ( i Will check with my friend palmfigher also)

I do notice as An example of the serie humans of this is in my portal  i"dont " get An error but get the option for alternatives why iT confused me

Groet Waldo

Op 16 mei 2017 om 14:15 heeft Kfir Hadas <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Try enabling debug logs in General Configuration > Advanced Settings > Enable debug logs,
try to search again, then go to http://localhost:8081/errorlogs/viewlog/?min_level=10
and post the logs here. Maybe there's something there

**Comment by sharkykh** [comment]
>I do notice as An example of the serie humans of this is in my portal  i"dont " get An error but get the option for alternatives why iT confused me

@Biersmurf Known issue, #3631
