### ISSUE TITLE
[APP SUBMITTED]: [Errno 13] Permission denied: u"\\\\X3D\\Mede8er\\TV Series\\Grey's Anatomy\\Season 13\\Grey's Anatomy - S13E16 - Who Is He (And What Is He To You).mkv"

### ISSUE THREAD

**Issue by MarioCaires** [SickRage/SickRage#3763]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@c56813972dbd79b774fab271b990881af464aa7a
No Log available with ERRORS:
### ERROR
```
POSTPROCESSOR-AUTO :: [c568139] [Errno 13] Permission denied: u"\\\\X3D\\Mede8er\\TV Series\\Grey's Anatomy\\Season 13\\Grey's Anatomy - S13E16 - Who Is He (And What Is He To You).mkv"
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by prantzos** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-10-10.0.16299**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@ae9ffb6ae2cc102cfa6d528f9779a6db19f82c91
Link to Log: https://gist.github.com/9c1be04bab2ed05c976a2f8c69f3c552
### ERROR
```
POSTPROCESSOR-AUTO :: [ae9ffb6] [Errno 13] Permission denied
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators
