### ISSUE TITLE
Sickrage not searching for all shows 

### ISSUE THREAD

**Issue by Comfubar** [SickRage/SickRage#3766]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:newest
OS:Windows 10
What you did:update
What happened:Animes are not being found as well as many other shows
What you expected:sickrage to find shows
Logs:

Other logs will be added as I'm doing this from mobile 
```
2017-05-18 00:49:50 POSTPROCESSOR-AUTO :: Cannot process an episode that's already been moved to its show dir, skipping E:\TOR\The Big Bang Theory
2017-05-18 00:49:50 POSTPROCESSOR-AUTO :: Cannot process an episode that's already been moved to its show dir, skipping E:\TOR\The Walking Dead
```

**Comment by sharkykh** [comment]
Are you trying to post-process a TV root folder?
You should use Add Shows -> Add Existing Shows

**Comment by Comfubar** [comment]
the post process sticks the movies into a folder with the tv show name but sometimes it does stick it in the actual folder i have on the hdd for all the tv shows

**Comment by Comfubar** [comment]
How should i set up post on qbtorrent and sickrage by change
