### ISSUE TITLE
[Feature Request] Add Support for "1337x" torrent indexer

### ISSUE THREAD

**Issue by NeoMod** [SickRage/SickRage#3769]
As per title, and due to recent events, I would like to propose the addition of [1337x](https://1337x.to/home/) to the supported torrent indexers.

Thank you.

**Comment by sharkykh** [comment]
Almost done with making this provider, but the site is not optimized for this. I have contacted them and asked them to add the torrent hash or a magnet link next to the torrents in the search result. If and when they do, I'll open a pull request for it.

**Comment by ward0** [comment]
You guys would be the first to make this provider work, sweet!

**Comment by sharkykh** [comment]
It really depends on 1337x. They didn't respond to the message I sent them almost two weeks ago. Can't make it work without having the hashes of the torrents in the search results...

**Comment by ward0** [comment]
I think thats why nobody ever got it to work :( because they don't respond to these requests.

**Comment by sharkykh** [comment]
I don't think that's going to happen.

If anyone notices a download/magnet button added to the search results page (next to every torrent), ping me (@sharkykh) here and I'll take a look.
Closing this for the time being.

**Comment by wyrickre** [comment]
I assume making another request for each result to fetch the details is not an option?

**Comment by wyrickre** [comment]
@sharkykh - Ping!  Was curious if you could answer my question above....

**Comment by sharkykh** [comment]
The answer is no. That'll cause very high traffic for the site, and that's unacceptable.
