### ISSUE TITLE
Sickrage self signed cert fails, too weak for OpenSSL 1.1.0e

### ISSUE THREAD

**Issue by binhex** [SickRage/SickRage#3770]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: GitHub release v2017.05.10-1
OS: Arch Linux x86-64
What you did: Installed SickRage and all required dependencies, including OpenSSL 1.1.0e, i then started SickRage and connected via HTTP, i then switched to HTTPS and restarted SickRage.
What happened:Attempting to start SickRage causes a traceback to be shown and SickRage does not start.
What you expected:SickRage to start and the Web UI to be accessible via HTTPS
Logs:
```
Traceback (most recent call last):
File "/opt/sickrage/lib/tornado/ioloop.py", line 888, in start
handler_func(fd_obj, events)
File "/opt/sickrage/lib/tornado/stack_context.py", line 277, in null_wrapper
return fn(*args, **kwargs)
File "/opt/sickrage/lib/tornado/netutil.py", line 276, in accept_handler
callback(connection, address)
File "/opt/sickrage/lib/tornado/tcpserver.py", line 264, in _handle_connection
do_handshake_on_connect=False)
File "/opt/sickrage/lib/tornado/netutil.py", line 517, in ssl_wrap_socket
context = ssl_options_to_context(ssl_options)
File "/opt/sickrage/lib/tornado/netutil.py", line 494, in ssl_options_to_context
context.load_cert_chain(ssl_options['certfile'], ssl_options.get('keyfile', None))
SSLError: [SSL: CA_MD_TOO_WEAK] ca md too weak (_ssl.c:2699)
```

Please note i cannot get to the Web UI as this error prevents me from starting SickRage, the above though does clearly show the cipher for the self signed cert is too weak.

**Comment by sharkykh** [comment]
@OmgImAlexis I have no experience with SSL whatsoever 

@binhex Before the server starts it tries to generate a self signed key and cert.

Try removing those from the Sickrage dir and try again.
They should be named server.crt and server.key

**Comment by sharkykh** [comment]
@binhex If you generated your own, please consider this: 
>Comment by Jan de Groot (JGC) - Wednesday, 26 April 2017, 07:46 GMT
>As said in 2nd comment, this is caused by MD5 CA certificates.
>
>I don't consider this a packaging, OpenVPN or OpenSSL bug. MD5 SSL certificates were proven insecure in 2008, Microsoft killed MD5 CA certificates in 2014, now OpenSSL on Archlinux does it in 2017. Google is pushing for SHA1 deprecation since 2014.

From https://bugs.archlinux.org/task/53831#comment157157

If you didn't, that might be an issue with the generated self signed cert and key..

**Comment by sharkykh** [comment]
@binhex Please set `enable_https` to `0` in `config.ini`, start SR, update to the latest version then try again.
Don't forget to remove the current cert & key.

**Comment by binhex** [comment]
@sharkykh will do, although i only grab releases not direct from master branch, but i will let you know asap.

**Comment by sharkykh** [comment]
@binhex Then it's on the `v2017.05.21-1` release.

**Comment by binhex** [comment]
Hi @sharkykh im afraid it looks like the change you put in hasn't completely fixed it, its still unable to boot if HTTPS is enabled, traceback from startup:-

```
2017-05-23 18:02:17,845 DEBG 'sickrage' stderr output:
18:02:17 INFO::MAIN :: Starting SickRage [master] using '/config/config.ini'

2017-05-23 18:02:17,962 DEBG 'sickrage' stderr output:
Traceback (most recent call last):
File "/opt/sickrage/SickBeard.py", line 545, in <module>
SickRage().start()
File "/opt/sickrage/SickBeard.py", line 297, in start
self.web_server = SRWebServer(self.web_options)
File "/opt/sickrage/sickbeard/webserveInit.py", line 66, in __init__

2017-05-23 18:02:17,962 DEBG 'sickrage' stderr output:
if not create_https_certificates(self.https_cert, self.https_key):
File "/opt/sickrage/sickbeard/helpers.py", line 863, in create_https_certificates
cacert = createCertificate(careq, (careq, cakey), serial, validity_period, 'sha256')
File "/opt/sickrage/lib/certgen.py", line 83, in createCertificate
cert.sign(issuerKey, digest)
File "/usr/lib/python2.7/site-packages/OpenSSL/crypto.py", line 1081, in sign
evp_md = _lib.EVP_get_digestbyname(_byte_string(digest))
TypeError: initializer for ctype 'char *' must be a str or list or tuple, not unicode
```

Just to confirm this is running the latest release of SickRage on Arch Linux 64bit using Python 2.7.13 and OpenSSL ver 1.1.0e.

The above looks like a pure Python issue and nothing to do with the cert and key generated but just incase i thought it worth mentioning that I was able to generate a valid cert and key using the OpenSSL 1.1.0e tool myself and if i configure SickRage to use this it starts successfully with HTTPS enabled, example command issued below:-

```
sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /tmp/server.key -out /tmp/server.cert
```

**Comment by sharkykh** [comment]
@binhex You are correct, sorry about that.
#3796 will fix it (tested).

```
File "/opt/sickrage/sickbeard/helpers.py", line 863, in create_https_certificates
cacert = createCertificate(careq, (careq, cakey), serial, validity_period, 'sha256')
```
The `'sha256'` here just needed to be `b'sha256'`.

**Comment by binhex** [comment]
Thanks @sharkykh i will test it in the next release.
