### ISSUE TITLE
TransmiTheNet provider has changed to Nebulance

### ISSUE THREAD

**Issue by PinaColonic** [SickRage/SickRage#3779]
Just over a month ago, TransmiTheNet (aka TransmitTheNet [sic / currently misspelled in Provider settings]) became Nebulance.io.    Would like to see this updated in the Search Providers in Sickrage.   Thank you.

**Comment by sharkykh** [comment]
Please search before opening issues.

#3747 is in develop branch. It will probably go into master on the next version release.
