### ISSUE TITLE
SickRage suddenly opening in Firefox instead of in Safari

### ISSUE THREAD

**Issue by rEes9P** [SickRage/SickRage#3785]
**Branch/Commit:** master/f5278dee021f52ef2529fdca3a9787a97249a22a

**OS:** OS X 10.12.5

**What you did:** Opened SickRage (Ran python /Applications/SickRage/SickBeard.py in Terminal)

**What happened:** SickRage opened in a new Firefox window

**What you expected:** Expected SickRage to open in Safari. Safari is my default browser and SickRage has always opened in Safari. I have not made any changes, either in SickRage or in Firefox (which I don't even use) and so am a little confused as to why this is happening since the last few days.

**Comment by OmgImAlexis** [comment]
You most likely set Firefox as your default browser. Either disable it opening in the `config.ini` or just set Safari as your default browser.

**Comment by rEes9P** [comment]
Thanks for the reply. As mentioned in the original post, Safari is my default browser (I just checked again). Also, how do I disable opening in config.ini?

**Comment by sharkykh** [comment]
Set `LAUNCH_BROWSER` to `0` or run SR with --no-launch

**Comment by rEes9P** [comment]
Sure. But any idea why SickRage uses Firefox while my default browser is set to Safari and services and links take me to Safari as usual?

**Comment by sharkykh** [comment]
SickRage is not doing anything fancy. It simply calls [webbrowser](https://docs.python.org/2/library/webbrowser.html) which is module included with Python2.
https://github.com/SickRage/SickRage/blob/master/sickbeard/__init__.py#L2403-L2422

I'm just guessing here, but if OS X has a `PATH` environment variable like Windows, maybe check that Firefox isn't in there.

Another workaround can be to set the path to the Safari executable in the `BROWSER` environment var.
