### ISSUE TITLE
Cannot download subtitles using legendas.tv

### ISSUE THREAD

**Issue by overmindbr** [SickRage/SickRage#3791]
Branch/Commit: Master and Develop branches
OS: Raspbian

I have tried to legendas.tv plugin to download subtitles. But i can't make it work. I've tried addic7ed and it seems to work fine, but legendas.tv doesnt.

There isn't much information in the log. I have tried putting a wrong password, but the log is the same. I've tried both master and develop branches and different files, but no success either.

Thanks in advance.

Logs:
```
2017-05-22 18:28:53 DEBUG Thread-18 :: 73762: No subtitles downloaded for "Show name SXXEYY"
2017-05-22 18:28:53 DEBUG Thread-18 :: No subtitles found for "Show name SXXEYY"
2017-05-22 18:28:53 DEBUG Thread-18 :: Could not search in legendastv provider. Discarding for now
2017-05-22 18:28:52 DEBUG Thread-18 :: Checking subtitle candidates for "Show name SXXEYY"(file xxxxx)
```

**Comment by sharkykh** [comment]
"Could not search * provider" usually means too many requests. Don't know what is the limit of your site. We use https://github.com/Diaoul/subliminal , so maybe the answer is there. Check the docs, search issues.

**Comment by overmindbr** [comment]
Thanks for your answer, you put me in the right direction. Found here [https://github.com/SickRage/SickRage/issues/1310](https://github.com/SickRage/SickRage/issues/1310) how to enable sublimal debugging, then, after analysing the log, i found out that unrar was missing.

Thanks :+1:
