### ISSUE TITLE
v2017.05.23-1 raises a TypeError

### ISSUE THREAD

**Issue by domibarton** [SickRage/SickRage#3795]
## Branch/Commit:
10a0c30

## OS: 
Debian 8 

## Docker Image:
[dbarton/sickrage](https://hub.docker.com/r/dbarton/sickrage/)

## What you did: 
Upgraded from `v2017.01.10-1` to `v2017.05.23-1`

## What happened: 
Can no longer start Sickrage because of a Python exception: 

```
Traceback (most recent call last):
  File "./SickBeard.py", line 545, in <module>
    SickRage().start()
  File "./SickBeard.py", line 297, in start
    self.web_server = SRWebServer(self.web_options)
  File "/sickrage/sickbeard/webserveInit.py", line 66, in __init__
    if not create_https_certificates(self.https_cert, self.https_key):
  File "/sickrage/sickbeard/helpers.py", line 863, in create_https_certificates
    cacert = createCertificate(careq, (careq, cakey), serial, validity_period, 'sha256')
  File "/sickrage/lib/certgen.py", line 83, in createCertificate
    cert.sign(issuerKey, digest)
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/crypto.py", line 1081, in sign
    evp_md = _lib.EVP_get_digestbyname(_byte_string(digest))
TypeError: initializer for ctype 'char *' must be a str or list or tuple, not unicode
```
Apparently a `str` / `unicode` error. I'm using Python 2.7 as described on the README. Is it possible that I've to upgrade to Python 3 (because of the "all strings are unicode by default now" feature) or is it a bug?

## What you expected:

Sickrage starts as usual.

**Comment by domibarton** [comment]
Or did something change in the cert handling from `v2017.01.10-1` to `v2017.05.23-1`, because I already have certs in place…

**Comment by sharkykh** [comment]
@domibarton 
Sorry about that, #3796 will fix it (tested).
And no, you do not need to upgrade to Python 3 (only 2.7 is supported).
