### ISSUE TITLE
torrent with the bad URL tracker key

### ISSUE THREAD

**Issue by lediabolo** [SickRage/SickRage#3797]
SickRage Info:
Branch: master
Commit: 10a0c3012e600ed61cdff6a6108b2bb55062907b
Version: v2017.05.23-1
Database Version: 44.0
Version de Python: 2.7.13 (default, Dec 19 2016, 02:32:04) [GCC 4.7.3 20130102 (prerelease)]
Version SSL: OpenSSL 1.0.2j 26 Sep 2016
OS: Linux-3.10.35-x86_64-with-glibc2.2.5
Local: en_US.UTF-8

SickRage is installed on a Virtual Machine (VMware) XPenology with DSM 5.2-5967 Update 2

My problem is:
I use Sickrage only with T411, and sometime, some torrents downloaded arn't with the correct Tracker private key 

My torrent client is : Synology Download Station but I've the same issue with Transmission package (of synocommunity.com)

Do you think that it's a Sickrage issue or a T411 issue ?
thanks

**Comment by miigotu** [comment]
Fairly certain its a t411 problem, when it happens just click the magnifying glass next to the episode and retry the search (mark it as failed too if you have failed download handling enabled)

**Comment by lediabolo** [comment]
thanks very much for the feedback.
I must perform maybe some tests again to validate, but it seem when I click the magnifying glass next to the episode, (by example "bones-s12e06-french-720p-hdtv-x264-sh0w" on https://www.t411.al/torrents/bones-s12e06-french-720p-hdtv-x264-sh0w ), the Sickrage download come with the following tracker URL : 
http://tracker.t411.al/6e946c3........../announce 
and this private key isn't the mine.
Have you an idea about how this bad private key is found ?
![bad_key](https://cloud.githubusercontent.com/assets/22579607/26532190/7704033c-43fa-11e7-88e1-656c1ab6be65.jpg)

**Comment by miigotu** [comment]
That is a different key, it is given by the api as a one-use key for that torrent afaik.

**Comment by lediabolo** [comment]
OK, so it's the T411 API that gives on some torrents a bad key.
The strangest thing is that it seems corrected (on this torrent), because I just tried again now and I no longer have the same key as yesterday.
Anyway, thanks for the information. I understand better how it works.
