### ISSUE TITLE
Show Specific Question Dr Who vs Dr Who 2005

### ISSUE THREAD

**Issue by mgaulton** [SickRage/SickRage#3804]
So i've noticed with latest git master (and possibly past versions) that Dr Who 2005 (various season/episodes) are getting grabbed for Dr Who 1960s episodes by mistake. Just curious what's the recommended why around this? I imagine other remake shows of the like would have similar issues.

**Comment by sharkykh** [comment]
[Scene exceptions](https://github.com/SickRage/SickRage/wiki/FAQ%27s-and-Fixes#scene-exceptions-releases-have-a-different-show-name-than-in-sickrage-and-are-not-snatched)

**Comment by mgaulton** [comment]
@sharkykh I thought that was additive to the list of options. I'm trying to set "not shows with 2005" in the scene name and I could see no way to do that.

**Comment by sharkykh** [comment]
Oh sorry I missed that in your issue, and you're right.
Umm, you could try using ignored words - set the show's ignored words to `2005`.
But that system currently has a weird issue that it doesn't always honor all of the ignored words you set.
The workaround for it seems to be this:
Copy all of your ignored words from the **general configuration** to the **show's configuration**, and insert `2005,` at the start of the list.

Then save the show's configuration and see if that solves it.

**Comment by mgaulton** [comment]
So far, i think this seems to be working. I think a decent FR would be to have the "exclude exception list""

**Comment by sharkykh** [comment]
@mgaulton 
Since Scene Exceptions **don't replace** the name we search for, only adds other variants to it,
I'd say that's not the correct term for it, and ignoring the word "2005" is actually an okay way to get the correct show to download,
even though it may be a bit obscure for some users..
