### ISSUE TITLE
[APP SUBMITTED]: SHOWQUEUE-FORCE-UPDATE :: [10a0c30] No data returned from theTVDB, unable to update this show.

### ISSUE THREAD

**Issue by lediabolo** [SickRage/SickRage#3806]
### INFO
Python Version: **2.7.13 (default, Dec 19 2016, 02:32:04) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@10a0c3012e600ed61cdff6a6108b2bb55062907b
No Log available with ERRORS:
### ERROR
```
SHOWQUEUE-FORCE-UPDATE :: [10a0c30] No data returned from theTVDB, unable to update this show.
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by HPMSGEN8** [comment]
### INFO
Python Version: **2.7.13 (default, Dec 19 2016, 02:32:04) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.77-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@10a0c3012e600ed61cdff6a6108b2bb55062907b
No Log available with ERRORS:
### ERROR
```
SHOWQUEUE-FORCE-UPDATE :: [10a0c30] No data returned from theTVDB, unable to update this show.
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by HPMSGEN8** [comment]
Hi Admins

Some of my shows are getting this and they are not even updating any more. Any advice on why this just stopped Example The Late Show with Stephen Colbert last update was 26 May 2017 and it will not update any more.

Do i need to remove any cache files or something to make this work again. 

Thanks

**Comment by sharkykh** [comment]
@HPMSGEN8 debug logs might be helpful

**Comment by HPMSGEN8** [comment]
I know but there is non. I just get that error

**Comment by sharkykh** [comment]
Look for 289574 in the logs instead.
I can't even guess what's wrong without more info, maybe try removing the shows then re-adding?

**Comment by miigotu** [comment]
Remove the show and re-add them. Likely there were dupes of the show on TVDB and one of them was removed (the one that you have)... Re-adding it to SR will make sure you have the one that is on tvdb.

**Comment by HPMSGEN8** [comment]
Thanks a lot @miigotu & @sharkykh
