### ISSUE TITLE
scene number 

### ISSUE THREAD

**Issue by kdy1968** [SickRage/SickRage#3808]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch: master
Commit: 10a0c3012e600ed61cdff6a6108b2bb55062907b
Version: v2017.05.23-1
Database Version: 44.0
OS:linux debian
What you did:for any show select scene numbering
What happened: nothing that i can tell
What you expected: i expected to be able to enter alternate season and episode numbers when the index differs from the scenes 
Logs: cant find any errors in the logs
```
PASTE LOGS HERE
```

**Comment by sharkykh** [comment]
@kdy1968 
On the show page, click on "Select Columns" on the right.
Check the `Scene` option. You can now enter scene numbering for each episode (Excluding specials)
