### ISSUE TITLE
[APP SUBMITTED]: Could not find a suitable TLS CA certificate bundle, invalid path: C:\SickRage\lib\certifi\weak.pem

### ISSUE THREAD

**Issue by divx-guy** [SickRage/SickRage#3809]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.14393**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@10a0c3012e600ed61cdff6a6108b2bb55062907b
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-75710 :: [TorrentProject] :: [10a0c30] Request failed: Could not find a suitable TLS CA certificate bundle, invalid path: C:\SickRage\lib\certifi\weak.pem
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by divx-guy** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.14393**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@10a0c3012e600ed61cdff6a6108b2bb55062907b
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-75710 :: [LimeTorrents] :: [10a0c30] Request failed: Could not find a suitable TLS CA certificate bundle, invalid path: C:\SickRage\lib\certifi\weak.pem
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by divx-guy** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.14393**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@10a0c3012e600ed61cdff6a6108b2bb55062907b
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-75710 :: [NZB-Index] :: [10a0c30] Request failed: Could not find a suitable TLS CA certificate bundle, invalid path: C:\SickRage\lib\certifi\weak.pem
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by divx-guy** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.14393**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@10a0c3012e600ed61cdff6a6108b2bb55062907b
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-75710 :: [Torrentz] :: [10a0c30] Request failed: Could not find a suitable TLS CA certificate bundle, invalid path: C:\SickRage\lib\certifi\weak.pem
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by divx-guy** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.14393**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@10a0c3012e600ed61cdff6a6108b2bb55062907b
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-75710 :: [ThePirateBay] :: [10a0c30] Request failed: Could not find a suitable TLS CA certificate bundle, invalid path: C:\SickRage\lib\certifi\weak.pem
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by divx-guy** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.14393**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@10a0c3012e600ed61cdff6a6108b2bb55062907b
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-75710 :: [SkyTorrents] :: [10a0c30] Request failed: Could not find a suitable TLS CA certificate bundle, invalid path: C:\SickRage\lib\certifi\weak.pem
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by divx-guy** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.14393**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@10a0c3012e600ed61cdff6a6108b2bb55062907b
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [LimeTorrents] :: [10a0c30] Request failed: Could not find a suitable TLS CA certificate bundle, invalid path: C:\SickRage\lib\certifi\weak.pem
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by divx-guy** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.14393**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@10a0c3012e600ed61cdff6a6108b2bb55062907b
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [ThePirateBay] :: [10a0c30] Request failed: Could not find a suitable TLS CA certificate bundle, invalid path: C:\SickRage\lib\certifi\weak.pem
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by divx-guy** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.14393**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@10a0c3012e600ed61cdff6a6108b2bb55062907b
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [TorrentProject] :: [10a0c30] Request failed: Could not find a suitable TLS CA certificate bundle, invalid path: C:\SickRage\lib\certifi\weak.pem
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by divx-guy** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.14393**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@10a0c3012e600ed61cdff6a6108b2bb55062907b
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [NZB-Index] :: [10a0c30] Request failed: Could not find a suitable TLS CA certificate bundle, invalid path: C:\SickRage\lib\certifi\weak.pem
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by divx-guy** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.14393**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@10a0c3012e600ed61cdff6a6108b2bb55062907b
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [BinSearch] :: [10a0c30] Request failed: Could not find a suitable TLS CA certificate bundle, invalid path: C:\SickRage\lib\certifi\weak.pem
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by divx-guy** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.14393**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@10a0c3012e600ed61cdff6a6108b2bb55062907b
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-75710 :: [Usenet-Crawler] :: [10a0c30] Request failed: Could not find a suitable TLS CA certificate bundle, invalid path: C:\SickRage\lib\certifi\weak.pem
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by divx-guy** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.14393**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@10a0c3012e600ed61cdff6a6108b2bb55062907b
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [Usenet-Crawler] :: [10a0c30] Request failed: Could not find a suitable TLS CA certificate bundle, invalid path: C:\SickRage\lib\certifi\weak.pem
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by divx-guy** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.14393**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@10a0c3012e600ed61cdff6a6108b2bb55062907b
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [SkyTorrents] :: [10a0c30] Request failed: Could not find a suitable TLS CA certificate bundle, invalid path: C:\SickRage\lib\certifi\weak.pem
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by divx-guy** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.14393**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@10a0c3012e600ed61cdff6a6108b2bb55062907b
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-308846 :: [NZB-Index] :: [10a0c30] Request failed: Could not find a suitable TLS CA certificate bundle, invalid path: C:\SickRage\lib\certifi\weak.pem
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by divx-guy** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.14393**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@10a0c3012e600ed61cdff6a6108b2bb55062907b
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-308846 :: [LimeTorrents] :: [10a0c30] Request failed: Could not find a suitable TLS CA certificate bundle, invalid path: C:\SickRage\lib\certifi\weak.pem
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by divx-guy** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.14393**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@10a0c3012e600ed61cdff6a6108b2bb55062907b
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-308846 :: [TorrentProject] :: [10a0c30] Request failed: Could not find a suitable TLS CA certificate bundle, invalid path: C:\SickRage\lib\certifi\weak.pem
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by divx-guy** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.14393**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@10a0c3012e600ed61cdff6a6108b2bb55062907b
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-308846 :: [Torrentz] :: [10a0c30] Request failed: Could not find a suitable TLS CA certificate bundle, invalid path: C:\SickRage\lib\certifi\weak.pem
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by divx-guy** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.14393**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@10a0c3012e600ed61cdff6a6108b2bb55062907b
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-308846 :: [Usenet-Crawler] :: [10a0c30] Request failed: Could not find a suitable TLS CA certificate bundle, invalid path: C:\SickRage\lib\certifi\weak.pem
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by divx-guy** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.14393**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@10a0c3012e600ed61cdff6a6108b2bb55062907b
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-308846 :: [SkyTorrents] :: [10a0c30] Request failed: Could not find a suitable TLS CA certificate bundle, invalid path: C:\SickRage\lib\certifi\weak.pem
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by divx-guy** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.14393**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@10a0c3012e600ed61cdff6a6108b2bb55062907b
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-308846 :: [ThePirateBay] :: [10a0c30] Request failed: Could not find a suitable TLS CA certificate bundle, invalid path: C:\SickRage\lib\certifi\weak.pem
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by divx-guy** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.14393**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@10a0c3012e600ed61cdff6a6108b2bb55062907b
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-309893 :: [NZB-Index] :: [10a0c30] Request failed: Could not find a suitable TLS CA certificate bundle, invalid path: C:\SickRage\lib\certifi\weak.pem
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by divx-guy** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.14393**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@10a0c3012e600ed61cdff6a6108b2bb55062907b
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-309893 :: [LimeTorrents] :: [10a0c30] Request failed: Could not find a suitable TLS CA certificate bundle, invalid path: C:\SickRage\lib\certifi\weak.pem
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by divx-guy** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.14393**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@10a0c3012e600ed61cdff6a6108b2bb55062907b
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-309893 :: [ThePirateBay] :: [10a0c30] Request failed: Could not find a suitable TLS CA certificate bundle, invalid path: C:\SickRage\lib\certifi\weak.pem
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by divx-guy** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.14393**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@10a0c3012e600ed61cdff6a6108b2bb55062907b
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-309893 :: [TorrentProject] :: [10a0c30] Request failed: Could not find a suitable TLS CA certificate bundle, invalid path: C:\SickRage\lib\certifi\weak.pem
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by divx-guy** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.14393**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@10a0c3012e600ed61cdff6a6108b2bb55062907b
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-309893 :: [Torrentz] :: [10a0c30] Request failed: Could not find a suitable TLS CA certificate bundle, invalid path: C:\SickRage\lib\certifi\weak.pem
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by divx-guy** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.14393**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@10a0c3012e600ed61cdff6a6108b2bb55062907b
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-309893 :: [SkyTorrents] :: [10a0c30] Request failed: Could not find a suitable TLS CA certificate bundle, invalid path: C:\SickRage\lib\certifi\weak.pem
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by divx-guy** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.14393**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@10a0c3012e600ed61cdff6a6108b2bb55062907b
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-317852 :: [LimeTorrents] :: [10a0c30] Request failed: Could not find a suitable TLS CA certificate bundle, invalid path: C:\SickRage\lib\certifi\weak.pem
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by divx-guy** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.14393**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@10a0c3012e600ed61cdff6a6108b2bb55062907b
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-317852 :: [Torrentz] :: [10a0c30] Request failed: Could not find a suitable TLS CA certificate bundle, invalid path: C:\SickRage\lib\certifi\weak.pem
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by divx-guy** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.14393**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@10a0c3012e600ed61cdff6a6108b2bb55062907b
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-317852 :: [Usenet-Crawler] :: [10a0c30] Request failed: Could not find a suitable TLS CA certificate bundle, invalid path: C:\SickRage\lib\certifi\weak.pem
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by divx-guy** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.14393**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@10a0c3012e600ed61cdff6a6108b2bb55062907b
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-317852 :: [ThePirateBay] :: [10a0c30] Request failed: Could not find a suitable TLS CA certificate bundle, invalid path: C:\SickRage\lib\certifi\weak.pem
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by divx-guy** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.14393**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@10a0c3012e600ed61cdff6a6108b2bb55062907b
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-317852 :: [TorrentProject] :: [10a0c30] Request failed: Could not find a suitable TLS CA certificate bundle, invalid path: C:\SickRage\lib\certifi\weak.pem
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by divx-guy** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.14393**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@10a0c3012e600ed61cdff6a6108b2bb55062907b
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-317852 :: [SkyTorrents] :: [10a0c30] Request failed: Could not find a suitable TLS CA certificate bundle, invalid path: C:\SickRage\lib\certifi\weak.pem
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by divx-guy** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.14393**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@10a0c3012e600ed61cdff6a6108b2bb55062907b
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-317852 :: [NZB-Index] :: [10a0c30] Request failed: Could not find a suitable TLS CA certificate bundle, invalid path: C:\SickRage\lib\certifi\weak.pem
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by divx-guy** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.14393**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@10a0c3012e600ed61cdff6a6108b2bb55062907b
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-311945 :: [NZB-Index] :: [10a0c30] Request failed: Could not find a suitable TLS CA certificate bundle, invalid path: C:\SickRage\lib\certifi\weak.pem
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by divx-guy** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.14393**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@10a0c3012e600ed61cdff6a6108b2bb55062907b
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-311945 :: [LimeTorrents] :: [10a0c30] Request failed: Could not find a suitable TLS CA certificate bundle, invalid path: C:\SickRage\lib\certifi\weak.pem
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by divx-guy** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.14393**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@10a0c3012e600ed61cdff6a6108b2bb55062907b
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-311945 :: [Torrentz] :: [10a0c30] Request failed: Could not find a suitable TLS CA certificate bundle, invalid path: C:\SickRage\lib\certifi\weak.pem
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by divx-guy** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.14393**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@10a0c3012e600ed61cdff6a6108b2bb55062907b
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-311945 :: [TorrentProject] :: [10a0c30] Request failed: Could not find a suitable TLS CA certificate bundle, invalid path: C:\SickRage\lib\certifi\weak.pem
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by divx-guy** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.14393**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@10a0c3012e600ed61cdff6a6108b2bb55062907b
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-311945 :: [SkyTorrents] :: [10a0c30] Request failed: Could not find a suitable TLS CA certificate bundle, invalid path: C:\SickRage\lib\certifi\weak.pem
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by divx-guy** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.14393**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@10a0c3012e600ed61cdff6a6108b2bb55062907b
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-311945 :: [Usenet-Crawler] :: [10a0c30] Request failed: Could not find a suitable TLS CA certificate bundle, invalid path: C:\SickRage\lib\certifi\weak.pem
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by divx-guy** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.14393**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@10a0c3012e600ed61cdff6a6108b2bb55062907b
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-311945 :: [ThePirateBay] :: [10a0c30] Request failed: Could not find a suitable TLS CA certificate bundle, invalid path: C:\SickRage\lib\certifi\weak.pem
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by divx-guy** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.14393**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@10a0c3012e600ed61cdff6a6108b2bb55062907b
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [Torrentz] :: [10a0c30] Request failed: Could not find a suitable TLS CA certificate bundle, invalid path: C:\SickRage\lib\certifi\weak.pem
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by sharkykh** [comment]
@divx-guy 
- Update SickRage.
- Make sure you have that file.
- If it still doesn't work, disable `Verify SSL Certs` in Config -> General -> Advanced Settings.
