### ISSUE TITLE
[APP SUBMITTED]: viewlog() got an unexpected keyword argument 'category'

### ISSUE THREAD

**Issue by ward0** [SickRage/SickRage#3819]
### INFO
Python Version: **2.7.13 (default, Dec 18 2016, 21:23:50) [GCC 4.6.4]**
Operating System: **Linux-3.2.40-armv7l-with-glibc2.4**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@10a0c3012e600ed61cdff6a6108b2bb55062907b
No Log available with ERRORS:
### ERROR
```
Thread-17 :: [10a0c30] Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 287, in async_call
    result = function(**kwargs)
TypeError: viewlog() got an unexpected keyword argument 'category'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by sharkykh** [comment]
If you want to filter the log, use the `Filter` select box in the View Log page.
