### ISSUE TITLE
torrentday url problem

### ISSUE THREAD

**Issue by MadKezza** [SickRage/SickRage#3828]
Branch/Commit: master
OS: QNAP NAS

What you did: I have found an error with the url set in sickrage for torrentday

What happened: the issue is it appends '**classic**.torrentday.com' instead of '**www**.torrentday.com'

What you expected: copying the link in the log and pasting in browser returns a message of 'Sorry pal :(' but changing the word 'classic' to 'www' works

Logs:
```
2017-06-04 21:39:00 INFO     SEARCHQUEUE-BACKLOG-77544 :: Request failed: 404 Client Error: Not Found for url: https://classic.torrentday.com/download.php/1575138/Andromeda.S01-S05.DVDRip.x264-NOGRP.torrent
```

**Comment by sharkykh** [comment]
In the meantime, you may change the url locally by setting a custom url for the provider in its settings.

**Comment by MasterCtrl** [comment]
for anyone interested the you need the whole "https://www.torrentday.com/download.php/" in the custom url for it to work. everything else seems to work fine.
