### ISSUE TITLE
[APP SUBMITTED]: CRC check failed 0xfe979c51L != 0x731a8c5eL

### ISSUE THREAD

**Issue by cmmmota** [SickRage/SickRage#3829]
### INFO
Python Version: **2.7.13 (default, Mar  2 2017, 11:37:04) [GCC 6.2.0]**
Operating System: **Linux-4.9.13-armv7l-with-glibc2.4**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@c1d4fd232f9e052063e08630b36c9cdd351e0e5a
No Log available with ERRORS:
### ERROR
```
Thread-543 :: [c1d4fd2] Error while trying to update: CRC check failed 0xfe979c51L != 0x731a8c5eL
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by cmmmota** [comment]
### INFO
Python Version: **2.7.13 (default, Mar  2 2017, 11:37:04) [GCC 6.2.0]**
Operating System: **Linux-4.9.13-armv7l-with-glibc2.4**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@c1d4fd232f9e052063e08630b36c9cdd351e0e5a
No Log available with ERRORS:
### ERROR
```
Thread-544 :: [c1d4fd2] Error while trying to update: CRC check failed 0xfe979c51L != 0x731a8c5eL
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by sharkykh** [comment]
Shutdown SickRage, then try updating using this command line:
```
python /path/to/SickBeard.py --force-update
```

**Comment by sharkykh** [comment]
@cmmmota Waiting on your response.

**Comment by itsme9x** [comment]
I have the same kind of error:

```2018-03-19 22:05:37 Thread-14 :: [53e6cc5] Error while trying to update: CRC check failed 0xc6640640L != 0x8f0e252L```

After trying your solution I got the following error:

```
No handlers could be found for logger "sickrage"
Failed to force an update.
```
