### ISSUE TITLE
[APP SUBMITTED]: [Errno 2] No such file or directory: '/media/disk2/downloads/TV/The.Americans.2013.S05E13.PROPER.720p.HDTV.x264-KILLERS ReUp/8f9968ce851a4fc4aae71bcd9f321588.mkv'

### ISSUE THREAD

**Issue by PipingR** [SickRage/SickRage#3831]
### INFO
Python Version: **2.7.3 (default, Oct 26 2016, 21:01:49) [GCC 4.6.3]**
Operating System: **Linux-3.13.0-67-generic-x86_64-with-Ubuntu-12.04-precise**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@10a0c3012e600ed61cdff6a6108b2bb55062907b
No Log available with ERRORS:
### ERROR
```
POSTPROCESSOR-AUTO :: [10a0c30] [Errno 2] No such file or directory: '/media/disk2/downloads/TV/The.Americans.2013.S05E13.PROPER.720p.HDTV.x264-KILLERS ReUp/8f9968ce851a4fc4aae71bcd9f321588.mkv'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by PipingR** [comment]
### INFO
Python Version: **2.7.3 (default, Oct 26 2016, 21:01:49) [GCC 4.6.3]**
Operating System: **Linux-3.13.0-67-generic-x86_64-with-Ubuntu-12.04-precise**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@10a0c3012e600ed61cdff6a6108b2bb55062907b
No Log available with ERRORS:
### ERROR
```
POSTPROCESSOR-AUTO :: [10a0c30] Unable to move file /media/disk2/downloads/TV/The.Americans.2013.S05E13.PROPER.720p.HDTV.x264-KILLERS ReUp/8f9968ce851a4fc4aae71bcd9f321588.mkv to /mnt/hgfs/DrTV/The Americans (2013)/Season 05/The Americans (2013) - S05E13 - The Soviet Division - 720p.HDTV.mkv: error 2 : No such file or directory
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by WebSpider** [comment]
Is this bug report still relevant ?

**Comment by PipingR** [comment]
Just closed it, thank you for the reminder.
