### ISSUE TITLE
Sort by downloads - Incomplete being mixed with complete series

### ISSUE THREAD

**Issue by rutskiuk** [SickRage/SickRage#3856]
I have noticed that for some shows, specifically The Simpsons that they show among the 100% complete series even when an episode is missing. Is it because there are that many the percentage of downloaded episodes is being rounded up to 100%?

![image](https://user-images.githubusercontent.com/25068977/27074221-61b5d9c6-501e-11e7-89e8-d06b4f7aa137.png)

I have checked and there is an episode missing and thinking back this has happened from time to time before. I would have expected to see this entry on the threshold between the complete and incomplete series (as a reminder to me to find what happened).

Branch: master
Commit: 96b53dee713dc35ebf295d0f37a67b2a36fb4ea3
Version: v2017.06.05-1
Database Version: 44.0

Is there something obvious that I'm missing?

**Comment by sharkykh** [comment]
In the "Select Columns" above the episode list, enable File Name, then the episode that doesn't have a filename is the one.
That's usually the case.

**Comment by rutskiuk** [comment]
I know what you're referring to, it's a handy option for tracking down the needed episodes.

What I'm getting at is that a show that isn't 100% completed shouldn't appear among the 100% completed shows when I sort by the Downloads field. If I were missing one episode then I work it out as 99.84% complete. Interestingly, the colour of the progress bar acknowledges that so I'm not sure why the sort criteria doesn't.

**Comment by sharkykh** [comment]
The sorter is a 3rd party javascript package. So maybe it rounds the decimal numbers up...
