### ISSUE TITLE
Maximum Number of Spanned Episodes?

### ISSUE THREAD

**Issue by rutskiuk** [SickRage/SickRage#3857]
Hi there,

I have noticed that SickRage doesn't recognise files that span more than four episodes. I did a bit of tinkering with renaming and found I frequently received a 'no episode number' error if the file spanned more than four episodes.

Original file with 6 episodes
![image](https://user-images.githubusercontent.com/25068977/27093433-905ba0f4-505e-11e7-89a8-9ce7364ed1e0.png)

Renamed file with 5 episodes
![image](https://user-images.githubusercontent.com/25068977/27093469-b7179ef0-505e-11e7-907d-bc3198dd8e44.png)

Accepted file with 4 episodes
![image](https://user-images.githubusercontent.com/25068977/27093512-e27210b2-505e-11e7-9ec4-9a89e4e7ee0e.png)

Branch: master
Commit: 96b53dee713dc35ebf295d0f37a67b2a36fb4ea3
Version: v2017.06.05-1
Database Version: 44.0

I have also tried removing and re-adding the show and forcing a full update just in case there was some problem with the individual episodes. Is there a limitation in SickRage preventing spanned episode files with more than 4 episodes? I totally understand a spanned episode doesn't work when crossing between seasons but I thought within a season there wouldn't be a limit. Am I wrong?
Obviously I can mark the files as downloaded but SickRage should be able to do this for me.

**Comment by sharkykh** [comment]
> Is there a limitation in SickRage preventing spanned episode files with more than 4 episodes?

Yes.
It's been discussed at least twice, please search a little before opening an issue.
1. Reason explained by @miigotu in #2925 
2. #3501

**Comment by miigotu** [comment]
Don't think Dr. Who ever aired an episode that was 4x episode time long.  The only reason multi-episode files are valid is for example when a special such as "special one hour episode" when the show is normally 30 minutes, the scene says this is 2 episodes in one.  These people who add 10 episodes or whole seasons to one file do not follow scene rules, and scene is what SR adheres to.

**Comment by rutskiuk** [comment]
I don't think the point is whether an aired episode was more then one episode in duration. Most of early Doctor Who were multi episode arcs with single stories. It is entirely likely that someone would rip their own media and group by story.
Some shows have particularly short duration but a large number of episodes. The only copy of Star Wars Clone Wars (2003) I could find (and can find now) was one file which spanned the first two seasons.
Personally speaking I dislike spanned episodes, it causes confusion whenever I have to deal with them. I would just rather name them correctly than manually split them or fudge it by marking them as downloaded manually.
Thanks for taking a look and getting back to me. I can see the decision made is best for the automation of downloads, especially with complication added if appending the episode names.
