### ISSUE TITLE
Error when trying to update

### ISSUE THREAD

**Issue by unabatedshagie** [SickRage/SickRage#3864]
When SickRage tries to update or I try and update via the menu option I'm getting the following error:
```
2017-06-14 22:26:00 Thread-16 :: git symbolic-ref -q HEAD returned : (128) fatal: bad config file line 1 in .git/config
2017-06-14 22:26:00 Thread-16 :: git rev-parse HEAD returned : (128) fatal: bad config file line 1 in .git/config
```
I've tried using the manual update instructions [here](https://github.com/SickRage/sickrage.github.io/blob/master/README.md), but I get the following error:

```
pi@bananapipro:/opt/sickrage$ sudo git remote set-url origin https://github.com/SickRage/SickRage.git
fatal: bad config file line 1 in .git/config
```

Not sure what to try next?

**Comment by sharkykh** [comment]
Your git configuration is corrupted, this usually happens when the the computer/application is shut down in the midst of a git operation.
You can post your `/path/to/SickRage/.git/config` file and I can fix it,
or you can edit the file, and set the contents to:
```ini
[remote "origin"]
	url = https://github.com/SickRage/SickRage.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
	remote = origin
	merge = refs/heads/master

```

**Comment by unabatedshagie** [comment]
Is that the whole content of the file?

Is there any special encoding for it as when I try and open it in nano the content is all garbled, I assume this is the cause of the problem?

**Comment by sharkykh** [comment]
@unabatedshagie 
Yes, that should be enough, might be missing some configuration though..
No special encoding, this is a simple text file.
Yep, seems like the config is indeed corrupt...

**Comment by unabatedshagie** [comment]
@sharkykh 

I've edited the file in nano and copied the config you wrote with sickrage stopped.

When I restart it I'm getting the following errors:

```
2017-06-14 23:18:06 Thread-14 :: [96b53de] git fetch origin returned : error: unable to resolve reference refs/remotes/origin/develop: Invalid argument
From https://github.com/SickRage/SickRage
! [new branch] develop -> origin/develop (unable to update local ref)
error: unable to resolve reference refs/remotes/origin/feature/requirements: Invalid argument
! [new branch] feature/requirements -> origin/feature/requirements (unable to update local ref)
```

**Comment by sharkykh** [comment]
@unabatedshagie 
https://stackoverflow.com/a/7348934/7597273
> Try cleaning-up your local repository with:
> ```
> $ git gc --prune=now
> $ git remote prune origin
> ```

**Comment by sharkykh** [comment]
If this does not help:
```
rm .git/refs/remotes/origin/develop
rm .git/refs/remotes/origin/feature/requirements
```
(But there might be more, try `git fetch origin` until it doesn't error)

**Comment by unabatedshagie** [comment]
Thank you!

Had to run all the four commands you gave me but it seems to be checking for updates without erroring now.

I owe you a beer!
