### ISSUE TITLE
QQ: "reset" series for a given location

### ISSUE THREAD

**Issue by mgaulton** [SickRage/SickRage#3865]
I'm trying to determine if there is a way to programatically / api reset the status of episodes to wanted based on the shows location.
background: i had a disk die and all of my anime and all of my newer series were lost. all were located under /mnt/mybookb so if i can say "if location = /mnt/mybookb/* then status = wanted" somehow, but I havent found a method yet.
Any suggestions?

**Comment by sharkykh** [comment]
The options aren't that extensive...
Only way I can think of is by editing the `sickbeard.db` database file.
**Do this at your own risk!!!**
**Always backup the file before you edit it!**

1. Stop SR
2. Go to https://sqliteonline.com/
3. File -> DB Open -> Choose your `sickbeard.db` file
4. On the left, double-click `tv_episodes`
5. Above the list, in the textbox that says `SELECT * FROM tv_episodes;`, type this:
`UPDATE tv_episodes SET status = 3 WHERE location LIKE '/mnt/mybookb/%';`
6. Click the `► Run` button.
7. File -> DB Save -> Save over your `sickbeard.db` file
**[MAKE SURE you have a backup to restore to if anything went wrong]**
8. Start SR

**Comment by mgaulton** [comment]
ok. that sounds like what I need. Thank you. I'll give that a shot

**Comment by sharkykh** [comment]
@mgaulton 
All good? Can I close this?
