### ISSUE TITLE
Missing Shows in SickRage

### ISSUE THREAD

**Issue by dd6905** [SickRage/SickRage#3881]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS: Win7
What you did: tried to add "Colony" show
What happened: It could not find the show that is in Season 2 now and expecting season 3
What you expected: The show should be found
Logs:
```
PASTE LOGS HERE
```
Hello. This problem has happened before but I did not track which shows as I thought there was
just a lag from when new shows showed up into SickRage. It has happend about 5-10 shows. This time I decided to file a problem report with the details. I tried to add "Colony" show which has been running more than 1 season, and the show exists in both IMDB.com and TVDB.com, but I can't seem to get the show added. I tried both English and all the indexer combos.

**Comment by sharkykh** [comment]
Verify that you don't already have the show using the Manage -> Mass Update table / page.

**Comment by dd6905** [comment]
Colony had a special in Nov 2015, but S01E01 showed up in 2016. There is "The Colony" 2009, but that is not the same show.

**Comment by sharkykh** [comment]
Enable debug logs, search for the show again. Check the debug logs.
Also, what indexer combinations? We only have TVDB. Are you sure you're on the correct SickRage fork?

**Comment by dd6905** [comment]
Hmm. Sorry, I feel like a d**bsh*t now. It was already added. A warning that it was already added would be nice as I couldn't figure out why. I didn't remember adding the show. I had this similar problem with a bunch of other shows that were season 1, but I didn't track it. I'll see if i can find another show and verify it, but I know for sure I didn't add those shows since they were new.

**Comment by sharkykh** [comment]
> A warning that it was already added would be nice as I couldn't figure out why.

Requested in #3631,
Just opened #3882 that'll fix this.
