### ISSUE TITLE
Adding from IMDB doesen't work

### ISSUE THREAD

**Issue by SmilerRyan** [SickRage/SickRage#3894]
Branch/Commit: Main(Installer version)
OS: Windows 7 Professional (x64)
What you did: Clicked add, chose IMDB, added a show
What happened: It gave an error whitch I don't understand
What you expected: The movie to be added to the list of shows
Logs:

Mako Error
A mako error has occured.
If this happened during an update a simple page refresh may be the solution.
 Mako errors that happen during updates may be a one time error if there were significant ui changes. 

File C:\SickRage\SickRage\sickbeard\show_queue.py:279, in show_name: return self.show.name if self.show else self.showDir.rsplit(os.sep)[-1] AttributeError: 'NoneType' object has no attribute 'rsplit'

**Comment by sharkykh** [comment]
If this is your first show, you need to add a TV Root Dir in the General configyration

**Comment by below9k** [comment]
Just had this happen to me after adding a couple of shows from IMDB.
> If this is your first show, you need to add a TV Root Dir in the General configuration
Definitely wasn't my first show, but I did recently change my default save directory - a couple hours before. Setting the default root directory in general, even though it said it was already set, then saving seems to have fixed it up again.

**Comment by miigotu** [comment]
#4224
