### ISSUE TITLE
Doctor Who 2005 continually searches for episodes exactly 7 years older than current date

### ISSUE THREAD

**Issue by Fetchered** [SickRage/SickRage#3897]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master/96b53dee713dc35ebf295d0f37a67b2a36fb4ea3
OS: QNAP QTS 4.3.3.0210
What you did: Added the show
What happened: The below details in the logs has been happening every day since the show was added.
What you expected: For this not to happen. Shows up in my warnings daily. 
Logs:
```
2017-06-30 01:05:53 SHOWQUEUE-REFRESH :: Unable to find episode with date 2010-06-30 for show Doctor Who (2005), skipping
2017-06-29 01:10:41 SHOWQUEUE-REFRESH :: Unable to find episode with date 2010-06-29 for show Doctor Who (2005), skipping
2017-06-27 01:00:15 SHOWQUEUE-REFRESH :: Unable to find episode with date 2010-06-27 for show Doctor Who (2005), skipping
```

**Comment by sharkykh** [comment]
Disable Air-By-Date setting in the show settings.

**Comment by Fetchered** [comment]
It is not enabled.

**Comment by sharkykh** [comment]
The code suggests otherwise.. try enabling it and saving then disabling it and saving.

**Comment by sharkykh** [comment]
This could also possibly be due to a video file in the show folder that isn't named properly?

**Comment by Fetchered** [comment]
Tried your suggestions, so far it seems like it's working (hasn't tried to search for those for the last couple of days). We'll see how it goes for the next couple.
Thanks!

**Comment by Arcanemagus** [comment]
I've seen this before with this show and the dates it searched for always matched up with specials that it was searching for.
