### ISSUE TITLE
RARBG Using search_tvdb in query

### ISSUE THREAD

**Issue by mabelisle** [SickRage/SickRage#3898]
Branch/Commit: v2017.06.05-1
OS: FreeBSD

What you did: I can't get any results for this query but with a manual search, there is plenty of results.

What happened: I investigated and it seems that the error come from the "&search_tvdb=70533" argument. If I remove it or replace it with "&search_imdb=tt4093826", I get my results.

What you expected: There is definitely a problem using tvdb in Rarbg. I am not sure what is the reason but it seems that rarbg is using IMDB to catalog their TV Shows so I don't understand why the searches are made with the TVDB arguments. It is clearly causing a problem in this case.

**You will need to replace to token with a valid one to reproduce.

Logs:
2017-07-01 20:09:02 DEBUG SEARCHQUEUE-BACKLOG-70533 :: [Rarbg] :: GET URL: http://torrentapi.org/pubapi_v2.php?sort=seeders&min_leechers=0&min_seeders=1&search_tvdb=70533&app_id=sickrage2&search_string=Twin+Peaks+S03E08&ranked=0&category=tv&format=json_extended&token=ler7xct5d1&limit=100&mode=search [Status: 200]

{"error":"No results found","error_code":20}

Working query: 
http://torrentapi.org/pubapi_v2.php?sort=seeders&min_leechers=0&min_seeders=1&search_imdb=tt4093826&app_id=sickrage2&search_string=Twin+Peaks+S03E08&ranked=0&category=tv&format=json_extended&token=ler7xct5d1&limit=100&mode=search

or

http://torrentapi.org/pubapi_v2.php?sort=seeders&min_leechers=0&min_seeders=1&app_id=sickrage2&search_string=Twin+Peaks+S03E08&ranked=0&category=tv&format=json_extended&token=ler7xct5d1&limit=100&mode=search

**Comment by 2twisty** [comment]
I, too am having this exact same issue.  Please advise.

**Comment by sharkykh** [comment]
I think some episodes are not linked to a tvdb id, like https://rarbg.to/torrent/tpvgucw

@rarbg Is there anything you can do about it?

**Comment by mabelisle** [comment]
They are definitely categorized using IMDB. If you search a TV Show using the catalog : [https://rarbg.to/catalog/tv/](url) all the results come up with a IMBD tag. Example : [https://rarbg.to/tv/tt1632701/](url)

**Comment by rarbg** [comment]
Unfortunately there is nothing we can do to fix tvdb ids for twin peaks because while its labeled s03 its actually s01 with a new imdb

If you find any other tv shows that dont have tvdb ids they can be fixed tho

**Comment by sharkykh** [comment]
Thanks @rarbg.

> I would actually do the opposite, check imdb and if not available check tvdb.

@mabelisle 
Well, SickRage is based on TVDB and not IMDB.
TVDB being the main indexer, there isn't even an option to use IMDB as an indexer.
And I don't think all the shows have a corresponding IMDB ID in the database.

I'm not change the RARBG provider in SR just because some shows are indexed incorrectly...
Doing even more API calls to RARBG's API just isn't the way to go.

Just enable some more providers, or, sorry to say this, manually search the site and download.

**Comment by rarbg** [comment]
@sharkykh just to add -  we are discussing a fix internally but noone has any ideas so far

**Comment by mabelisle** [comment]
@sharkykh 
I deleted the darn show anyway ahah. I don't know if it's worth a fix if this particular is really rare. Although, an easy way to get around it could be to add a check box in the show options asking if we want this show to search using the IMDB id instead of TVDB. It would just modify the search string and would be easy to implement.

**Comment by 2twisty** [comment]
This RARBG thing is exactly why I have had to install Sonarr.
Sonarr handles RarBG searches just fine.  I now have Sonarr managing my
series, but SickRage searching for subtitles.  I sure wish Sickrage would
just FIX this issue with the IMDB vs TheTVDB search.

Heck, just go look at Sonarr's code.  See how they handle RarBG.

**Comment by OmgImAlexis** [comment]
@2twisty it's not that easy. Sonarr and Sickrage are two completely different projects.

@sharkykh one idea I had was maybe we could add an option to use IMDB id for the show similarly to how we allow overrides for show names. This would just be a checkbox in the settings for the show.

**Comment by TrueOsiris** [comment]
Any progress on this?
Still encountering in latest sickrage docker.
