### ISSUE TITLE
NAS?

### ISSUE THREAD

**Issue by shadowtor** [SickRage/SickRage#3902]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master/v2017.06.05-1
OS: WIN10
What you did: Trying to add mapped network drive as storage location
What happened: doesnt show in list at all
What you expected: to be like couchpotato settings, allowing post-processing to send to NAS
Logs:
```
PASTE LOGS HERE
```

**Comment by sharkykh** [comment]
It won't show in the list, but it does support it.
But you have to run SickRage as your user (not as the SYSTEM user because it doesn't work with network)
