### ISSUE TITLE
Where do deleted files go?

### ISSUE THREAD

**Issue by anujpuri85** [SickRage/SickRage#3910]
When I mark a show for deletion, where do the files go? I had the check boxes checked to send them to trash, but they never went there. The show folder was removed from the hard drive, however the space has not freed up. Where can I go to fully delete the files so that the space clears up?

**Comment by sharkykh** [comment]
I'm guessing your Operating System is Windows, see https://github.com/SickRage/SickRage/issues/3204

**Comment by anujpuri85** [comment]
Yes, Windows 7. I'll be sure to follow that now, but where do I go to delete the files that i've already deleted in SickRage in order to free up space?

**Comment by sharkykh** [comment]
You need to login as the SYSTEM user. Try googling it as I don't have the answer for that ATM.

**Comment by sharkykh** [comment]
@anujpuri85 Or you can try Method 1 from [this Microsoft answer](https://answers.microsoft.com/en-us/windows/forum/windows_7-files/how-do-i-access-the-files-in-crecyclebin/3382e5a3-937a-4a75-868c-80b9529139a7)

**Comment by anujpuri85** [comment]
Wow, thank you! That microsoft link worked (I did methods 1 and 2).
