### ISSUE TITLE
pushBullet

### ISSUE THREAD

**Issue by UNiXMIT** [SickRage/SickRage#3914]
If I enable PushBullet and select NoChannel it will still push to the channel I have set up.

**Comment by sharkykh** [comment]
@UNiXMIT 
Please follow the issue template when creating a new issue. We can't help you without the required information.

**Comment by UNiXMIT** [comment]
The issue is reproducible with the information I provided.

**Comment by sharkykh** [comment]
Nonetheless, the template exists for a good reason, please use it.
For example, debug logs would be helpful in this case.

And..
It's only reproducible if I have a PushBullet account, which I don't.
