### ISSUE TITLE
No download anything

### ISSUE THREAD

**Issue by alamillo98** [SickRage/SickRage#3918]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

OS: Linux
What you did: I search for and episode on newpct in spanish, the problem is the numering is for example, season 14 episode 16 (Navy) is 1416 and the searcher does not found any episode, what can i do? When i triyed to change the absolute it says "Invalid parameter"
What happened: The search failed
What you expected: Found the episode 
http://www.newpct.com/descargar-seriehd/navy/capitulo-1416/hdtv-720p-ac3-5-1/
Logs:
```
PASTE LOGS HERE
```

**Comment by sharkykh** [comment]
The search feature on that site's search engine seems to be really extremely bad.
Even when I try searching for ["NCIS Temporada 1"](http://www.newpct.com/index.php?l=doSearch&q=NCIS%20Temporada%201&category_=All&idioma_=All&bus_de_=All) it brings up completely different shows and other seasons.
Not to mention ["NCIS S01E01"](http://www.newpct.com/index.php?l=doSearch&q=NCIS%20S01E01&category_=All&idioma_=All&bus_de_=All). The actual wanted result is at the bottom of the page.
I don't think there's much we can do about it if you can't even search properly on this site.
Maybe try and contact the site's management and tell them that you can't search the site...
