### ISSUE TITLE
Page can't be displayed

### ISSUE THREAD

**Issue by jiska78** [SickRage/SickRage#3925]
Out of the blue the Sickrage page suddenly can't be displayed and I don't even know where to start. It was working fine two weeks ago and now nothing. Excuse my n00bness, but can someone tell me where to start or what to provide in order to assist. I've obviously tried rebooting the NAS but no good. I'm okay with SSH if someone can provide commands to find where the fault lies?

ReadyNAS 314

**Comment by sharkykh** [comment]
Try getting the logs. I'm not sure abort ReadyNAS, but I think it should be in `/apps/sickrage/app-config/Logs`.

**Comment by jiska78** [comment]
Thanks heaps, that helped me find the problem :)

**Comment by OmgImAlexis** [comment]
You may want to share the answer to the problem here incase anyone finds this later on and has the same issue.

**Comment by jiska78** [comment]
I have no idea why, but the port had changed 7071 to 8181 which was already in use, so a conflict. Edited the port number to put it back to 7071.
