### ISSUE TITLE
Can't search show with multiple names on thetvdb.com

### ISSUE THREAD

**Issue by someoneelsehere** [SickRage/SickRage#3931]
See the listing for https://thetvdb.com/?string=scrotal+recall&tab=listseries&function=Search

Searching either show name in SickRage is unsuccessful.

Reason for the multiple names is the show was cancelled after S01 on Channel 4 (UK), then picked up for S02 on Netflix with a new title.

Branch: master
Commit: 96b53dee713dc35ebf295d0f37a67b2a36fb4ea3
Version: v2017.06.05-1
Database Version: 44.0

**Comment by sharkykh** [comment]
Sorry for the image size, I'm on mobile. I can find it just fine. Please see my comment on #3928 

![](https://user-images.githubusercontent.com/10238474/28252464-3082469e-6a9c-11e7-8fd1-dd5cf5a963f8.jpg)

**Comment by someoneelsehere** [comment]
You're correct! Sorry for the hassle.
