### ISSUE TITLE
ERROR Could not open static file u'/home/mint/Sickrage-master/gui/slick/css/${sickbeard.THEME_NAME}.css'

### ISSUE THREAD

**Issue by PinaColonic** [SickRage/SickRage#3935]
Branch/Commit:  Branch: develop
Commit: b5ae6efbe48c8150b4120b6ba4881024c049d6a3
Version: v2017.06.05-1
Database Version: 44.0
OS: Linux Mint 18.2
What you did: Started Sickrage with latest Development branch update / Restarted SickRage and still see it.   I don't want to be on Dev branch but need qbittorrent fix only available in Development.
What happened: See errors just streaming in logs
What you expected: Not to see a bunch of errors about this css
Logs: Below
```
AA 2017-07-17 12:22:33 ERROR Could not open static file u'/home/mint/Sickrage-master/gui/slick/css/${sickbeard.THEME_NAME}.css'
AA 2017-07-17 12:22:32 ERROR Could not open static file u'/home/mint/Sickrage-master/gui/slick/css/${sickbeard.THEME_NAME}.css'
AA 2017-07-17 12:22:32 ERROR Could not open static file u'/home/mint/Sickrage-master/gui/slick/css/${sickbeard.THEME_NAME}.css'
AA 2017-07-17 12:22:31 ERROR Could not open static file u'/home/mint/Sickrage-master/gui/slick/css/${sickbeard.THEME_NAME}.css'
AA 2017-07-17 12:22:30 ERROR Could not open static file u'/home/mint/Sickrage-master/gui/slick/css/${sickbeard.THEME_NAME}.css'
AA 2017-07-17 12:22:30 ERROR Could not open static file u'/home/mint/Sickrage-master/gui/slick/css/${sickbeard.THEME_NAME}.css'
AA 2017-07-17 12:22:29 ERROR Could not open static file u'/home/mint/Sickrage-master/gui/slick/css/${sickbeard.THEME_NAME}.css'
AA 2017-07-17 12:22:29 ERROR Could not open static file u'/home/mint/Sickrage-master/gui/slick/css/${sickbeard.THEME_NAME}.css'
AA 2017-07-17 12:22:28 ERROR Could not open static file u'/home/mint/Sickrage-master/gui/slick/css/${sickbeard.THEME_NAME}.css'
AA 2017-07-17 12:22:28 ERROR Could not open static file u'/home/mint/Sickrage-master/gui/slick/css/${sickbeard.THEME_NAME}.css'
AA 2017-07-17 12:22:27 ERROR Could not open static file u'/home/mint/Sickrage-master/gui/slick/css/${sickbeard.THEME_NAME}.css'
AA 2017-07-17 12:22:27 ERROR Could not open static file u'/home/mint/Sickrage-master/gui/slick/css/${sickbeard.THEME_NAME}.css'
AA 2017-07-17 12:22:26 ERROR Could not open static file u'/home/mint/Sickrage-master/gui/slick/css/${sickbeard.THEME_NAME}.css'

**Comment by PinaColonic** [comment]
Thanks sharkykh - I appreciate all your efforts on SR development.

**Comment by sharkykh** [comment]
Unrelated quesion,
Did you try to submit the error from SickRage? (I tried to fix it some time ago and I'm not sure if it works)

**Comment by PinaColonic** [comment]
I don't see a way to submit from SickRage.  I do have my github info plugged in settings.   On view log I can see it scroll with this error over and over but there's no button to submit error just a PAUSE.   I am pretty sure I remember seeing a place to submit in the past but now I can't seem to find it.

**Comment by sharkykh** [comment]
@PinaColonic 
It's on the error viewer page (not the log viewer), in the top-right corner.
The link to it should be visible when you have errors, "View Errors" in the tools menu.

**Comment by PinaColonic** [comment]
This particular issue shows up in VIEW LOG only, streaming over and over.  It doesn't appear on the VIEW WARNINGS page and I don't currently have  VIEW ERROR page available under that same tools icon in the upper right, even though this shows up as an ERROR.

**Comment by sharkykh** [comment]
Oh okay, thanks.

**Comment by OmgImAlexis** [comment]
Closed in https://github.com/SickRage/SickRage/pull/3921
