### ISSUE TITLE
[idea] magnetico

### ISSUE THREAD

**Issue by CaptainConsternant** [SickRage/SickRage#3940]
Hi,

Have you seen [magnetico](https://github.com/boramalper/magnetico) ?

I think it is very promising and would like to know if it could be integrated with sickrage ?

Thanks

**Comment by OmgImAlexis** [comment]
We may look into this but for now it's a definite no.

> **magnetico** is still under active construction, and is considered _pre-alpha_ software. Please use **magnetico** suite with care and follow the installation instructions carefully to install it & secure the installation. Feel perfectly free to send bug reports, suggestions, or whatever comes to your mind to send to us through GitHub or personal e-mail.

**Comment by sharkykh** [comment]
For starters, that requires Python 3.5+.
SickRage runs on Python 2.7.10 - 2.7.13, so it's not compatible...

Second, I'm against ever making SickRage a torrent client. It's got enough issues as it is.. lol
But that's just me.

**Comment by BillVeusees** [comment]
OK, i may have expressed myself poorly

My idea was not to integrate or reproduce magnetico inside sickrage, but rather to add magnetico instances as an external search provider for torrents. 

You could add it as a source, and in the settings you give the url, user and password.

**Comment by sharkykh** [comment]
@BillVeusees From what I can gather from a simple search in their repository, you can generate RSS feed(s).
If that's the case, you can use this with the Custom RSS Provider option in SickRage.

While it does [have an API](https://github.com/boramalper/magnetico/blob/master/magneticow/docs/API/v0.md), it's only a draft.
Maybe when they have something more concrete...
