### ISSUE TITLE
Github repo

### ISSUE THREAD

**Issue by brystro** [SickRage/SickRage#3948]
Why not move your repo to gitlab?  Its free and just as good as github

**Comment by OmgImAlexis** [comment]
@miigotu might be able to answer this more for now we're sticking with Github.

**Comment by miigotu** [comment]
GitHub is our home, we will be staying here.  The same exact thing could have happened on GitLab, because it is a law, not their policies.

**Comment by neoatomic** [comment]
And more important, all installers/packages/guides point to this Github address. It will be a nightmare going trough a migration like that. ;o
