### ISSUE TITLE
sickrage.spk 

### ISSUE THREAD

**Issue by xmenxmen** [SickRage/SickRage#3950]
Hi.
Where can i download sickrage.spk to manually install it on a Synology.

**Comment by Achelos** [comment]
https://github.com/SickRage/Sickrage/wiki/Sickrage-installation-packages

Instructions here.

**Comment by beschoenen** [comment]
Is the package in the package center not working?

**Comment by neoatomic** [comment]
You can use the sickbeard-custom method with the synocommunity Repo, or you can use [BenjV's  *.spk.](https://github.com/BenjV/SYNO-packages/raw/master/SickRage%20DSM%206%20noarch%20V1.0.spk)

**Comment by BenjV** [comment]
Don't use the SynoCommunity version.
That package is not yet suited for DSM 6.

I have made a package for DSM 6, see the link posted by neoatomic or take a look at all my packages here:
https://github.com/BenjV/SYNO-packages

**Comment by Achelos** [comment]
as far as i can see there is no package in the package center for SickRage.
Only thing there is is the Sickbeard-custom package.

**Comment by neoatomic** [comment]
Correct, the Synocommunity doesn't have a dedicated Sickrage package, only Sickbeard-custom. But that works currently only with DSM5 as it needs some changes. (However there is a workaround to get it working with DSM6 if that is preferred.)
But quickest (for DSM 5 & 6) is to grab BenjV's Sickrage .Spk (from the link above) and install that from your DSM package center.

I have just updated the Wiki, so users can grab BenjV's Sickrage package from there. :+1:
