### ISSUE TITLE
Skytorrents / submit errors button issues

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [SickRage/SickRage#3955]
Branch/Commit: 832ccb445f8eaadef783eddb51880d67d1a77b3d
OS: macOS 10.12.6
What you did: preformed a manual search of episode, then got skytrorrent error tried to submit error but that failed.
What happened: sky torrents error & submit issue button does seem to work
What you expected: to work and submit my skytorrents error

Logs:
https://gist.github.com/XxUnkn0wnxX/0d6cca97bfde96fa98586afddbfc6cd6

usually when I submit errors it show successful or something in log but this time it gave me error with logger.py, line 325.

as for skytorrents.py line 117, Reddit user: sharkykh said to change to `info_hash = item.guid.rsplit('/', 2)[1] ` - I have tested and it works just fine...

**Comment by sharkykh** [comment]
1. Thanks - that was my bad. #3957 will fix it.
2. I've responded to you [on Reddit](https://www.reddit.com/r/sickrage/comments/6rtbxf/the_repo_is_back/dl8oisq/) - the fix has been pushed to develop in #3946
