### ISSUE TITLE
Won't update - local branch ahead master error

### ISSUE THREAD

**Issue by Braen10** [SickRage/SickRage#3967]
I've got long time now problem with updating sickrage.

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)
I also try to update using command line (_git remote set-url origin https://github.com/SickRage/SickRage.git git fetch origin git checkout master git branch -u origin/master git reset --hard origin/master git pull_), but I've got this error:

```
error: Your local changes to the following files would be overwritten by merge:
        SickBeard.py
        gui/slick/css/lib/jquery-ui-1.10.4.custom.min.css
        lib/chardet/cli/chardetect.py
        lib/github/StatsCodeFrequency.py
        lib/github/StatsCommitActivity.py
        lib/github/StatsContributor.py
        lib/github/StatsParticipation.py
        lib/github/StatsPunchCard.py
        lib/imdb/locale/generatepot.py
        lib/imdb/locale/rebuildmo.py
        lib/mako/cmd.py
        lib/ndg/httpsclient/test/scripts/openssl_https_server.sh
        lib/pysrt/commands.py
        lib/requests/packages/chardet/chardetect.py
        lib/subliminal/score.py
        runscripts/init.debian
        runscripts/init.fedora
        runscripts/init.freebsd
        runscripts/init.gentoo
        runscripts/init.solaris11
        runscripts/init.systemd
        runscripts/init.ubuntu
        runscripts/init.upstart
Please, commit your changes or stash them before you can merge.
Aborting
```

Branch/Commit: master/34d0987400b3d50f550f55472d417c4e5b263f55
OS: Windows 8.1
Logs:
```
CHECKVERSION :: Local branch is ahead of master. Automatic update not possible.
```

**Comment by pigsyn** [comment]
Could you add your current repo `git status` ? Your commit is very very old.

**Comment by Braen10** [comment]
There it is @pigsyn 
`c:\SickRage>git status
On branch master
Your branch and 'upstream/master' have diverged,
and have 2863 and 1139 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   SickBeard.py
        modified:   gui/slick/css/lib/jquery-ui-1.10.4.custom.min.css
        modified:   lib/chardet/cli/chardetect.py
        modified:   lib/github/StatsCodeFrequency.py
        modified:   lib/github/StatsCommitActivity.py
        modified:   lib/github/StatsContributor.py
        modified:   lib/github/StatsParticipation.py
        modified:   lib/github/StatsPunchCard.py
        modified:   lib/imdb/locale/generatepot.py
        modified:   lib/imdb/locale/rebuildmo.py
        modified:   lib/mako/cmd.py
        modified:   lib/ndg/httpsclient/test/scripts/openssl_https_server.sh
        modified:   lib/pysrt/commands.py
        modified:   lib/requests/packages/chardet/chardetect.py
        modified:   lib/subliminal/score.py
        modified:   runscripts/init.debian
        modified:   runscripts/init.fedora
        modified:   runscripts/init.freebsd
        modified:   runscripts/init.gentoo
        modified:   runscripts/init.solaris11
        modified:   runscripts/init.systemd
        modified:   runscripts/init.ubuntu
        modified:   runscripts/init.upstart

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        .appveyor.yml
        .codecov.yml
        .snyk
        cache-20160422_202145/
        cache-20160423_112246/
        gui/slick/css/font-awesome.min.css
        gui/slick/fonts/FontAwesome.otf
        gui/slick/fonts/fontawesome-webfont.eot
        gui/slick/fonts/fontawesome-webfont.svg
        gui/slick/fonts/fontawesome-webfont.ttf
        gui/slick/fonts/fontawesome-webfont.woff
        gui/slick/fonts/fontawesome-webfont.woff2
        gui/slick/images/32px_discord_notifier.png
        gui/slick/images/Slack_Mark_Web.png
        gui/slick/images/network/channel 5 (uk).png
        gui/slick/images/network/chiller.png
        gui/slick/images/network/club illico.png
        gui/slick/images/network/doordarshan national.png
        gui/slick/images/network/dr3.png
        gui/slick/images/network/gsn.png
        gui/slick/images/network/hot.png
        gui/slick/images/network/italia 1.png
        gui/slick/images/network/kanal 5 (dk).png
        gui/slick/images/network/kbs.png
        gui/slick/images/network/la7.png
        gui/slick/images/network/ntv (jp).png
        gui/slick/images/network/rai 1.png
        gui/slick/images/network/rai 2.png
        gui/slick/images/network/rai 3.png
        gui/slick/images/network/rai 4.png
        gui/slick/images/network/rai gulp.png
        gui/slick/images/network/rete 4.png
        gui/slick/images/network/sbs (kr).png
        gui/slick/images/network/seeso.png
        gui/slick/images/network/stod 2.png
        gui/slick/images/network/tnt (us).png
        gui/slick/images/network/tv 2 zulu.png
        gui/slick/images/network/tv 3.png
        gui/slick/images/network/twit.png
        gui/slick/images/network/yes.png
        gui/slick/images/providers/archetorrent.png
        gui/slick/images/providers/filelist.png
        gui/slick/images/providers/hdtorrents_it.png
        gui/slick/images/providers/horriblesubs.png
        gui/slick/images/providers/ilcorsaronero.png
        gui/slick/images/providers/immortalseed.png
        gui/slick/images/providers/ncore_cc.png
        gui/slick/images/providers/skytorrents.png
        gui/slick/images/providers/torrent9.png
        gui/slick/images/trakt-placeholder.png
        gui/slick/views/config_shares.mako
        gui/slick/views/inc_home_menu.mako
        gui/slick/views/inc_home_showList.mako
        lib/backports_abc.py
        lib/cfscrape/
        lib/guessit/test/test_api_unicode_literals.py
        lib/js2py/
        lib/pgi/
        lib/putiopy.py
        lib/rarfile/test/
        lib/singledispatch.py
        lib/singledispatch_helpers.py
        lib/tornado/_locale_data.py
        lib/tornado/test/http1connection_test.py
        lib/tornado/test/static/sample.xml
        lib/tornado/test/static/sample.xml.bz2
        lib/tornado/test/static/sample.xml.gz
        lib/tornado/test/windows_test.py
        lib/tus.py
        lib/twilio/
        lib/tzlocal/
        locale/af_ZA/LC_MESSAGES/messages.json
        locale/ar_SA/LC_MESSAGES/messages.json
        locale/bg_BG/LC_MESSAGES/messages.json
        locale/ca_ES/LC_MESSAGES/messages.json
        locale/cs_CZ/LC_MESSAGES/messages.json
        locale/da_DK/LC_MESSAGES/messages.json
        locale/de_DE/LC_MESSAGES/messages.json
        locale/el_GR/LC_MESSAGES/messages.json
        locale/en_GB/LC_MESSAGES/messages.json
        locale/en_US/LC_MESSAGES/messages.json
        locale/es_ES/LC_MESSAGES/messages.json
        locale/et_EE/LC_MESSAGES/messages.json
        locale/fa_IR/LC_MESSAGES/messages.json
        locale/fi_FI/LC_MESSAGES/messages.json
        locale/fr_FR/LC_MESSAGES/messages.json
        locale/he_IL/LC_MESSAGES/messages.json
        locale/hr_HR/LC_MESSAGES/messages.json
        locale/hu_HU/LC_MESSAGES/messages.json
        locale/is_IS/LC_MESSAGES/messages.json
        locale/it_IT/LC_MESSAGES/messages.json
        locale/ja_JP/LC_MESSAGES/messages.json
        locale/ko_KR/LC_MESSAGES/messages.json
        locale/lv_LV/LC_MESSAGES/messages.json
        locale/nl_NL/LC_MESSAGES/messages.json
        locale/no_NO/LC_MESSAGES/messages.json
        locale/pl_PL/LC_MESSAGES/messages.json
        locale/pt_BR/LC_MESSAGES/messages.json
        locale/pt_PT/LC_MESSAGES/messages.json
        locale/ro_RO/LC_MESSAGES/messages.json
        locale/ru_RU/LC_MESSAGES/messages.json
        locale/sk_SK/LC_MESSAGES/messages.json
        locale/sl_SI/LC_MESSAGES/messages.json
        locale/sv_SE/LC_MESSAGES/messages.json
        locale/tr_TR/LC_MESSAGES/messages.json
        locale/uk_UA/LC_MESSAGES/messages.json
        locale/vi_VN/LC_MESSAGES/messages.json
        locale/zh_CN/LC_MESSAGES/messages.json
        locale/zh_TW/LC_MESSAGES/messages.json
        patches/
        sickbeard/notifiers/discord.py
        sickbeard/notifiers/slack.py
        sickbeard/notifiers/twilio_notify.py
        sickbeard/post_processing_queue.py
        sickbeard/providers/archetorrent.py
        sickbeard/providers/filelist.py
        sickbeard/providers/hdtorrents_it.py
        sickbeard/providers/horriblesubs.py
        sickbeard/providers/ilcorsaronero.py
        sickbeard/providers/immortalseed.py
        sickbeard/providers/ncore.py
        sickbeard/providers/skytorrents.py
        sickbeard/providers/torrent9.py
        sickrage/helper/argument_parser.py
        tests/browser_tests.py
        tests/filter_bad_releases_tests.py
        tests/mocha/
        tests/post_processor_queue_tests.py
        tests/sickrage_tests/providers/torrent/cassettes/horriblesubs.yaml
        tests/sickrage_tests/providers/torrent/cassettes/skytorrents.yaml
        tests/sickrage_tests/providers/torrent/cassettes/torrent9.yaml
        unrar/
        yarn.lock

no changes added to commit (use "git add" and/or "git commit -a")`

**Comment by pigsyn** [comment]
Can you add `git remote -v` ? Look like you tried this from the faq _https://github.com/SickRage/SickRage/wiki/FAQ%27s-and-Fixes#i-have-problems-updating-or-my-installation-got-corrupt-what-now_ and some reset HEAD at some point.

**Comment by pigsyn** [comment]
Anyways, if you have multiple remotes like this:
```
origin	https://github.com/SickRage/SickRage.git (fetch)
origin	https://github.com/SickRage/SickRage.git (push)
upstream 	https://github.com/SickRage/SickRage.git (fetch)
upstream 	https://github.com/SickRage/SickRage.git (push)
```
and want to clean up this modification mess, I would do this:

1. Stop Sickrage & backup C:\SickRage (if possible)
2. `git remote rm upstream`
3. `git checkout -f`
4 . `git clean -fd`
4. redo commands from your first message

Your repo should be updated and clean a this point.

Start sickrage and I strongly recommend that you run a show mass update (Under manage mass update select update and submit)

**Comment by beschoenen** [comment]
@Braen10 Solved? please close if so.

**Comment by Braen10** [comment]
Still same error:

`c:\SickRage>git remote rm upstream

c:\SickRage>git checkout -f

c:\SickRage>git clean -fd
Removing .appveyor.yml
Removing .codecov.yml
Removing .snyk
Removing cache-20160422_202145/
Removing cache-20160423_112246/
Removing cache-20170404_184605/
Removing gui/slick/css/font-awesome.min.css
Removing gui/slick/fonts/FontAwesome.otf
Removing gui/slick/fonts/fontawesome-webfont.eot
Removing gui/slick/fonts/fontawesome-webfont.svg
Removing gui/slick/fonts/fontawesome-webfont.ttf
Removing gui/slick/fonts/fontawesome-webfont.woff
Removing gui/slick/fonts/fontawesome-webfont.woff2
Removing gui/slick/images/32px_discord_notifier.png
Removing gui/slick/images/Slack_Mark_Web.png
Removing gui/slick/images/network/channel 5 (uk).png
Removing gui/slick/images/network/chiller.png
Removing gui/slick/images/network/club illico.png
Removing gui/slick/images/network/doordarshan national.png
Removing gui/slick/images/network/dr3.png
Removing gui/slick/images/network/gsn.png
Removing gui/slick/images/network/hot.png
Removing gui/slick/images/network/italia 1.png
Removing gui/slick/images/network/kanal 5 (dk).png
Removing gui/slick/images/network/kbs.png
Removing gui/slick/images/network/la7.png
Removing gui/slick/images/network/ntv (jp).png
Removing gui/slick/images/network/rai 1.png
Removing gui/slick/images/network/rai 2.png
Removing gui/slick/images/network/rai 3.png
Removing gui/slick/images/network/rai 4.png
Removing gui/slick/images/network/rai gulp.png
Removing gui/slick/images/network/rete 4.png
Removing gui/slick/images/network/sbs (kr).png
Removing gui/slick/images/network/seeso.png
Removing gui/slick/images/network/stod 2.png
Removing gui/slick/images/network/tnt (us).png
Removing gui/slick/images/network/tv 2 zulu.png
Removing gui/slick/images/network/tv 3.png
Removing gui/slick/images/network/twit.png
Removing gui/slick/images/network/yes.png
Removing gui/slick/images/providers/archetorrent.png
Removing gui/slick/images/providers/filelist.png
Removing gui/slick/images/providers/hdtorrents_it.png
Removing gui/slick/images/providers/horriblesubs.png
Removing gui/slick/images/providers/ilcorsaronero.png
Removing gui/slick/images/providers/immortalseed.png
Removing gui/slick/images/providers/ncore_cc.png
Removing gui/slick/images/providers/skytorrents.png
Removing gui/slick/images/providers/torrent9.png
Removing gui/slick/images/trakt-placeholder.png
Removing gui/slick/views/config_shares.mako
Removing gui/slick/views/inc_home_menu.mako
Removing gui/slick/views/inc_home_showList.mako
Removing lib/backports_abc.py
Removing lib/cfscrape/
Removing lib/guessit/test/test_api_unicode_literals.py
Removing lib/js2py/
Removing lib/pgi/
Removing lib/putiopy.py
Removing lib/rarfile/test/
Removing lib/singledispatch.py
Removing lib/singledispatch_helpers.py
Removing lib/tornado/_locale_data.py
Removing lib/tornado/test/http1connection_test.py
Removing lib/tornado/test/static/sample.xml
Removing lib/tornado/test/static/sample.xml.bz2
Removing lib/tornado/test/static/sample.xml.gz
Removing lib/tornado/test/windows_test.py
Removing lib/tus.py
Removing lib/twilio/
Removing lib/tzlocal/
Removing locale/af_ZA/LC_MESSAGES/messages.json
Removing locale/ar_SA/LC_MESSAGES/messages.json
Removing locale/bg_BG/LC_MESSAGES/messages.json
Removing locale/ca_ES/LC_MESSAGES/messages.json
Removing locale/cs_CZ/LC_MESSAGES/messages.json
Removing locale/da_DK/LC_MESSAGES/messages.json
Removing locale/de_DE/LC_MESSAGES/messages.json
Removing locale/el_GR/LC_MESSAGES/messages.json
Removing locale/en_GB/LC_MESSAGES/messages.json
Removing locale/en_US/LC_MESSAGES/messages.json
Removing locale/es_ES/LC_MESSAGES/messages.json
Removing locale/et_EE/LC_MESSAGES/messages.json
Removing locale/fa_IR/LC_MESSAGES/messages.json
Removing locale/fi_FI/LC_MESSAGES/messages.json
Removing locale/fr_FR/LC_MESSAGES/messages.json
Removing locale/he_IL/LC_MESSAGES/messages.json
Removing locale/hr_HR/LC_MESSAGES/messages.json
Removing locale/hu_HU/LC_MESSAGES/messages.json
Removing locale/is_IS/LC_MESSAGES/messages.json
Removing locale/it_IT/LC_MESSAGES/messages.json
Removing locale/ja_JP/LC_MESSAGES/messages.json
Removing locale/ko_KR/LC_MESSAGES/messages.json
Removing locale/lv_LV/LC_MESSAGES/messages.json
Removing locale/nl_NL/LC_MESSAGES/messages.json
Removing locale/no_NO/LC_MESSAGES/messages.json
Removing locale/pl_PL/LC_MESSAGES/messages.json
Removing locale/pt_BR/LC_MESSAGES/messages.json
Removing locale/pt_PT/LC_MESSAGES/messages.json
Removing locale/ro_RO/LC_MESSAGES/messages.json
Removing locale/ru_RU/LC_MESSAGES/messages.json
Removing locale/sk_SK/LC_MESSAGES/messages.json
Removing locale/sl_SI/LC_MESSAGES/messages.json
Removing locale/sv_SE/LC_MESSAGES/messages.json
Removing locale/tr_TR/LC_MESSAGES/messages.json
Removing locale/uk_UA/LC_MESSAGES/messages.json
Removing locale/vi_VN/LC_MESSAGES/messages.json
Removing locale/zh_CN/LC_MESSAGES/messages.json
Removing locale/zh_TW/LC_MESSAGES/messages.json
Removing patches/
Removing sickbeard/notifiers/discord.py
Removing sickbeard/notifiers/slack.py
Removing sickbeard/notifiers/twilio_notify.py
Removing sickbeard/post_processing_queue.py
Removing sickbeard/providers/archetorrent.py
Removing sickbeard/providers/filelist.py
Removing sickbeard/providers/hdtorrents_it.py
Removing sickbeard/providers/horriblesubs.py
Removing sickbeard/providers/ilcorsaronero.py
Removing sickbeard/providers/immortalseed.py
Removing sickbeard/providers/ncore.py
Removing sickbeard/providers/skytorrents.py
Removing sickbeard/providers/torrent9.py
Removing sickrage/core/
Removing sickrage/helper/argument_parser.py
Removing tests/browser_tests.py
Removing tests/filter_bad_releases_tests.py
Removing tests/mocha/
Removing tests/post_processor_queue_tests.py
Removing tests/sickrage_tests/providers/torrent/cassettes/horriblesubs.yaml
Removing tests/sickrage_tests/providers/torrent/cassettes/skytorrents.yaml
Removing tests/sickrage_tests/providers/torrent/cassettes/torrent9.yaml
Removing unrar/
Removing yarn.lock

c:\SickRage>git remote set-url origin https://github.com/SickRage/SickRage.git

c:\SickRage>git fetch origin
From https://github.com/SickRage/SickRage
 * branch            HEAD       -> FETCH_HEAD

c:\SickRage>git checkout master
M       SickBeard.py
M       gui/slick/css/lib/jquery-ui-1.10.4.custom.min.css
M       lib/chardet/cli/chardetect.py
M       lib/github/StatsCodeFrequency.py
M       lib/github/StatsCommitActivity.py
M       lib/github/StatsContributor.py
M       lib/github/StatsParticipation.py
M       lib/github/StatsPunchCard.py
M       lib/imdb/locale/generatepot.py
M       lib/imdb/locale/rebuildmo.py
M       lib/mako/cmd.py
M       lib/ndg/httpsclient/test/scripts/openssl_https_server.sh
M       lib/pysrt/commands.py
M       lib/requests/packages/chardet/chardetect.py
M       lib/subliminal/score.py
M       runscripts/init.debian
M       runscripts/init.fedora
M       runscripts/init.freebsd
M       runscripts/init.gentoo
M       runscripts/init.solaris11
M       runscripts/init.systemd
M       runscripts/init.ubuntu
M       runscripts/init.upstart
Already on 'master'

c:\SickRage>git branch -u origin/master
fatal: Cannot setup tracking information; starting point 'origin/master' is not
a branch.

c:\SickRage>git reset --hard origin/master
HEAD is now at 34d0987 DB version bump, force it to 44,0 without prejudice`

**Comment by beschoenen** [comment]
You could try settings up SickRage a new. Make a backup of `config.ini`, `sickbeard.db` and `cache.db`, clone into another folder, and copy over the 3 files.

**Comment by beschoenen** [comment]
When in C:/ try:

```
git clone https://github.com/SickRage/SickRage.git sickrage-new
```

**Comment by Braen10** [comment]
And what should i do before git clone...? Just stop SickRage or delete all files i C:\SickRage?

**Comment by beschoenen** [comment]
- Stop current SickRage, but keep the files.
- Clone SickRage from GitHub into a new folder (now you'll have 2 folders).
- Copy over the 3 files I mentioned.
- And start SickRage from the new folder.
- If everything's OK you can delete the old folder and maybe rename the new folder back to `sickrage`.

**Comment by Braen10** [comment]
Worked, I'm now on:

c:\sickrage-new>git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean

Thank you, closing now.
