### ISSUE TITLE
Help with version 

### ISSUE THREAD

**Issue by smorison** [SickRage/SickRage#3969]
Hi guys,
Not great with git really...
I'm on the following and can't work out what the current version should be.

OS: OSX
Branch: master
Commit: 832ccb445f8eaadef783eddb51880d67d1a77b3d
Version: v2017.06.05-1

I've restarted everythign and checked for updates and it says i'm on the latest... just needing a newbie confirmation here please.

Thanks heaps

**Comment by OmgImAlexis** [comment]
Yep you're on the latest.
