### ISSUE TITLE
[Feature Request] Re-Add KickassTorrents as a Torrent Provider

### ISSUE THREAD

**Issue by phantomrtw** [SickRage/SickRage#3986]
KickassTorrents has returned and is a valuable source for torrent requests. Is there any way that we could get their new domain, http://kickasstorrents.to/, added as a Provider?

**Comment by OmgImAlexis** [comment]
That's not the real kickasstorrents, katcr.co is the closest to the real thing.

**Comment by phantomrtw** [comment]
have you been to http://kickasstorrents.to/community/? There are tens of thousands of posts there, with a very high torrent and seeder count. If it isn't the legit KAT, then it still appears to be a very good source. 

Also, upon visiting katcr.co, I got 3 popup windows, and an EXE that tried to download itself.

**Comment by OmgImAlexis** [comment]
Check the last post date. It's a clone just before KAT was taken down.

If you're not using [ublock origin](https://github.com/gorhill/uBlock) that's to be expected on 99% of torrent sites.


Closing this as we decided internally that we don't want to add any more KAT clones.
