### ISSUE TITLE
Feature Request: Add support for Torznab

### ISSUE THREAD

**Issue by PoshSparks** [SickRage/SickRage#3998]
Feature request:

   Add direct support for torznab under "Configure Custom Torrent Provider" ... 
   from a form standpoint: add checkbox or dropdown to select torznab or RSS url... and a field for the API key... 
   This would open up a larger pool of both public and private trackers/indexers... and this would take demands off of the sickrage team to constantly add new trackers/indexers by allowing the jackett and Cardigann teams to maintain the indexers.

**Comment by PoshSparks** [comment]
+1 ...  I definitely think SickRage would benefit from torznab support...

**Comment by miigotu** [comment]
Torznab providers are already supported, you add it as a custom __newznab__ provider, because it uses the neznab api.
