### ISSUE TITLE
Add t411.si as provider

### ISSUE THREAD

**Issue by jgrossrieder** [SickRage/SickRage#4021]
The team that has done t411 is back in business, with a new domain. For what I found, it has a lot of content and is working very nice since severals weeks!

Should we add this provider back to sickrage?

The domain is https://t411.si/

**Comment by lejudoka13** [comment]
yeah they seems to do a good job, but yggtorrent is good too, sickrage should get yggtorrent and t411.si povider's

**Comment by Sylanorr** [comment]
I took some torrents from t411.si since a few week and it's working fine. I think you should add it !

**Comment by lejudoka13** [comment]
yeah it is working very well  @Sylanorr

**Comment by adaur** [comment]
t411.si is a scam

**Comment by Sylanorr** [comment]
No but it works... that's the point isn't it ?

**Comment by jgrossrieder** [comment]
WTF? Why do you close this?  As of today, it's the most complete torrent website I found on french scene. Currently I've severals shows that are available here but nowhere in the currents torrents provider.

**Comment by lejudoka13** [comment]
a site scammer is a site that decide to steal money from users but t411.si doen't do that they just bring a new version of t411. That's different but the torrent site is very diversify so why not ?

**Comment by jgrossrieder** [comment]
100% agree, and they are putting a lot of effort in adding functionalities and providing quality torrents.

**Comment by Sylanorr** [comment]
Please Reopen this Issue ...

**Comment by lejudoka13** [comment]
the new interface is better than the oldest t411 team and they decide to stop Pubs farming so why not @adaur ?

**Comment by jgrossrieder** [comment]
And they stopped their promotion of using seedbox to be able to maintain a 1:1 ratio.

**Comment by adaur** [comment]
I'll reopen if you want, but a website claiming to be the successor of T411 taking his name and copying its design whereas it's not affiliated to it in any way looks very much like scam to me.

Use yggtorrent if you have to use a public tk.

More info: https://www.wareziens.net/forum/topic-36562-t411si-page-1.html

**Comment by jgrossrieder** [comment]
I got multiples tv shows that were not available on yggtorrents but on T411.si. Also to mention that I find the description of the T411 torrents more detailed.

Why not add them both then? Should be to the end user to decide which one to use if at the end they both propose good content.

**Comment by adaur** [comment]
https://www.wareziens.net/forum/topic-36562-t411si-page-2.html#p413462

The only thing this website does is reference public torrents available elsewhere like torrent9 (already added into SickRage)

**Comment by lejudoka13** [comment]
@adaur where are you in the ideas to add yggtorrent cause i just test ur branch and nothing is working

**Comment by adaur** [comment]
It was working when I opened my PR, but I left it since it didn't got merged for no reason. I'll check it again soon

**Comment by lejudoka13** [comment]
@adaur ok it say "Unable to connect to provider " maybe they changed something

**Comment by lejudoka13** [comment]
actually there are 3 provider where we can find good torrent and last french /vostfr torrent
There provider are **torrent9** but torrent9 got maybe 4 on 10 torrent searching and the rest are **t411.si** and **yggtorrent** so dev can you just develop this two provider ? 

French 
@adaur je sais que tu es français, tu as très ben remarqué que torrent9 n'avais casiment rien en séries et que le reste des séries étaient sur yggtorrent, peut-être que t411.si ne te plait pas mais ils font un super travail pour l'instant. Ce serait cool si tu pouvais faire l'un des deux .

**Comment by jgrossrieder** [comment]
I've done my best to implement this in the #4050. Please let me know if there is something wrong in what I did.

**Comment by jgrossrieder** [comment]
@miigotu Any idea when this will be merged and pushed to master? I've a lot of tv-shows that are not found except on yggtorrent and t411.si, both are waiting to be merged and pushed to master.
