### ISSUE TITLE
[question] nyaa trusted setting

### ISSUE THREAD

**Issue by Zabanya** [SickRage/SickRage#4083]
my search always return result with ?f=2 which make filter to trusted only, is there a way to make it non trusted?, since i could not find it in provider setting nor show setting

**Comment by ahmadhadidi** [comment]
I found the culprit,[this class here](https://github.com/SickRage/SickRage/blob/72f937b3667166801ff595ea674a7877dd8b67cd/sickbeard/providers/nyaa.py
) at line 65 seems to be what's causing your issue.

Can you untick the option located at: Search Providers -> Provider Options -> *Select Nyaa in the Configure Provider field* -> uncheck "Confirmed download: only download torrents from trusted or verified uploaders?" then save, and then search again, see if it works?

**Comment by Zabanya** [comment]
thanks!
