### ISSUE TITLE
[TorrentProject] New URL

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [SickRage/SickRage#4102]
TorrentProject Provider url needs to be changed from https://torrentproject.se TO https://torrentproject2.se/ [Non-Verified URL]

also as a sidetone I also received this notice:

`GET URL: https://torrentproject2.se/?filter=2101&s=The+Gifted+S01E03&showmagnets=on&num=50&out=json [Status: 200]
2017-10-23 04:30:19 `
`[TorrentProject] :: Requested a json response but response was not json, check the url: https://torrentproject2.se`

maybe api may need to be reworked a little.

**Comment by OmgImAlexis** [comment]
From what I can see `torrentproject.se` is just down at the moment do you have a link to verify they've changed domains?

**Comment by XxUnkn0wnxX** [comment]
unsure, I found it here on this  [Reddit](https://www.reddit.com/r/TPB/comments/713hfl/torrent_project_have_new_domains/) Post, but doesnt seem to be a reliable source though, and offical TorrentProject Url has been down for over a month.

**Comment by OmgImAlexis** [comment]
Well from the Reddit post it seems very unlikely we'll be using that URL then.
