### ISSUE TITLE
Did Sickrage Development come to a stall?

### ISSUE THREAD

**Issue by abetancort** [SickRage/SickRage#4103]
Appears that **SickRage** in last few months has evolved a  into a **_Walking Dead_** App...  IMHO, I believe that the best thing that could happen for the App and the community at this point is for the current **SickRage** development team to become aware that’s time to let go and for the current  repo-admin to take a step back into the background and silently pass the baton to a new team leader as soon as **there’s one willing to grab it**.  

Because sooner than later, and surely before anyone would expect the **App** will go from a **_Walking Dead_**  to be **Actually and Effectively Dead** as it turns to obsolete and unusable. Becoming what  most people call **abandonware**. 

I truly think, it would be pity after the huge amount of efforts in time, sweet, nights coding and battles fought to get to this development stage of the so called “**_Official_**”  **SickRage fork**.

**Comment by OmgImAlexis** [comment]
Dupe https://github.com/SickRage/SickRage/issues/4095 https://github.com/SickRage/SickRage/issues/4100
