### ISSUE TITLE
Reset TV Show database

### ISSUE THREAD

**Issue by rmilyard** [SickRage/SickRage#4107]
Today I noticed on Sickrage running on my FreeNAS server is missing shows. They seem to be in database since when I try to re add them it shows them there. However they aren't downloading etc. Is there a way to basically clean up this and then maybe try to re add them?

SickRage Info:
Branch: master 
Commit: d8c2613583ce8b321a5adc9ff70c52e830f224a8 
Database Version: 44.0

Python Version:
2.7.9 (default, Sep 9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]

SSL Version:
OpenSSL 1.0.2d 9 Jul 2015

OS:
FreeBSD-11.0-RELEASE-amd64-64bit-ELF

Locale:
en_US.UTF-8

A mako error has occured.
If this happened during an update a simple page refresh may be the solution.
Mako errors that happen during updates may be a one time error if there were significant ui changes.

Show/Hide Error
File /usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/show_queue.py:279, in show_name: return self.show.name if self.show else self.showDir.rsplit(os.sep)[-1] AttributeError: 'NoneType' object has no attribute 'rsplit'

**Comment by rmilyard** [comment]
One show I found issue today with was adding Tom Clancy's Jack Ryan

**Comment by miigotu** [comment]
#4224
