### ISSUE TITLE
SickRage won't start (something corrupt after power outage ?)

### ISSUE THREAD

**Issue by Adelscott** [SickRage/SickRage#4159]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Master I guess. Package is version 99999999 from BenjV to avoid Echel0n's crap
OS: Synology DSM 6.1.4
What you did: nothing, last snatch on 24/11/2017 02h11.
What happened: power outage, restarted on 24/11/2017 16h10, since then no snatch. I see no SickRage update on  Synology event notifications
What you expected: Package to start, but it's stopped. And I get an error "Failed to run the package service"
Logs:

If someone could tell me how to check logs to see what's the error when starting ? 
Or to start it manually ?
I tried to launch "start" on admin@DiskStation:/var/packages/sickrage/scripts$ path but I get this : 
start: Rejected send message, 1 matched rules; type="method_call", sender=":1.25" (uid=1024 pid=5252 comm="start ") interface="com.ubuntu.Upstart0_6.Instance" member="Start" error name="(unset)" requested_reply="0" destination="com.ubuntu.Upstart" (uid=0 pid=1 comm="/sbin/init ")
If I could find the problem instead of reinstalling. Last time I lost all my transmission seeds when uninstalling Echel0n's version to install BenjV's ...

Thanks

**Comment by Adelscott** [comment]
Found log in /var/packages/sickrage/target/var/Logs/sickrage.log

But it's weird, most recent entry is
2017-09-13 01:25:04 INFO     EVENT-QUEUE :: Restarting SickRage with ['/var/packages/sickrage/target/env/bin/python', u'/var/packages/sickrage/target/var/SickBeard.py', '--daemon', '--pidfile', '/var/packages/sickrage/target/var/sickrage.pid', '--config', '/var/packages/sickrage/target/var/config.ini', '--datadir', '/var/packages/sickrage/target/var/', u'--nolaunch']

It's when I installed BenjV's version. So either the package can not write to this file or it is written to another file. Permissions are : -rw-r--r--  1 sc-sickrage sickrage 2848 Sep 13 01:25 sickrage.log
When I try "chmod -R 777 sickrage.log" I got "chmod: changing permissions of  Ç sickrage.log Ç : Operation not permitted"

**Comment by OmgImAlexis** [comment]
Switch between versions isn't supported or even slightly recommended.

If you want to use a different fork of Sickbeard, Sickrage, etc. then you should be doing a completely new install.

**Comment by Adelscott** [comment]
Why is this closed ? Are you sure you've read what I wrote ?

On 2017-09-13 I did a new install with package from BenjV. Everything was working since an unexpected shutdown. 

Please open your eyes before sniping.

**Comment by Adelscott** [comment]
If anyone with eyes can re open it, thanks

**Comment by BenjV** [comment]
I do not see anything wrong with that line in te logfile.
It is completely correct.

Probably a curcial file of the package is corrupted during the power outage.
I suggest you save the database en the config files remove the package completely, do a reboot and install the package new.
Do an update from within Sickrage.
Stop the package
restore the database and config files
start Sickrage again.

You can find the package here:
https://github.com/BenjV/SYNO-packages/raw/master/SickRage%20DSM%206%20noarch%20V1.0.spk

The database and config files are to be found here:
/var/packages/sickrage/target/var/sickrage/sickbeard.db
/var/packages/sickrage/target/var/sickrage/config.ini

PS I could also be that some python files became corrupted so maybe removing and reinstalling python could be neccesarry but that is less likely.

**Comment by Adelscott** [comment]
@BenjV thanks for you support.

What surprised me in this log is the date. I thought it should be the package log, every time I start it, something new should be added to this log. I'm pretty sure my NAS rebooted several times since this date ... Is this just an installation log ?

So I'll try to reinstall it, hoping I don't lose everything like last time when struggling to get rid of Echel0n's version, now that group sc-media is set.

**Comment by Adelscott** [comment]
Thks @BenjV , I followed your instructions and it seems to work

 2 things (if anyone has same problem and read this thread) : 
Path for sickbeard.db and config.ini is /var/packages/sickrage/target/var/ not /var/packages/sickrage/target/var/sickrage/
When I saved the files with cp command permissions changed (tried with -p option to preserve them but didn't work) . Owner became admin not sc-sickrage anymore. I don't know how to change them back to this account (chown not working with admin account :( ) so I chmod -R 777 on them. Had to do this, otherwise Package wouldn't start.

Thanks again !

**Comment by BenjV** [comment]
try to add sudo in from to get root privs for the command.
admin is not enough privs

So like this.

sudo chown sc-sickrage /var/packages/sickrage/target/var/sickbeard.db
sudo chown sc-sickrage /var/packages/sickrage/target/var/config,ini

**Comment by Adelscott** [comment]
Thanks, 
In fact my problem was I couldn't sudo using telnet.exe. Worked with putty ssh and command "sudo -i"
Permissions are back to sc-sickrage:sickrage (like all the files in same path)

**Comment by Adelscott** [comment]
Once again I got a power outage, and once again SickRage was the only program not working after reboot. Luckily I restored everything with same procedure. How comes it only happens to SickRage ?

**Comment by BenjV** [comment]
Just bad luck, I think and the fact that SickRage is doing a lot of updates to files.
You could make the various intervals SickRage does things bigger.
For example the postprocessore run standard every 10 minutes, I have set mine to run every 4 hours because I don't need it to run that often.

The often SickRage does something the bigger the change it get corrupted during power outage.

The real solution is getting a small UPS to fix this.
When the power outage is too long, the UPS does a gracefull shutdown of my Synology Nas.

**Comment by Adelscott** [comment]
Thanks, I changed it to 60 minutes. Too bad that SickRage does not look in Transmission if the download is finished to start processing

**Comment by BenjV** [comment]
It does look in Transmission, (now every 60 minutes) and then updates its own internal files.
There are more time settings in SickRage that could be set larger, just take a look at the log screen to see when it does something and which timer you could adjust.
