### ISSUE TITLE
Title doesn't contain any of X, ignoring it

### ISSUE THREAD

**Issue by utdrmac** [SickRage/SickRage#4177]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: d8c2613
OS: Debian
What you did: Search for episode
What happened: Search failed to match filename string
What you expected: Expect it to match

Not much to say here. I set the require word of 'WEB' in the show's settings. Saw this in the logs. Doesn't make sense. You can clearly see the letters W E B contained in 'WEBRip' so why did it not match? Is this not regex matching? or even simple "*match*" ? ("*WEB*")

Release: Brooklyn.Nine-Nine.S01E03.WEBRip.x264-RARBG doesn't contain any of WEB, ignoring it

**Comment by BenjV** [comment]
It is word matching and in this case the word is WEBRIP and not WEB.
If you want also WEBRIP just add that word too.
