### ISSUE TITLE
No newznab_string passed to saveProviders

### ISSUE THREAD

**Issue by atah** [SickRage/SickRage#4201]
I would like use Yggtorrent provider but I have two errors : 

Thread-14 :: [594f47e] No newznab_string passed to saveProviders

[YggTorrent] :: Invalid username or password. Check your settings

but my password is correct 

Can you help me please ?

**Comment by fantasio31** [comment]
Same issue for me, for all personnalized provider using RSS feed.
Sickrage is not able to manage these feeds anymore.

**Comment by miigotu** [comment]
The `No newznab_string passed to saveProviders` is a new error message I added the other day to catch this problem. It was not passing it before then, so I added it to debug why nzb providers did not add/save and then fixed that issue. I have not tested torrent rss feeds yet.

@atah, we have a built in yggtorrent provider, and you can also use jackett as an nzb torrent provider, but I will work on the torrent rss provider soon. Can someone give me an example torrent rss url and provider settings?

**Comment by pcliff069** [comment]
I am using Sickrage trying to connect to TorrentDay and am getting this error.
 No newznab_string passed to saveProviders
I have nothing to do with newznab and now cannot grab anything from TD

**Comment by jokklas** [comment]
Same here, custom torrent providers are suddenly gone and adding new ones doesn't work.
Hope it's a quick fix since I love showrss and a couple more.

**Comment by miigotu** [comment]
Working on it

**Comment by miigotu** [comment]
@pcliff069 normal built in providers seem to work fine here, you can ignore the error until I remove it. I started with a fresh config, enabled morethan.tv, saved and refreshed (this is an issue I want to resolve, refreshing shouldnt be necessary) and then  set the username and password and saved again, then did a manual search for an episode which was found and SickRage tried to send it to my fake torrent client (doesnt exist =P)
@jokklas I'm going to check with a test for torrent_rss now

**Comment by miigotu** [comment]
Should be fixed, please update

**Comment by fantasio31** [comment]
Seems OK for me. Will check regularly during few days and confirm.

**Comment by jokklas** [comment]
Aye, working for me as well, thanks a bunch!

**Comment by pcliff069** [comment]
yes all good thanks heaps
