### ISSUE TITLE
Search too sensitive

### ISSUE THREAD

**Issue by JayTurnr** [SickRage/SickRage#4204]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: 594f47e2b89832ca2e6ac7e89bdd5544403c1124
OS: Linux
What you did: Add Show > Search "Russell Howard"
What happened: No results
What you expected: Results of "Russell Howard's Good News", "Russell Howard's Good News Extra" etc

Not sure if this is your fault or TVDB's fault but looks like the apostrophe s was the issue

**Comment by miigotu** [comment]
Yeah, it's tvdb api doing that, we pass it to the api and show what they return (minus shows which are already in your show list). Going to close this because there isn't really anything I can do

**Comment by JayTurnr** [comment]
Fair enough, I know TVDB is constantly evolving. Let's hope their search logic evolves again to include that. Thanks for the swift response!
