### ISSUE TITLE
Multipart episodes

### ISSUE THREAD

**Issue by plato79** [SickRage/SickRage#4206]
Ok, this is not actually a bug, because I see some episodes in this format and it's AFAIK not possible to process via Sickrage.

For example for Ripper Street there are two parts for S04E01:

ripper.street.s04e01.1080p.bluray.x264-turmoil.mkv
ripper.street.s04e01.part.2.1080p.bluray.x264-turmoil.mkv

What does Sickrage do?:

It processes part.2 as S04E01, and ignores the first file because it's smaller.. If the file order would be reversed, it would probably process first part, and then overwrite it with the second part.

Another example, Star Wars Rebel Assault S02E01:

Star.Wars.Rebels.S02E01.Part1.1080p.BluRay.x264-CiNEFiLE.mkv
Star.Wars.Rebels.S02E01.Part2.1080p.BluRay.x264-CiNEFiLE.mkv

Again, the same situation and the same thing happens. This time Part1 is bigger so Part1 is assigned as S02E01 and Part2 is ignored or overwritten.

Is there any way to correctly process this files? When plex sees Part1, Part2 in the file it merges them and plays one after another. So playback is not a problem but processing them is impossible it seems.

**Comment by miigotu** [comment]
Merge the episodes with mkvmerge or similar, sickrage cannot handle multiple files with the same episode number because it makes no sense
