### ISSUE TITLE
Invalid API access returns generic 404 page instead of "Wrong API key used" when SickRage is at the root of the server

### ISSUE THREAD

**Issue by hjbotha** [SickRage/SickRage#4246]
Branch/Commit: master / 4b69468
OS: linuxserver/sickrage docker
What you did: Set web_root to "/" or "". Access /api/asdasd.
What happened: I got the generic 404 page, which exposes information about the server
What you expected: I should get "Wrong API key used"
Logs:
```
AA AttributeError: 'WebRoot' object has no attribute 'api/asdasd'
AA method = getattr(self, _route)
AA File "/app/sickrage/sickbeard/webserve.py", line 263, in get
2018-01-14 11:08:35 INFO     TORNADO :: Starting SickRage on http://0.0.0.0:8081/
2018-01-14 11:08:35 INFO     MAIN :: Starting SickRage [master] using '/config/config.ini'
```

The issue does not occur if web_root is not blank or "/". Below log is from such an attempt.

```
AA AttributeError: 'WebRoot' object has no attribute 'api/asdasd'
AA method = getattr(self, _route)
AA File "/app/sickrage/sickbeard/webserve.py", line 263, in get
2018-01-14 11:02:53 INFO     TORNADO :: Starting SickRage on http://0.0.0.0:8081/
2018-01-14 11:02:53 INFO     MAIN :: Starting SickRage [master] using '/config/config.ini'
```

This occurs because webserve.py is checking that url[:3] = "api", while in fact, url[:4] = "/api".

I'd try to create a PR but I don't know how to address this while preserving both use cases (and the third possible use case where a reverse proxy is rewriting paths). However, I think it might be related to the fact that, if the web_root is set to '/' it ends up being deleted by sickrage when it writes the config back to disk.

**Comment by OmgImAlexis** [comment]
This is a known issue. Not much we can do.

**Comment by hjbotha** [comment]
Sorry for the accidental pull request. Don't use github much.

Would there be a significant downside to just doing

```if url[:3] == "api" or url[:4] == "/api": ...```

or maybe adding after 
```
            if sickbeard.WEB_ROOT and self.request.uri.startswith(sickbeard.WEB_ROOT):
                url = url[len(sickbeard.WEB_ROOT) + 1:]
```
```
            else:
                url = url.lstrip('/')
```

and nesting the conditions if required.

I just consider this a slight security issue is all. Exposing that 1, we're using SickRage, and 2, some admittedly limited information about content.

**Comment by OmgImAlexis** [comment]
Since other apps use the API we tend to not change it as they may be relying on the fact that all Sickrage instances use the 404 page the same.

Also hiding the 404 page isn't really going to help with much since finding out your have sickrage running is as simple as visiting the non api routes.
