### ISSUE TITLE
[My bad!]Sickrage deleted my whole library!

### ISSUE THREAD

**Issue by EduardoOliveira** [SickRage/SickRage#4248]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master d8c2613583ce8b321a5adc9ff70c52e830f224a8
OS: ubuntu using docker (linuxserver/sickrage)
What you did: deleted 1 show
What happened: that shows parent folder was deleted, my whole library
What you expected: to delete only one show
Logs:
```
can only more recent logs (need help with that)
```

How can i recreate the file system so I can download everything again?

**Comment by OmgImAlexis** [comment]
How was your show library laid out? Did you have all your shows in separate directories?

**Comment by EduardoOliveira** [comment]
![screen shot 2018-01-15 at 09 33 12](https://user-images.githubusercontent.com/1675917/34935889-4ec7cb72-f9d7-11e7-93d1-60e00a24e0f5.png)

I queried a back up, I found the problem, Dragon ball was giving me trouble in another software (emby) so I deleted it in sickrage, yep... my bad...

Sorry guys.

Keep up the good work!

**Comment by EduardoOliveira** [comment]
I've recreated all the folders and manually forced some shows to re scan files and fully update, is there a way to do that for all the shows not going one by one?

**Comment by OmgImAlexis** [comment]
Use the mass update page.
