### ISSUE TITLE
Question about Scene Exception

### ISSUE THREAD

**Issue by saitoh183** [SickRage/SickRage#4256]
I just want to know or have a example of what would go into the scene exception at Season level in the new UI. The wiki isnt up to date on this.

![image](https://user-images.githubusercontent.com/1534197/35180003-eb7b8f18-fd73-11e7-9be5-946145ebdc80.png)

**Comment by miigotu** [comment]
Examples can be seen [here](https://github.com/SickRage/sickrage.github.io/blob/master/scene_exceptions/scene_exceptions.json#L508)
The ones with -1 as the key would translate to a show exception, ones that dont have a -1 but instead are under a season number would be a per season exception
