### ISSUE TITLE
Sickrage keeps adding an existing show to another folder

### ISSUE THREAD

**Issue by heula** [SickRage/SickRage#4259]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch: master
Commit: 4b69468cc1ea330f598364718068352a54b0eb92
Version: v2017.12.19-1
Database Version: 44.0
OS: Windows 10
What you did: Added the show "Het geheime dagboek van Hendrik Groen" to the preferred series folder. Removed the serie. The show is now no longer in my database but the error "2018-01-20 12:49:57 SHOWQUEUE-ADD :: [4b69468] Unable to look up the show in F:\Series Alex\Het geheime dagboek van Hendrik Groen on theTVDB using ID 337085, not using the NFO. Delete .nfo and try adding manually again.: HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/337085/nl.xml" keeps coming.
What happened: it keeps adding the serie "Het geheime dagboek van Hendrik Groen" with another tvdb id to the default series folder This tvdb id is the right one "336504". And this tvdb id is wrong "340505" and tvdb id 337085 does not excist anymore.
What you expected: When the show is added on the choosen TVDB id when adding it not uses the second tvdb id to add again in the default folder.
This also happens with the tv show Voetbalmaffia. Both have double TVDB id's
Logs: [sickrage.log](https://github.com/SickRage/SickRage/files/1648783/sickrage.log)
```
AA None
2018-01-20 12:34:25 ERROR Thread-32 :: [4b69468] Missing time zone for network: Paramount Network. Check valid network is set in indexer (theTVDB) before filing issue.
AA tvdb_error: HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/337085/nl.xml
AA raise tvdb_error(e)
AA File "C:\SickRage\SickRage\lib\tvdb_api\tvdb_api.py", line 629, in _getetsrc
AA self.config['url_seriesInfo'] % (sid, getShowInLanguage)
AA File "C:\SickRage\SickRage\lib\tvdb_api\tvdb_api.py", line 841, in _getShowData
AA self._getShowData(key, self.config['language'], True)
AA File "C:\SickRage\SickRage\lib\tvdb_api\tvdb_api.py", line 946, in __getitem__
AA s = t[self.indexer_id]
AA File "C:\SickRage\SickRage\sickbeard\show_queue.py", line 320, in run
AA Traceback (most recent call last):
2018-01-20 12:19:58 ERROR SHOWQUEUE-ADD :: [4b69468] Unable to look up the show in F:\Series Alex\Het geheime dagboek van Hendrik Groen on theTVDB using ID 337085, not using the NFO. Delete .nfo and try adding manually again.: HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/337085/nl.xml

```

**Comment by miigotu** [comment]
Remove the show, stop SickRage, and delete cache.db

**Comment by heula** [comment]
This is still an issue for me. Show is no longer in my database and I have deleted the cache.db multiple times now but Sickrage keeps adding the show over and over with a different and wrong tvdb ID which results in an error.

[sickrage.log](https://github.com/SickRage/SickRage/files/1743864/sickrage.log)

**Comment by heula** [comment]
Still adding this serie without my doing. Please tell my why and how to resolve this. Option you told earlier doesn't work.

[sickrage.log](https://github.com/SickRage/SickRage/files/1801757/sickrage.log)

**Comment by miigotu** [comment]
remove it from trakt..

**Comment by heula** [comment]
It is not in my Trakt collection.

**Comment by miigotu** [comment]
Delete the NFO file in `F:\Series Alex\Het geheime dagboek van Hendrik Groen`

**Comment by heula** [comment]
The show is with the right TVDB id already available in another Series directory. It is trying to add the same show with a different an wrong TVDB id to the standard series folder. That is what is happening day in day out. I have deleted that show from the database so why does it do this all the time with a wrong TVDB id?
It does not matter if the show is in the database or removed from it. 

Removing the nfo does not work.

[sickrage.log](https://github.com/SickRage/SickRage/files/1804664/sickrage.log)

**Comment by miigotu** [comment]
```
2018-03-12 00:04:56 DEBUG    TRAKTCHECKER :: SHOW_WATCHLIST::CHECK::START - Trakt Episode Watchlist
2018-03-12 00:05:01 INFO     TRAKTCHECKER :: Adding show 337085
2018-03-12 00:05:01 DEBUG    TRAKTCHECKER :: SHOW_WATCHLIST::CHECK::FINISH - Trakt Episode Watchlist
```

**Comment by heula** [comment]
Can't remove something that is not in my trakt collection. 

https://i.imgur.com/Z6V8lt6.jpg

Does it help when I remove the Trakt notification in Sickrage?

**Comment by miigotu** [comment]
Man... Collections, Watchlist, and EPISODES are different things.

It can NOT be in your collections, but be on your WATCHLIST

Go to `https://trakt.tv/users/dashboard/watchlist` and remove all episodes of that show from there.

**Comment by heula** [comment]
Thanks Man...

If I only had seen the watchlist butoon on the Trakt Dashboard. It wasn't there.
But thanks for the HELP!
