### ISSUE TITLE
Episodes are being added to wrong directory.

### ISSUE THREAD

**Issue by Gamegeneral** [SickRage/SickRage#4260]
Branch: master
Commit: 4b69468cc1ea330f598364718068352a54b0eb92
OS:Windows-10-10.0.16299
What you did: added an show to show list
What happened: show was added, snatched and downloaded, but post processed to main directory of all shows, not individual show folder. Main directory is one level above show folder.
What you expected: show would be processed to individual show folder, not the directory of shows
Logs:
```
[sickrage.log](https://github.com/SickRage/SickRage/files/1649371/sickrage.log)

```

**Comment by Gamegeneral** [comment]
Updating: 

If I place the episodes from the directory back into the folder scanned by the post processing process, they are placed in the correct directory on the second go-round.

**Comment by miigotu** [comment]
I believe this is related to another issue, where showName is unset

**Comment by miigotu** [comment]
#4224
