### ISSUE TITLE
[APP SUBMITTED]: Thread-86 :: [4b69468] Missing time zone for network: Sony Crackle. Check valid network is set in indexer (theTVDB) before filing issue.

### ISSUE THREAD

**Issue by divx-guy** [SickRage/SickRage#4264]
### INFO
Python Version: **2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.17074**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@4b69468cc1ea330f598364718068352a54b0eb92
No Log available with ERRORS:
### ERROR
```
Thread-86 :: [4b69468] Missing time zone for network: Sony Crackle. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by justClouds** [comment]
Having the same log entries on a Debian and an Ubuntu system.
Python Version: 2.7.12
Operating System: Ubuntu 16.04 LTS / Debian Stretch 9.2
Branch: master

**Comment by LeeThompson** [comment]
Really for streaming only networks if there isn't a timezone set, it should just default to GMT since it's not really applicable in the traditional sense anyway.
