### ISSUE TITLE
Missing filename 'manageEpisodeStatuses.js' after latest update

### ISSUE THREAD

**Issue by liranbg** [SickRage/SickRage#4272]
Branch/Commit: Master 5bc5c3aa7b0007ee3c69e7cacfb975af597f8f37
OS: `Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial`
What you did: used "Manual Post Processing"
What happened: Log error, nothing to really worry about (?)
What you expected: 
Logs:
```
...
AA 2018-01-25 13:01:59 ERROR Could not open static file u'/opt/sickrage/gui/slick/js/manageEpisodeStatuses.js'
...
```

**Comment by PaulAqua** [comment]
Same error here + tvshows have weird naming for seasons. Example: **Season 4294967295** Instead of **Season 5**

**Comment by paullee29** [comment]
I have the same error as well, but thus far no naming errors, I am version: v2018.02.26-2

**Comment by enochian0117** [comment]
Same error appearing in logs.  v2018.02.26-2
No naming convention issues

**Comment by Dragonsys** [comment]
Same issue. Looking at the latest commit, the file missing there as well. (https://github.com/SickRage/SickRage/tree/master/gui/slick/js)

Branch: master
Commit: 53e6cc50c086757c31fc518b550d7681c61649e6
Version: v2018.03.12-1
Database Version: 44.0

> AA None
> AA 2018-03-11 19:04:04 ERROR Could not open static file u'C:\\Tools\\SickRage\\SickRage\\gui\\slick\\js\\manageEpisodeStatuses.js'

**Comment by BJamin99** [comment]
gui/slick/views/manage_episodeStatuses.mako references <script type="text/javascript" src="${static_url('js/manageEpisodeStatuses.js')}"> which doesn't exist.
