### ISSUE TITLE
addExistingShows duplicate the folder name

### ISSUE THREAD

**Issue by ediazrod** [SickRage/SickRage#4288]
When I try to add a new existent show for example on  addExistingShow for example "Mosaic".

The part 5.

#5 Verify Your Input
Show name
Mosaic
Directory
/datos/raid/series/MosaicMosaic
Quality
SD

Duplicate the name of the show like /MosaicMosaic

The show add ok but I can't access to the show I get a error.
Regards!

**Comment by ediazrod** [comment]
I am trying to debug the issue because I think is related with core.js or core.min.js and the tag name desc-directory-name

**Comment by OmgImAlexis** [comment]
Please reopen this issue and follow the issue template. It's there for a reason.
