### ISSUE TITLE
How do I stop "Upgrading" Shows?

### ISSUE THREAD

**Issue by rbhamilton** [SickRage/SickRage#4296]
Hey sorry I know this isn't the right format but I can't find any other way to ask a question.  I just switched to SickRage (love it) and imported all my shows into it.  Easy.  Thanks!  Wonderful program.

However this morning I woke up and found it had re-downloaded about 850 shows.

I've set my "allowed" quality to any and my preferred to 720P.  Meaning (to me) if you can get it in 720P then that's great but if you can only find it in SD that's fine.  But I'm not fixated on it.  Please don't re-download everything!!

How do I turn off the "upgrading" of older shows?  Is there any way to just disable that feature?  If there is, I can't seem to find it but I'm guessing it's something obvious.

Many thanks in advance for your assistance.

**Comment by Arcanemagus** [comment]
The best option is to set a custom quality priority to match what you want (IE: A _maximum_ of 720p). You should also mark shows that are "done" as `Paused`. This will prevent Sickrage from attempting any further searches for the show.

For example if the show has ended so there will no longer be new episodes, and what you have is at the best quality that you want, mark it as Paused.

**Comment by miigotu** [comment]
Set the old episodes to "Archived"
