### ISSUE TITLE
[APP SUBMITTED]: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by AubreyKloppers** [SickRage/SickRage#4304]
### INFO
Python Version: **2.7.3 (default, Jun 21 2016, 18:38:19) [GCC 4.7.2]**
Operating System: **Linux-3.2.0-4-amd64-x86_64-with-debian-7.11**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@f30a84430b444bbd39308bfb8ff85ca17a48abd1
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-334069 :: [TorrentDay] :: [f30a844] Exception while searching TorrentDay. Error: TypeError("'NoneType' object is not iterable",)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by AubreyKloppers** [comment]
### INFO
Python Version: **2.7.3 (default, Jun 21 2016, 18:38:19) [GCC 4.7.2]**
Operating System: **Linux-3.2.0-4-amd64-x86_64-with-debian-7.11**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@f30a84430b444bbd39308bfb8ff85ca17a48abd1
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-310516 :: [TorrentDay] :: [f30a844] Exception while searching TorrentDay. Error: TypeError("'NoneType' object is not iterable",)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by AubreyKloppers** [comment]
### INFO
Python Version: **2.7.3 (default, Jun 21 2016, 18:38:19) [GCC 4.7.2]**
Operating System: **Linux-3.2.0-4-amd64-x86_64-with-debian-7.11**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@f30a84430b444bbd39308bfb8ff85ca17a48abd1
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-265454 :: [TorrentDay] :: [f30a844] Exception while searching TorrentDay. Error: TypeError("'NoneType' object is not iterable",)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by AubreyKloppers** [comment]
### INFO
Python Version: **2.7.3 (default, Jun 21 2016, 18:38:19) [GCC 4.7.2]**
Operating System: **Linux-3.2.0-4-amd64-x86_64-with-debian-7.11**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@f30a84430b444bbd39308bfb8ff85ca17a48abd1
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-334069 :: [TorrentDay] :: [f30a844] Exception while searching TorrentDay. Error: TypeError("'NoneType' object is not iterable",)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by AubreyKloppers** [comment]
### INFO
Python Version: **2.7.3 (default, Jun 21 2016, 18:38:19) [GCC 4.7.2]**
Operating System: **Linux-3.2.0-4-amd64-x86_64-with-debian-7.11**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@f30a84430b444bbd39308bfb8ff85ca17a48abd1
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-310516 :: [TorrentDay] :: [f30a844] Exception while searching TorrentDay. Error: TypeError("'NoneType' object is not iterable",)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by AubreyKloppers** [comment]
### INFO
Python Version: **2.7.3 (default, Jun 21 2016, 18:38:19) [GCC 4.7.2]**
Operating System: **Linux-3.2.0-4-amd64-x86_64-with-debian-7.11**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@f30a84430b444bbd39308bfb8ff85ca17a48abd1
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-265454 :: [TorrentDay] :: [f30a844] Exception while searching TorrentDay. Error: TypeError("'NoneType' object is not iterable",)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by MarioCaires** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@5066fab234dc43e24648601b932523d87d9bac6c
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-78956 :: [TorrentDay] :: [5066fab] Exception while searching TorrentDay. Error: TypeError("'NoneType' object is not iterable",)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by tonyp1983** [comment]
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-11.0-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@5066fab234dc43e24648601b932523d87d9bac6c
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-78804 :: [TorrentDay] :: [5066fab] Exception while searching TorrentDay. Error: TypeError("'NoneType' object is not iterable",)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by tonyp1983** [comment]
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-11.0-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@5066fab234dc43e24648601b932523d87d9bac6c
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-71814 :: [TorrentDay] :: [5066fab] Exception while searching TorrentDay. Error: TypeError("'NoneType' object is not iterable",)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by sabr5** [comment]
2018-03-09 21:46:46 SEARCHQUEUE-BACKLOG-335992 :: [TorrentDay] :: [6e3a1dc] Exception while searching TorrentDay. Error: TypeError("'NoneType' object is not iterable",)

**Comment by dirkr07** [comment]
### INFO
Python Version: **2.7.13 (default, Dec 19 2016, 01:06:03) [GCC 4.3.2]**
Operating System: **Linux-2.6.32.12-ppc-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@ae9ffb6ae2cc102cfa6d528f9779a6db19f82c91
Link to Log: https://gist.github.com/f9d910dd51b91d3d25206f7d313b1edb
### ERROR
```
FINDPROPERS :: [TorrentDay] :: [TorrentDay] :: [TorrentDay] :: [TorrentDay] :: [TorrentDay] :: [TorrentDay] :: [TorrentDay] :: [TorrentDay] :: [TorrentDay] :: [ae9ffb6] Exception while searching propers in TorrentDay, skipping: 'NoneType' object is not iterable
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by dirkr07** [comment]
### INFO
Python Version: **2.7.13 (default, Dec 19 2016, 01:06:03) [GCC 4.3.2]**
Operating System: **Linux-2.6.32.12-ppc-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@ae9ffb6ae2cc102cfa6d528f9779a6db19f82c91
Link to Log: https://gist.github.com/5b509a5e7e2e595fa07eb4d24f69e802
### ERROR
```
FINDPROPERS :: [TorrentDay] :: [TorrentDay] :: [TorrentDay] :: [TorrentDay] :: [TorrentDay] :: [TorrentDay] :: [TorrentDay] :: [TorrentDay] :: [ae9ffb6] Exception while searching propers in TorrentDay, skipping: 'NoneType' object is not iterable
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by dirkr07** [comment]
### INFO
Python Version: **2.7.13 (default, Dec 19 2016, 01:06:03) [GCC 4.3.2]**
Operating System: **Linux-2.6.32.12-ppc-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@ae9ffb6ae2cc102cfa6d528f9779a6db19f82c91
No Log available with ERRORS:
### ERROR
```
FINDPROPERS :: [TorrentDay] :: [TorrentDay] :: [TorrentDay] :: [TorrentDay] :: [TorrentDay] :: [TorrentDay] :: [TorrentDay] :: [ae9ffb6] Exception while searching propers in TorrentDay, skipping: 'NoneType' object is not iterable
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by dirkr07** [comment]
### INFO
Python Version: **2.7.13 (default, Dec 19 2016, 01:06:03) [GCC 4.3.2]**
Operating System: **Linux-2.6.32.12-ppc-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@ae9ffb6ae2cc102cfa6d528f9779a6db19f82c91
No Log available with ERRORS:
### ERROR
```
FINDPROPERS :: [TorrentDay] :: [TorrentDay] :: [TorrentDay] :: [TorrentDay] :: [TorrentDay] :: [TorrentDay] :: [ae9ffb6] Exception while searching propers in TorrentDay, skipping: 'NoneType' object is not iterable
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by dirkr07** [comment]
### INFO
Python Version: **2.7.13 (default, Dec 19 2016, 01:06:03) [GCC 4.3.2]**
Operating System: **Linux-2.6.32.12-ppc-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@ae9ffb6ae2cc102cfa6d528f9779a6db19f82c91
No Log available with ERRORS:
### ERROR
```
FINDPROPERS :: [TorrentDay] :: [TorrentDay] :: [TorrentDay] :: [TorrentDay] :: [TorrentDay] :: [ae9ffb6] Exception while searching propers in TorrentDay, skipping: 'NoneType' object is not iterable
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by dirkr07** [comment]
### INFO
Python Version: **2.7.13 (default, Dec 19 2016, 01:06:03) [GCC 4.3.2]**
Operating System: **Linux-2.6.32.12-ppc-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@ae9ffb6ae2cc102cfa6d528f9779a6db19f82c91
No Log available with ERRORS:
### ERROR
```
FINDPROPERS :: [TorrentDay] :: [TorrentDay] :: [TorrentDay] :: [TorrentDay] :: [ae9ffb6] Exception while searching propers in TorrentDay, skipping: 'NoneType' object is not iterable
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by dirkr07** [comment]
### INFO
Python Version: **2.7.13 (default, Dec 19 2016, 01:06:03) [GCC 4.3.2]**
Operating System: **Linux-2.6.32.12-ppc-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@ae9ffb6ae2cc102cfa6d528f9779a6db19f82c91
No Log available with ERRORS:
### ERROR
```
FINDPROPERS :: [TorrentDay] :: [TorrentDay] :: [TorrentDay] :: [ae9ffb6] Exception while searching propers in TorrentDay, skipping: 'NoneType' object is not iterable
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by dirkr07** [comment]
### INFO
Python Version: **2.7.13 (default, Dec 19 2016, 01:06:03) [GCC 4.3.2]**
Operating System: **Linux-2.6.32.12-ppc-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@ae9ffb6ae2cc102cfa6d528f9779a6db19f82c91
No Log available with ERRORS:
### ERROR
```
FINDPROPERS :: [TorrentDay] :: [TorrentDay] :: [ae9ffb6] Exception while searching propers in TorrentDay, skipping: 'NoneType' object is not iterable
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by dirkr07** [comment]
### INFO
Python Version: **2.7.13 (default, Dec 19 2016, 01:06:03) [GCC 4.3.2]**
Operating System: **Linux-2.6.32.12-ppc-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@ae9ffb6ae2cc102cfa6d528f9779a6db19f82c91
No Log available with ERRORS:
### ERROR
```
FINDPROPERS :: [TorrentDay] :: [ae9ffb6] Exception while searching propers in TorrentDay, skipping: 'NoneType' object is not iterable
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by Grantp1962** [comment]
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-11.0-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@ae9ffb6ae2cc102cfa6d528f9779a6db19f82c91
No Log available with ERRORS:
### ERROR
```
FINDPROPERS :: [TorrentDay] :: [ae9ffb6] Exception while searching propers in TorrentDay, skipping: 'NoneType' object is not iterable
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by sabr5** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.16299**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@53e6cc50c086757c31fc518b550d7681c61649e6
Link to Log: https://gist.github.com/58aee714da5bfbd3dc33381a19881409
### ERROR
```
SEARCHQUEUE-BACKLOG-284190 :: [TorrentDay] :: [53e6cc5] Exception while searching TorrentDay. Error: TypeError("'NoneType' object is not iterable",)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by sabr5** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.16299**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@53e6cc50c086757c31fc518b550d7681c61649e6
Link to Log: https://gist.github.com/8cd3ff4591c1c9e24d1b75a3db324900
### ERROR
```
SEARCHQUEUE-BACKLOG-284190 :: [TorrentDay] :: [53e6cc5] Exception while searching TorrentDay. Error: TypeError("'NoneType' object is not iterable",)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by sabr5** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.16299**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@53e6cc50c086757c31fc518b550d7681c61649e6
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-295647 :: [TorrentDay] :: [53e6cc5] Exception while searching TorrentDay. Error: TypeError("'NoneType' object is not iterable",)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by sabr5** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.16299**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@1981e70388b85e873710028b0b519d2251f8e623
Link to Log: https://gist.github.com/c5e118821fadcb5c49e8ab991612f2ae
### ERROR
```
SEARCHQUEUE-BACKLOG-284190 :: [TorrentDay] :: [1981e70] Exception while searching TorrentDay. Error: TypeError("'NoneType' object is not iterable",)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by dirkr07** [comment]
@miigotu  any idea if this one can be solved?
