### ISSUE TITLE
Utils.py causes two UserWarning errors in console (no module named lxml.html & falling back to beautifulsoup)

### ISSUE THREAD

**Issue by kailia** [SickRage/SickRage#4316]
```
C:\DATA\SickRage\SickRage\lib\imdb\parser\http\utils.py:481: UserWarning: unable to use "lxml": No module named lxml.html
  warnings.warn('unable to use "%s": %s' % (mod, str(e)))
C:\DATA\SickRage\SickRage\lib\imdb\parser\http\utils.py:472: UserWarning: falling back to "beautifulsoup"
  warnings.warn('falling back to "%s"' % mod)
```

Note: these only appears in the Dos window, not in the SickRage logs (even debug).

Branch: master
Commit: f30a84430b444bbd39308bfb8ff85ca17a48abd1
Version: v2018.02.06-1
Database Version: 44.0
Python Version: 2.7.11 (v2.7.11:6d1b6a68f775, Dec 5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]
SSL Version: OpenSSL 1.0.2d 9 Jul 2015
OS: Windows-10-10.0.17074

**Comment by miigotu** [comment]
install bs4 and lxml... They arent required but they are helpful
