### ISSUE TITLE
Subtitle Find Frequency search vs Manual search

### ISSUE THREAD

**Issue by heula** [SickRage/SickRage#4326]
#
Branch/Commit: Master / 5bc5c3a
OS: Windows 10 x64
What you did: set auto search for subtitles to 1 hour
What happened: Downloaded subtitles are not as much as when I run a manual search with the "Missed subtitle management" option.
What you expected: That it searches every hour for all available subtitles for every episode without subtitles like the manual search does.

[sickrage.log](https://github.com/SickRage/SickRage/files/1744409/sickrage.log)

It seems that a manual search for subtitles (Dutch) do have more hits than the search subtitles option that I have set for every hour. Tested multiple times now and every manual search has found more subtitles for my episodes than the hourly search..

Thanks

**Comment by miigotu** [comment]
The auto search only checks for episodes from the last 24 hours every hour. Episodes older than that are checked less often, once every 24 hours until they are 7 days old and then once a week iirc.

**Comment by heula** [comment]
Oh okay. Good to know.
Thanks

**Comment by heula** [comment]
Is there a script or batch file that I can run every day that riggers the manual search function?

**Comment by miigotu** [comment]
You can write your own script, check `http://ip:port/home/apibuilder`
