### ISSUE TITLE
2018-02-26 21:04:48 Thread-15 :: [5066fab] Unable to create the folder «foldername», can't add the show

### ISSUE THREAD

**Issue by ciberboy** [SickRage/SickRage#4336]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
  SickRage Info:
Branch: master
Commit: 5066fab234dc43e24648601b932523d87d9bac6c
Version: v2018.02.17-1
Database Version: 44.0
  Python Version: 2.7.14 (default, Sep 23 2017, 22:06:14) [GCC 7.2.0]
  SSL Version: OpenSSL 1.0.2g 1 Mar 2016
  OS: Linux-4.13.0-32-generic-x86_64-with-Ubuntu-17.10-artful
  Locale: en_US.UTF-8
OS: Ubuntu 17.10
What you did:Add a show
What happened: [5066fab] Unable to create the folder «foldername», can't add the show
What you expected: For a folder to be created
Logs:[5066fab] Unable to create the folder «foldername», can't add the show
```
PASTE LOGS HERE
```
This happens on adding a show, point to a folder on a WDMyCloud external HD or a local folder, shuch as download folder. I've tried every suggestion I could find on the web

**Comment by ciberboy** [comment]
BTW, this was a fresh install

**Comment by EqUaTe** [comment]
Does the user SR is running as have RWX permissions to the target Shows directory, and at least read/execute on every directory prior to that?

**Comment by ciberboy** [comment]
It hadn't, but I have granted access to it:
ciberboy@ciberserver:/media/windowsshare$ ls -la
total 8
drwxrwxrwx 4 sickrage sickrage 4096 nov 23 23:15 .
drwxr-xr-x 4 root     root     4096 jan  3 20:00 ..
drwxr-xr-x 2 ciberboy root        0 jan 29 19:11 Filmes
drwxr-xr-x 2 ciberboy root        0 fev 26 20:59 Series

**Comment by ciberboy** [comment]
To be clear, the issue still remains.

**Comment by WebSpider** [comment]
The write permission seems to be missing.. Please chmod 777 the dirs and see if that solves your issue

**Comment by ciberboy** [comment]
Hi

Thank you for your reply. I have resolved it my moving to Sonarr.

Thanks!
