### ISSUE TITLE
[APP SUBMITTED]: Thread-14 :: [6e3a1dc] Missing time zone for network: Sony Crackle. Check valid network is set in indexer (theTVDB) before filing issue.

### ISSUE THREAD

**Issue by sulaiman-allen** [SickRage/SickRage#4350]
### INFO
Python Version: **2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]**
Operating System: **Linux-4.4.0-116-generic-x86_64-with-Ubuntu-16.04-xenial**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@6e3a1dccd94857fc381c9a246b903904eca424e1
No Log available with ERRORS:
### ERROR
```
Thread-14 :: [6e3a1dc] Missing time zone for network: Sony Crackle. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by DravenSA** [comment]
I would love a fix for this... i tried deleted cache.db like a previous post said, but it didnt work

**Comment by kidiavn** [comment]
### INFO
Python Version: **2.7.12 (default, Aug 20 2016, 20:35:21) [GCC 5.2.0]**
Operating System: **Linux-4.2.8-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@6e3a1dccd94857fc381c9a246b903904eca424e1
No Log available with ERRORS:
### ERROR
```
Thread-15 :: [6e3a1dc] Missing time zone for network: Sony Crackle. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by zaans2** [comment]
The fix for any missing timezones for networks, is adding the network and corresponding timezone to `network_timezones.txt` (https://github.com/SickRage/sickrage.github.io/blob/master/sb_network_timezones/network_timezones.txt). You can do this yourself and crate a pull request. They will then merge it into the file.

**Comment by DravenSA** [comment]
So i did what you said, then did a pull request, it was approved... now what? because i did an update with 2 commits.. and it wasn't there.

**Comment by zaans2** [comment]
The owner has to merge it. That doesnt happen automatically. It being approved is just someone saying "this is okay to merge". Tag @miigotu in a comment there once it is approved

**Comment by DravenSA** [comment]
Thanks... will do
