### ISSUE TITLE
how get api key with credential

### ISSUE THREAD

**Issue by nico6308** [SickRage/SickRage#4352]
hi, I search a method for get api key with server address and my credential it's for an iOS app it is possible ? I can't find an solution for that on the web but the app nzbUnity can do that... thx

**Comment by miigotu** [comment]
`https://0.0.0.0:8081/getkey?u=username&p=password`

I would suggest using POST instead of GET though, the same handler will work either way.

**Comment by nico6308** [comment]
Great perfect thank you !
