### ISSUE TITLE
[APP SUBMITTED]: index() got an unexpected keyword argument 'web'

### ISSUE THREAD

**Issue by cheesehd** [SickRage/SickRage#4354]
### INFO
Python Version: **2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]**
Operating System: **Linux-4.4.0-116-generic-x86_64-with-Ubuntu-16.04-xenial**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@6e3a1dccd94857fc381c9a246b903904eca424e1
No Log available with ERRORS:
### ERROR
```
Thread-53 :: [6e3a1dc] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 280, in async_call
    result = function(**kwargs)
TypeError: index() got an unexpected keyword argument 'web'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by dporem** [comment]
### INFO
Python Version: **2.7.16 (default, Apr  6 2019, 01:42:57) [GCC 8.2.0]**
Operating System: **Linux-4.19.66-v7+-armv7l-with-debian-10.0**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
MANUAL :: [e094759] Failed doing webui callback: Traceback (most recent call last):
  File "/home/pi/.sickchill/sickchill/views/index.py", line 180, in async_call
    result = function(**kwargs)
TypeError: index() got an unexpected keyword argument 'web'

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
