### ISSUE TITLE
YGG error send rtorrent

### ISSUE THREAD

**Issue by skillfr** [SickRage/SickRage#4359]
Plugin YGG works perfectly for search but does not send it on rtorrent
Plugin Xthor works perfectly for search and sends on rtorrent....

### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Master
OS: Debian 7
What you did:
What happened:
What you expected:
Logs:
```
AA . Error not a valid bencoded string
AA Release Group: xxxx
AA Size: -1
AA Name: xxxxx02E01.FRENCH.720p
AA Quality: 720p WEB-DL
AA status: 5
AA hastbn: False
AA hasnfo: False
AA airdate: 736598 (datetime.date(2017, 9, 26))
AA subtitles_lastsearch: '0001-01-01 00:00:00'
AA subtitles_searchcount: 0
AA subtitles: u''
AA description: u"blablabla"
AA location: u''
AA u"xxxxx" - S2E1 - u'xxxx'
AA Episodes:
AA Extra Info:
2018-03-09 18:48:03 DEBUG SEARCHQUEUE-MANUAL-311790 :: rTorrent: Exception raised when sending torrent: YggTorrent @ https://yggtorrent.com/engine/download_torrent?id=xxxx
AA BTFailure: not a valid bencoded string
AA raise BTFailure("not a valid bencoded string")
AA File "/opt/SickRage/lib/bencode/__init__.py", line 68, in bdecode
AA torrent_bdecode = bencode.bdecode(result.content)
AA File "/opt/SickRage/sickbeard/clients/generic.py", line 215, in _get_torrent_hash
AA result = self._get_torrent_hash(result)
AA File "/opt/SickRage/sickbeard/clients/generic.py", line 257, in sendTORRENT
AA Traceback (most recent call last):
2018-03-09 18:48:03 ERROR SEARCHQUEUE-MANUAL-311790 :: [832ccb4] rTorrent: Failed Sending Torrent
2018-03-09 18:48:03 DEBUG SEARCHQUEUE-MANUAL-311790 :: Error is: not a valid bencoded string
AA BTFailure: not a valid bencoded string
AA raise BTFailure("not a valid bencoded string")
AA File "/opt/SickRage/lib/bencode/__init__.py", line 68, in bdecode
AA torrent_bdecode = bencode.bdecode(result.content)
AA File "/opt/SickRage/sickbeard/clients/generic.py", line 215, in _get_torrent_hash
AA Traceback (most recent call last):
2018-03-09 18:48:03 ERROR SEARCHQUEUE-MANUAL-311790 :: [832ccb4] Unable to bdecode torrent
2018-03-09 18:48:03 DEBUG SEARCHQUEUE-MANUAL-311790 :: Calling rTorrent Client
```

**Comment by Danelem** [comment]
I think it's the same error as here: #4331

**Comment by chripink** [comment]
Hi,

I have the same issue. I hope it can be fixed :)

AA BTFailure: not a valid bencoded string
AA raise bencode.BTL.BTFailure("not a valid bencoded string")
AA File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/helpers.py", line 1935, in bdecode
AA torrent_bdecode = helpers.bdecode(result.content, True)
AA File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/clients/generic.py", line 216, in _get_torrent_hash
AA result = self._get_torrent_hash(result)
AA File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/clients/generic.py", line 259, in sendTORRENT
AA Traceback (most recent call last):
2018-03-13 09:14:09 ERROR SEARCHQUEUE-BACKLOG-289590 :: [53e6cc5] DownloadStation: Failed Sending Torrent
AA BTFailure: not a valid bencoded string
AA raise bencode.BTL.BTFailure("not a valid bencoded string")
AA File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/helpers.py", line 1935, in bdecode
AA torrent_bdecode = helpers.bdecode(result.content, True)
AA File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/clients/generic.py", line 216, in _get_torrent_hash
AA Traceback (most recent call last):
2018-03-13 09:14:09 ERROR SEARCHQUEUE-BACKLOG-289590 :: [53e6cc5] Unable to bdecode torrent
2018-03-13 09:14:09 INFO SEARCHQUEUE-BACKLOG-289590 :: Downloading Mr.Robot.S01.FRENCH.720p.BluRay.x264-SODAPOP from YggTorrent

**Comment by skillfr** [comment]
temporary solution, create an RSS feed in sickrage with https://github.com/Guisch/YGG-rss-feed-generator, the time that it is repaired
