### ISSUE TITLE
Unable to manually add shows

### ISSUE THREAD

**Issue by thelynx77** [SickRage/SickRage#4364]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Master /  2bdb321
OS: Raspian
What you did: try to add a show manually, Timeless(2016)
What happened: error screen
What you expected: show to be added
Logs:
...
AA TypeError: Expected bytes, unicode, or None; got 
AA "Expected bytes, unicode, or None; got %r" % type(value)
AA File "/opt/sickrage/lib/tornado/escape.py", line 248, in to_basestring
AA to_basestring(value))
AA File "/opt/sickrage/lib/tornado/escape.py", line 63, in xhtml_escape
AA kwargs[arg] = xhtml_escape(value)
AA File "/opt/sickrage/sickbeard/webserve.py", line 281, in async_call
AA result = self.fn(*self.args, **self.kwargs)
AA File "/opt/sickrage/lib/concurrent/futures/thread.py", line 62, in run
AA return self.__get_result()
AA File "/opt/sickrage/lib/concurrent/futures/_base.py", line 422, in result
AA value = future.result()
AA File "/opt/sickrage/lib/tornado/gen.py", line 1055, in run
AA results = yield self.async_call(method)
AA File "/opt/sickrage/sickbeard/webserve.py", line 265, in get
AA yielded = self.gen.throw(*exc_info)
AA File "/opt/sickrage/lib/tornado/gen.py", line 1063, in run
AA raise_exc_info(self._exc_info)
AA File "/opt/sickrage/lib/tornado/concurrent.py", line 238, in result
AA value = future.result()
AA File "/opt/sickrage/lib/tornado/gen.py", line 1055, in run
AA result = yield result
AA File "/opt/sickrage/lib/tornado/web.py", line 1511, in _execute
AA Traceback (most recent call last):
AA HTTPServerRequest(protocol=u'http', host='192.168.58.11:8081', method='POST', uri='/addShows/addNewShow', version='HTTP/1.1', remote_ip='192.168.58.241', headers={'Origin': 'http://192.168.58.11:8081', 'Content-Length': '330', 'Accept-Language': 'en-US,en;q=0.9', 'Accept-Encoding': 'gzip, deflate', 'Host': '192.168.58.11:8081', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8', 'Upgrade-Insecure-Requests': '1', 'Connection': 'keep-alive', 'Referer': 'http://192.168.58.11:8081/addShows/newShow/', 'Cache-Control': 'max-age=0', 'Cookie': 'SID=oRRYcch1d0r/zJMLfGxbCkkx3nWcQFEl', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36', 'Content-Type': 'application/x-www-form-urlencoded'})
AA 2018-03-10 10:59:23 ERROR Uncaught exception POST /addShows/addNewShow (192.168.58.241)
AA TypeError: Expected bytes, unicode, or None; got 
AA "Expected bytes, unicode, or None; got %r" % type(value)
AA File "/opt/sickrage/lib/tornado/escape.py", line 248, in to_basestring
AA to_basestring(value))
AA File "/opt/sickrage/lib/tornado/escape.py", line 63, in xhtml_escape
AA kwargs[arg] = xhtml_escape(value)
AA File "/opt/sickrage/sickbeard/webserve.py", line 281, in async_call
AA Traceback (most recent call last):
AA TypeError: Expected bytes, unicode, or None; got 
AA "Expected bytes, unicode, or None; got %r" % type(value)
AA File "/opt/sickrage/lib/tornado/escape.py", line 248, in to_basestring
AA to_basestring(value))
AA File "/opt/sickrage/lib/tornado/escape.py", line 63, in xhtml_escape
AA kwargs[arg] = xhtml_escape(value)
AA File "/opt/sickrage/sickbeard/webserve.py", line 281, in async_call
2018-03-10 10:59:22 ERROR Thread-14 :: [2bdb321] Failed doing webui callback: Traceback (most recent call last):
2018-03-10 10:58:05 INFO CHECKVERSION :: Checking for updates using GIT
2018-03-10 10:58:05 INFO TORNADO :: Starting SickRage on http://0.0.0.0:8081/
2018-03-10 10:58:05 INFO MAIN :: Starting SickRage [master] using '/opt/sickrage/config.ini'
```

**Comment by rw-aldum** [comment]
can confirm, can't add new shows. tried removing a show and adding it back as an existing show, same issue.

Removed all shows with special characters, same issue.

**Comment by svencoeck** [comment]
Reverting to a previous commit seems to fix the issue

`git checkout 6e3a1d`

**Comment by miigotu** [comment]
it will be fixed in a few minutes. It was introduced when correcting a security flaw.

**Comment by miigotu** [comment]
Please confirm the new update to master fixes the issue. Tag me if any more errors come up.
