### ISSUE TITLE
Can't add from existing folder with special characters [Synology DSM6.2]

### ISSUE THREAD

**Issue by Jamyz** [SickRage/SickRage#4369]
Branch/Commit:master/eb0cc11f58c817ba0ba9c5ca3bbad7c43145c974
OS:Linux-3.10.102-x86_64-with-glibc2.2.5
What you did:
Add Folder with character like Marvel's or DC's
What happened:
a fix or code
What you expected:
The tip is because something is wrong with the path.
The correct path is :
`/volume1/TV Show/Marvel’s Jessica Jones (2015)`
and sickrage path is
`/volume1/TV Show/Marvel&#39;s Jessica Jones (2015)`

But when i try to edit the path i see `Marvel’s` but is put `Marvel&#39;s`

Cant check files files in the folders

Logs:
```
2018-03-10 19:57:13 INFO SHOWQUEUE-ADD :: Done cache check 2018-03-10 19:57:06 INFO
SHOWQUEUE-ADD :: 284190: Updating NFOs for show with new indexer info 2018-03-10 19:56:55
INFO SHOWQUEUE-ADD :: Setting all episodes to the specified default status: 5 2018-03-10 19:56:54 INFO SHOWQUEUE-ADD :: 284190: Unable to find the show in the database 2018-03-10 19:56:52
INFO SHOWQUEUE-ADD :: theTVDB: {u'useZip': True, u'apikey': u'F9C450E78D99172E', u'cache': u'/var/packages/sickrage/target/var/cache/indexers/theTVDB', u'language': 'fr'} 2018-03-10 19:56:52 INFO SHOWQUEUE-ADD :: Starting to add show by ShowDir: /volume1/TV Show/Marvel's Jessica Jones (2015)
```

`2018-03-10 20:40:15 DEBUG SHOWQUEUE-ADD :: 284190: Loading show info from IMDb 2018-03-10 20:40:12 DEBUG SHOWQUEUE-ADD :: Retrieving show info from IMDb 2018-03-10 20:40:12 INFO SHOWQUEUE-ADD :: Setting all episodes to the specified default status: 5 2018-03-10 20:40:12 DEBUG SHOWQUEUE-ADD :: Setter sets location to /volume1/TV Show/Marvel's Jessica Jones (2015) 2018-03-10 20:40:11 DEBUG SHOWQUEUE-ADD :: 284190: Loading show info from theTVDB 2018-03-10 20:40:11 INFO SHOWQUEUE-ADD :: 284190: Unable to find the show in the database 2018-03-10 20:40:05 INFO SHOWQUEUE-ADD :: theTVDB: {u'useZip': True, u'apikey': u'F9C450E78D99172E', u'cache': u'/var/packages/sickrage/target/var/cache/indexers/theTVDB', u'language': 'fr'} 2018-03-10 20:40:05 INFO SHOWQUEUE-ADD :: Starting to add show by ShowDir: /volume1/TV Show/**Marvel's** Jessica Jones (2015) 2018-03-10 20:39:56 DEBUG Thread-16 :: Searching for Show with searchterm(s): ['Jessica Jones'] on Indexer: theTVDB 2018-03-10 20:39:51 DEBUG Thread-17 :: Searching for Show with searchterm(s): ['Marvel's Jessica Jones'] on Indexer: theTVDB`

**Comment by Jamyz** [comment]
The tip is because something is wrong with the path.
The correct path is :
/volume1/TV Show/Marvel’s Jessica Jones (2015)
and sickrage path is
/volume1/TV Show/Marvel&#39;s Jessica Jones (2015)

But when i try to edit the path i see Marvel’s but is put Marvel&#39;s

**Comment by Jamyz** [comment]
Commit eb0cc11f58c817ba0ba9c5ca3bbad7c43145c974

**Comment by miigotu** [comment]
You need to use a `'` not a `’`

**Comment by Jamyz** [comment]
Sorry @miigotu i use `'` not `’`
Maybe capture screen help
<img width="1022" alt="capture d ecran 2018-03-11 a 00 01 01" src="https://user-images.githubusercontent.com/6177824/37247719-f2cc7a84-24bf-11e8-949d-6c7dc21fd09c.png">
<img width="829" alt="capture d ecran 2018-03-11 a 00 02 51" src="https://user-images.githubusercontent.com/6177824/37247720-f68efa52-24bf-11e8-9a47-5bf737f0de7c.png">
<img width="590" alt="capture d ecran 2018-03-11 a 00 04 08" src="https://user-images.githubusercontent.com/6177824/37247723-fce39e08-24bf-11e8-9ccb-8bfac79c1244.png">
<img width="749" alt="capture d ecran 2018-03-11 a 00 04 18" src="https://user-images.githubusercontent.com/6177824/37247724-fcffccf4-24bf-11e8-94d0-a4f0311a1f74.png">
<img width="290" alt="capture d ecran 2018-03-11 a 00 04 43" src="https://user-images.githubusercontent.com/6177824/37247725-fd1c1350-24bf-11e8-8590-004cb38185a8.png">

**Comment by Jamyz** [comment]
When i add the show i have this error
`2018-03-11 00:16:07 SHOWQUEUE-ADD :: [ae9ffb6] Request failed: '_io.BytesIO' object has no attribute 'fp'`

**Comment by miigotu** [comment]
`/volume1/TV Show/Marvel’s Jessica Jones (2015)` has the wrong type of apostrophe.

also, you cannot add an show existing show when the same show exists in SR.

**Comment by Jamyz** [comment]
Its crazy, when i add rename the folders with `’` works but with `'` don't.
I rename all the folders....
In local i have none.none, it's normal ? or i need to change something ?

**Comment by miigotu** [comment]
Found an issue probably, I will update in a few minutes after I test it

**Comment by miigotu** [comment]
Please try the 4369 branch

**Comment by Jamyz** [comment]
Hi @miigotu, i try with the last branch.
When try to add an existing show now i have th follow,
`2018-03-11 09:25:33 SHOWQUEUE-ADD :: [ae9ffb6] Error trying to add show: Invalid folder for the show!
`

**Comment by miigotu** [comment]
i will have to do some more testing

**Comment by miigotu** [comment]
Can you enable debug in `https://0.0.0.0:8081/config/general/` on the advanced tab, then reproduce it and check the log (switch the dropdown to debug)
I need to see the line that looks like `Setter sets location to blah` right before the `Invalid folder for the show`

**Comment by Jamyz** [comment]
OK...i have:

`2018-03-11 10:00:34 DEBUG SHOWQUEUE-REMOVE-SHOW :: Transaction with 5 queries executed 2018-03-11 10:00:34 INFO SHOWQUEUE-REMOVE-SHOW :: Removing Marvel's Jessica Jones AA NoNFOException: Invalid folder for the show! AA raise NoNFOException("Invalid folder for the show!") AA File "/volume1/@appstore/sickrage/var/sickbeard/tv.py", line 175, in _setLocation AA self.show.location = self.showDir AA File "/volume1/@appstore/sickrage/var/sickbeard/show_queue.py", line 415, in run 2018-03-11 10:00:31 DEBUG SHOWQUEUE-ADD :: Traceback (most recent call last): AA NoNFOException: Invalid folder for the show! AA raise NoNFOException("Invalid folder for the show!") AA File "/volume1/@appstore/sickrage/var/sickbeard/tv.py", line 175, in _setLocation AA self.show.location = self.showDir AA File "/volume1/@appstore/sickrage/var/sickbeard/show_queue.py", line 415, in run AA Traceback (most recent call last): 2018-03-11 10:00:31 ERROR SHOWQUEUE-ADD :: [ae9ffb6] Error trying to add show: Invalid folder for the show! 2018-03-11 10:00:31 DEBUG SHOWQUEUE-ADD :: Setter sets location to /volume1/TV Show/Marvel's Jessica Jones (2015) 2018-03-11 10:00:30 DEBUG SHOWQUEUE-ADD :: 284190: Loading show info from theTVDB 2018-03-11 10:00:30 INFO SHOWQUEUE-ADD :: 284190: Unable to find the show in the database 2018-03-11 10:00:29 INFO SHOWQUEUE-ADD :: theTVDB: {u'useZip': True, u'apikey': u'F9C450E78D99172E', u'cache': u'/var/packages/sickrage/target/var/cache/indexers/theTVDB', u'language': u'fr'} 2018-03-11 10:00:29 INFO SHOWQUEUE-ADD :: Starting to add show by ShowDir: /volume1/TV Show/Marvel's Jessica Jones (2015)`

**Comment by miigotu** [comment]
ok I have it fixed I think

**Comment by Jamyz** [comment]
Nice. I wait the release to try again.

**Comment by Jamyz** [comment]
I use the developer branch and now works fine. When you push to master ?
Thanks you for the job
