### ISSUE TITLE
[APP SUBMITTED]: 'module' object has no attribute 'ANIDB_PASS'

### ISSUE THREAD

**Issue by MarkKeir95** [SickRage/SickRage#4376]
### INFO
Python Version: **2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]**
Operating System: **Linux-4.9.59-v7+-armv7l-with-debian-9.3**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@7a26059801aed3e1aa4994663b0c68ee13fb3d56
Link to Log: https://gist.github.com/a119a870251e83ee4be706965151d0e9
### ERROR
```
Thread-16 :: [7a26059] Failed doing webui callback: Traceback (most recent call last):
  File "/home/pi/Servers/SickRage/sickbeard/webserve.py", line 287, in async_call
    result = function(**kwargs)
  File "/home/pi/Servers/SickRage/sickbeard/webserve.py", line 5320, in saveAnime
    sickbeard.ANIDB_PASSWORD = filters.unhide(sickbeard.ANIDB_PASS, anidb_password)
AttributeError: 'module' object has no attribute 'ANIDB_PASS'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by jcarlos001** [comment]
### INFO
Python Version: **2.7.14 (default, Jan  6 2018, 18:53:10) [GCC 4.2.1 Compatible FreeBSD Clang 4.0.0 (tags/RELEASE_400/final 297347)]**
Operating System: **FreeBSD-11.1-STABLE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@7a26059801aed3e1aa4994663b0c68ee13fb3d56
Link to Log: https://gist.github.com/27ec967d87232b94f9acc3be24befb57
### ERROR
```
Thread-14 :: [7a26059] Failed doing webui callback: Traceback (most recent call last):
  File "/usr/local/sickrage/sickbeard/webserve.py", line 287, in async_call
    result = function(**kwargs)
  File "/usr/local/sickrage/sickbeard/webserve.py", line 5320, in saveAnime
    sickbeard.ANIDB_PASSWORD = filters.unhide(sickbeard.ANIDB_PASS, anidb_password)
AttributeError: 'module' object has no attribute 'ANIDB_PASS'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by jcarlos001** [comment]
### INFO
Python Version: **2.7.14 (default, Jan  6 2018, 18:53:10) [GCC 4.2.1 Compatible FreeBSD Clang 4.0.0 (tags/RELEASE_400/final 297347)]**
Operating System: **FreeBSD-11.1-STABLE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@7a26059801aed3e1aa4994663b0c68ee13fb3d56
Link to Log: https://gist.github.com/95b9b67af3723751e13c793999b90729
### ERROR
```
Thread-16 :: [7a26059] Failed doing webui callback: Traceback (most recent call last):
  File "/usr/local/sickrage/sickbeard/webserve.py", line 287, in async_call
    result = function(**kwargs)
  File "/usr/local/sickrage/sickbeard/webserve.py", line 5320, in saveAnime
    sickbeard.ANIDB_PASSWORD = filters.unhide(sickbeard.ANIDB_PASS, anidb_password)
AttributeError: 'module' object has no attribute 'ANIDB_PASS'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators
