### ISSUE TITLE
AA AttributeError: '_io.BytesIO' object has no attribute 'fp'

### ISSUE THREAD

**Issue by Johan1974** [SickRage/SickRage#4381]
SickRage Configuration SickRage Info:
Branch: master
Commit: 53e6cc50c086757c31fc518b550d7681c61649e6
Database Version: 44.0
Python Version: 2.7.14 (default, Jan 8 2018, 17:12:46) [GCC 4.9.3 20150311 (prerelease)]
SSL Version: OpenSSL 1.0.2n 7 Dec 2017
OS: Linux-2.6.32.12-ppc-with-glibc2.0
Locale: None.None
User: sc-sickrage
Program Folder: /var/packages/sickrage/target/var
Config File: /var/packages/sickrage/target/var/config.ini
Database File: /var/packages/sickrage/target/var/sickbeard.db
Cache Folder: /var/packages/sickrage/target/var/cache
Log Folder: /var/packages/sickrage/target/var/Logs
  Arguments: ['--daemon', '--pidfile', '/var/packages/sickrage/target/var/sickrage.pid', '--config', '/var/packages/sickrage/target/var/config.ini', '--datadir', '/var/packages/sickrage/target/var/', '--nolaunch']

What you did:       Trying to get Sickrage to Work
What happened:   TvSeries does not seem to be picked up for download only see a lot of errors in the logs. 
What you expected: TVSeries in the download que of nzbget

Logs:
```
[SickRage.Log](https://github.com/SickRage/SickRage/files/1804745/SickRage.Log)

```
Regards,

Johan

**Comment by abetancort** [comment]
I am having the same error:

Does any one knows what it means: 

    2018-03-18 01:37:28 SEARCHQUEUE-BACKLOG-258541 :: [Torrent9] :: [1981e70] Request failed: _io.BytesIO' object has no attribute 'fp' 
    2018-03-18 01:23:49 SEARCHQUEUE-DAILY-SEARCH :: [Torrent9] :: [1981e70] Request failed: '_io.BytesIO' object has no attribute 'fp'
