### ISSUE TITLE
Can't find the tvshow in torrents, tho he exists but has got other name than tvdb default

### ISSUE THREAD

**Issue by TiagoDM** [SickRage/SickRage#4392]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master/53e6cc50c086757c31fc518b550d7681c61649e6 
Version: v2018.03.12-1 
OS: Win 10 Pro x64
What you did: ---
What happened: Can't find tvshow because of the year on the name of the tvshow - Timeless (2016), the show name in tpb and other torrent sites IS "Timeless" only, like timeless.s02e01, NOT timeless(2016).s02e01
What you expected: Expected to sickrage to find the episodes and download.
Logs:
```
PASTE LOGS HERE
```

Can you please add some option, so the user can choose the name what to search for, instead of the original name, by default named by theTVDB? 
I mean, user responsability to change the search string, instead of the "default"... and a button to rollback the changes. 

Is that possible?

Thank you,

tiago.dmarques@gmail.com

**Comment by miigotu** [comment]
Thats what scene exceptions are. Edit the show and add the name you want

**Comment by TiagoDM** [comment]
Sorry to nag about this. Thank you. Perfect!!

A quinta, 15/03/2018, 07:14, miigotu <notifications@github.com> escreveu:
