### ISSUE TITLE
[APP SUBMITTED]: [Errno 13] Permission denied: u'C:\\Downloads\\Series\\Timeless (2016)\\Season 01\\Timeless (2016).S01E16.The Red Scare.mkv'

### ISSUE THREAD

**Issue by TiagoDM** [SickRage/SickRage#4393]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@53e6cc50c086757c31fc518b550d7681c61649e6
Link to Log: https://gist.github.com/c8290b05d9a846557cd2c0184196d2dd
### ERROR
```
Thread-26 :: [53e6cc5] Failed renaming C:\Downloads\Series\Timeless (2016)\Season 01\Timeless.S01E16.HDTV.x264-KILLERS[eztv].mkv to C:\Downloads\Series\Timeless (2016)\Season 01\Timeless (2016).S01E16.The Red Scare.mkv : [Errno 13] Permission denied: u'C:\\Downloads\\Series\\Timeless (2016)\\Season 01\\Timeless (2016).S01E16.The Red Scare.mkv'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by prantzos** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-10-10.0.17134**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@5a9a634bc8af642c13a41b01affabbe96d9564dd
Link to Log: https://gist.github.com/64ea4549d359c326f1e031c1462a4f1e
### ERROR
```
POSTPROCESSOR-AUTO :: [5a9a634] [Errno 13] Permission denied
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by prantzos** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-10-10.0.17134**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@5a9a634bc8af642c13a41b01affabbe96d9564dd
Link to Log: https://gist.github.com/261edd6afe3e06e44c548c3aa3df3aab
### ERROR
```
POSTPROCESSOR-AUTO :: [5a9a634] [Errno 13] Permission denied
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by wallacebrf** [comment]
SickChill Info:
Branch: master
Commit: 0306ded8f236585531276bc4cc1db9303f26bfce
Version: v2020.04.23-6
Database Version: 44.1
  Python Version:2.7.18 (default, Apr 20 2020, 19:51:05) [GCC 9.2.0]
  SSL Version:OpenSSL 1.1.1d 10 Sep 2019
  OS:Linux-3.10.105-x86_64-with
  Locale:en_US.UTF-8


getting the following errors on the latest build

2020-04-23 10:51:06 WARNING WEBSERVER-CONFIGBACKUPRESTORE :: Zip creation error: [Errno 13] Permission denied: u'/downloads/sickchill-20200423105106.zip'
2020-04-23 10:51:05 WARNING WEBSERVER-CONFIGBACKUPRESTORE :: Zip creation error: [Errno 13] Permission denied: u'/downloads/sickchill-20200423105105.zip'
2020-04-23 10:50:48 WARNING WEBSERVER-CONFIGBACKUPRESTORE :: Zip creation error: [Errno 13] Permission denied: u'/downloads/sickchill-20200423105048.zip'


i can access the directory and see the show folders and see previous backups i store there
