### ISSUE TITLE
Show List needs "sticky" display settings

### ISSUE THREAD

**Issue by jeronymite** [SickRage/SickRage#4394]
SickRage Info:
Branch: master
Commit: 53e6cc50c086757c31fc518b550d7681c61649e6
Version: v2018.03.12-1
Database Version: 44.0
  Python Version: 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
  SSL Version: OpenSSL 1.0.2j 26 Sep 2016
  OS: Windows-10-10.0.16299
  Locale: en_AU.cp1252

What you did: In Show List, changed sort column. Went to another page, then went to Show List again.
What happened: The selected sort column had reverted to the default.
What you expected: The selected sort column should have been what I changed it to.

This is an improvement request. Either make the "settings" on the Show List page always "sticky" or provide a means to optionally make them stick after a change. (Apologies if this is currently possible and I am not aware of how to do it.)

Thanks.

**Comment by OmgImAlexis** [comment]
This should already work as the table's sort should be saved to local storage and picked up again on reloading.

**Comment by miigotu** [comment]
@OmgImAlexis it was removed because it should not be set on the show name filter, and it should only on the sticky headers

**Comment by miigotu** [comment]
I'll fix this now. I actually meant to make filter_saveFilters: false instead of removing saveSort
