### ISSUE TITLE
Can not search for a show or add existing!

### ISSUE THREAD

**Issue by statik1983** [SickRage/SickRage#4416]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Master / d115b9d4810d9ef40a1dd5f8a3df72ed5c19c16b 
OS: FreeNAS / FreeBSD
What you did: Try to add new show from search or add existing show
What happened: NOTHING...
What you expected: to get any result at all
Logs: Searching for Show with searchterm(s): ['jessica jones'] on Indexer: theTVDB
```
PASTE LOGS HERE
```

There is nothing else in the logs to post... it just keeps "searching" and never finds anything.  It has been like this for months now.

**Comment by miigotu** [comment]
#4225
