### ISSUE TITLE
[APP SUBMITTED]: ThreadPoolExecutor-0_3 :: [9783c5f] Missing time zone for network: YouTube Red. Check valid network is set in indexer (theTVDB) before filing issue.

### ISSUE THREAD

**Issue by snapperhead** [SickRage/SickRage#4449]
### INFO
Python Version: **2.7.10 (default, Jul 15 2017, 17:16:57) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]**
Operating System: **Darwin-17.4.0-x86_64-i386-64bit**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@9783c5f4de5d600d249705ce230cca53a9169f65
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_3 :: [9783c5f] Missing time zone for network: YouTube Red. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by jethromorais** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.16299**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@9783c5f4de5d600d249705ce230cca53a9169f65
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_0 :: [9783c5f] Missing time zone for network: YouTube Red. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by Ombouwleusden** [comment]
### INFO
Python Version: **2.7.14 (default, Mar 14 2018, 20:37:29) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.102-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@9783c5f4de5d600d249705ce230cca53a9169f65
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_0 :: [9783c5f] Missing time zone for network: YouTube Red. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by procdaddy11** [comment]
Still happening

**Comment by Kvothe1970** [comment]
Indeed. Still happening for me as well
