### ISSUE TITLE
No episodes found with jackett as provider - all shows & quality

### ISSUE THREAD

**Issue by 00mpy** [SickRage/SickRage#4454]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master/9783c5f4de5d600d249705ce230cca53a9169f65
OS: FreeBSD-11.0-RELEASE-amd64-64bit-ELF
Browser: Google Chrome 65.0.3325.181
What you did: nothing until noticing that no shows were downloading, triggered manual search in webui, manual search in Jackett webui
What happened: no search results found with jackett as provider in sickrage webui, manaul search in jackett webui for same show returns multiple results
What you expected: sickrage to read returned results of jackett and snatch correct episode
Logs:
```
2018-03-28 16:01:58 INFO SEARCHQUEUE-MANUAL-278125 :: Unable to find a download for: [NCIS New Orleans - S04E18 - Welcome to the Jungle]
2018-03-28 16:01:58 INFO SEARCHQUEUE-MANUAL-278125 :: [Jackett - Torrent Day] :: Performing season pack search for NCIS: New Orleans
2018-03-28 16:01:55 INFO SEARCHQUEUE-MANUAL-278125 :: [Jackett - Torrent Day] :: Performing episode search for NCIS: New Orleans
2018-03-28 16:01:55 INFO SEARCHQUEUE-MANUAL-278125 :: Beginning manual search for: [NCIS New Orleans - S04E18 - Welcome to the Jungle]
```

**Comment by kicker83** [comment]
Same problem here. The query to jackett is working fine, but sickrage doesn't snatch the episode.

**Comment by miigotu** [comment]
ill take a look tonight...

**Comment by jalahandro** [comment]
I have the same symptoms as well.
When I check my Jackett logs I see the results from queries kicked by SickRage found episodes.

Sickrage:
Branch: master
Commit: 9783c5f4de5d600d249705ce230cca53a9169f65
Version: v2018.03.25-2
Database Version: 44.0

Jackett Version 0.8.815.0

**Comment by daviddob** [comment]
Running into the same issue with an old forked version of jackett so I dont believe the api change to be the issue

**Comment by miigotu** [comment]
Let me work on it. I understand it isnt working and I have all the information that I need. So unless you have a fix please let me work =P

**Comment by daviddob** [comment]
Wasn't sure if you needed more debug info. I'll also jump into the codebase later tonight to see if I can assist.

**Comment by kicker83** [comment]
I think im moving to medusa, it is working perfect. I suggest everyone to
take a look to that fork.

**Comment by jalahandro** [comment]
I just tried daviddob's fix, and it worked for me.  Thanks!

**Comment by diegofromparis** [comment]
it seems to work well. Migotu can you review and commit ?

**Comment by dissimul8** [comment]
I tried daviddob's fix and it didn't work for me. I added some debug to log out the title and URL which jackett is providing:

```
09:36:40 INFO::SEARCHQUEUE-MANUAL-337302 :: Beginning manual search for: [Counterpart - S01E01 - The Crossing]
09:36:40 INFO::SEARCHQUEUE-MANUAL-337302 :: [Jackett: ETTV] :: Performing episode search for Counterpart
09:36:42 WARNING::SEARCHQUEUE-MANUAL-337302 :: [Jackett: ETTV] :: Counterpart.S01E01.720p.WEB.H264-STRiFE[ettv]
09:36:42 WARNING::SEARCHQUEUE-MANUAL-337302 :: [Jackett: ETTV] :: http://10.1.1.8:9117/dl/ettv/?jackett_apikey=i6xn3f32o5z6m3wss2i5qv8ig1ds3xsa&path=WGdROEo4LzF3RXM4aWlIRHNkREl4VWdaRGxNdTY1UUtxaGZZSkNKOC95Z2pIaDBqVVl1STJEVm1WekVrWkpUcllPQmwrSW5xRmo2aE5uYTBxNEs0dlJQQ2lyMFJ3SWlqTktNdjdBK2g2M3FkV1lnVkRJamRsK1VnSkc3QWFvTEdxM2Nma3dCSFdVK3hnM3hXVWt5K2h4bThWQ0NBdGFxbHlhc080c1BDUE1ZK1dXd2xYdmNjalZ1eVFvdUdkYlVZTFRuV1JMZEo5WjZqbHpHRjlzTVAza0hjWWYyTWplOVVjdWs1SUVpUXhtOFdBWi9VVjA1ZTlYcFlRODdkd2UxbGdzc293RzFzbmFxRlVaNjJ2Y2Rhd2IrakY4VXh3QUdOWFhRMFZYa2ZyVjZ4c3FwYlY0aEhqMXk2Rm44VlU3Zm15TTJzN0NFbjdNV09MOEFPaldzcEZjbnVCSzhBSGtScnVUQmNEWGVlczd2NWtwbGVjL1VKaHF3QUtHd1NXazRjWExIekVnc2VrcVgreWx1ZVRmc2NnZz090&file=Counterpart.S01E01.720p.WEB.H264-STRiFE[ettv]
09:36:42 INFO::SEARCHQUEUE-MANUAL-337302 :: Unable to find a download for: [Counterpart - S01E01 - The Crossing]
```

If I manually follow the URL provided it works as expected.

**Comment by sagilo** [comment]
This issue still happens to me.
I'm running the latest version (v2018.06.10-1) yet the exact same behavior still happens.
@daviddob Any ideas?

**Comment by daviddob** [comment]
Its working on v2018.05.11 (commit 5a9a634). Ill have to update to current and test to see if there is a break in functionality.
