### ISSUE TITLE
sickrage replaces the & to &amp;amp; in RSS

### ISSUE THREAD

**Issue by skillfr** [SickRage/SickRage#4548]
Branch/Commit: Master/https://github.com/SickRage/SickRage/commit/9783c5f4de5d600d249705ce230cca53a9169f65
Python Version: Python 2.7.13
Local: fr_FR.UTF-8
OS: Debian 9
Browser: Chrome 
What you did: nothing
What happened: I noticed that sickrage systematically replaces the & to &amp;amp;
What you expected: that it works, because it prevents to retrieve the infos of the flows rss

Before https://url/rss.php?feed=dl&
After https://url/rss.php?feed=dl&amp;amp;

Cordially

Logs:
```
2018-04-01 18:27:30 DEBUG SEARCHQUEUE-DAILY-SEARCH :: [XXX] :: RSS error:
2018-04-01 18:27:30 DEBUG SEARCHQUEUE-DAILY-SEARCH :: [XXX] :: GET URL: https://XXX.net/rss.php?feed=dl&amp;cat=42,4,48,43&amp;rsskey=XXXXXXXXXXXXXXXXXXXXX[Status: 200]
```

**Comment by hedlof** [comment]
Yes same problem here. 

I had to reinstall SickRage and cannot add custom provider with RSS feed. It says: 
No items found in the RSS feed https://url.com/rss.php?cat=8&amp;passkey=xxxxxxxxxxxxxxxxxxxxxxxxx

**Comment by skillfr** [comment]
up

**Comment by murre87** [comment]
Same here

**Comment by miigotu** [comment]
Need to know which rss provider, because showrss works fine with how it is

**Comment by hedlof** [comment]
I'm using Superbits.org RSS feed. Superbits is down atm though because of server issues.

**Comment by skillfr** [comment]
@miigotu rss feeds built into the tracker (xthor and ethor)

**Comment by miigotu** [comment]
Should be fixed in #4636

**Comment by murre87** [comment]
How do i implement this in my sickrage-installation.
I have: v2018.04.08-1

**Comment by miigotu** [comment]
It would help if you can test the develop branch and let me know if it works. I haven't been able to test it personally, but there are a lot of other changes in that PR so hopefully its all working nice

**Comment by skillfr** [comment]
ok thanks you it's work
