### ISSUE TITLE
[APP SUBMITTED]: ThreadPoolExecutor-0_3 :: [a760263] Missing time zone for network: FX (US). Check valid network is set in indexer (theTVDB) before filing issue.

### ISSUE THREAD

**Issue by blu30ri0n** [SickRage/SickRage#4575]
### INFO
Python Version: **2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]**
Operating System: **Linux-4.4.11-v7+-armv7l-with-debian-8.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@a7602639bd525f27475f1eeb2fc504111a14b51c
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_3 :: [a760263] Missing time zone for network: FX (US). Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by maheshraotm** [comment]
### INFO
Python Version: **2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]**
Operating System: **Linux-4.14.30-v7+-armv7l-with-debian-9.4**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@a7602639bd525f27475f1eeb2fc504111a14b51c
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_0 :: [a760263] Missing time zone for network: FX (US). Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators
