### ISSUE TITLE
Sickrage replaces the & to &amp; in RSS custom provider

### ISSUE THREAD

**Issue by skillfr** [SickRage/SickRage#4587]
Branch/Commit: Master/https://github.com/SickRage/SickRage/commit/a7602639bd525f27475f1eeb2fc504111a14b51c
Python Version: Python 2.7.13
Local: fr_FR.UTF-8
OS: Debian 9
Browser: Chrome 
What you did: nothing
What happened: I noticed that sickrage systematically replaces the & to &amp;amp;
What you expected: that it works, because it prevents to retrieve the infos of the flows rss

Before https://url/rss.php?feed=dl&
After https://url/rss.php?feed=dl&amp;amp;

Cordially

Proof

![chrome_2018-04-09_23-59-54](https://user-images.githubusercontent.com/12272393/38525551-11c974dc-3c53-11e8-9880-ef628e7fd54c.png)

Logs:
```
2018-04-01 18:27:30 DEBUG SEARCHQUEUE-DAILY-SEARCH :: [XXX] :: RSS error:
2018-04-01 18:27:30 DEBUG SEARCHQUEUE-DAILY-SEARCH :: [XXX] :: GET URL: https://XXX.net/rss.php?feed=dl&amp;cat=42,4,48,43&amp;rsskey=XXXXXXXXXXXXXXXXXXXXX[Status: 200]
```

**Comment by skillfr** [comment]
Up https://github.com/SickRage/SickRage/issues/4548

**Comment by murre87** [comment]
Up

**Comment by pax0707** [comment]
Broke my backup to api not working...

**Comment by nFec** [comment]
#4445 similar but different.
