### ISSUE TITLE
[APP SUBMITTED]: ThreadPoolExecutor-0_0 :: [5a9a634] Missing time zone for network: YouTube Red. Check valid network is set in indexer (theTVDB) before filing issue.

### ISSUE THREAD

**Issue by RebelliousUno** [SickRage/SickRage#4678]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@5a9a634bc8af642c13a41b01affabbe96d9564dd
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_0 :: [5a9a634] Missing time zone for network: YouTube Red. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by lqid10t** [comment]
### INFO
Python Version: **2.7.13 (default, Dec 19 2016, 02:32:04) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.102-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@5a9a634bc8af642c13a41b01affabbe96d9564dd
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_1 :: [5a9a634] Missing time zone for network: YouTube Red. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by m00n22** [comment]
### INFO
Python Version: **2.7.13 (default, Dec 19 2016, 02:32:04) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.102-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@5a9a634bc8af642c13a41b01affabbe96d9564dd
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_0 :: [5a9a634] Missing time zone for network: YouTube Red. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by bepece1** [comment]
### INFO
Python Version: **2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]**
Operating System: **Linux-4.14.34-v7+-armv7l-with-debian-9.4**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@5a9a634bc8af642c13a41b01affabbe96d9564dd
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_0 :: [5a9a634] Missing time zone for network: YouTube Red. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by danyboy666** [comment]
### INFO
Python Version: **2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]**
Operating System: **Linux-4.4.0-109-generic-x86_64-with-Ubuntu-16.04-xenial**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@5a9a634bc8af642c13a41b01affabbe96d9564dd
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_3 :: [5a9a634] Missing time zone for network: YouTube Red. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by bepece1** [comment]
### INFO
Python Version: **2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]**
Operating System: **Linux-4.14.34-v7+-armv7l-with-debian-9.4**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@5a9a634bc8af642c13a41b01affabbe96d9564dd
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_0 :: [5a9a634] Missing time zone for network: YouTube Red. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by j0n0russo** [comment]
### INFO
Python Version: **2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]**
Operating System: **Linux-3.19.8-ckt22-custom-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@5a9a634bc8af642c13a41b01affabbe96d9564dd
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_1 :: [5a9a634] Missing time zone for network: YouTube Red. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by faldo7777** [comment]
### INFO
Python Version: **2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-10-10.0.17134**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@5a9a634bc8af642c13a41b01affabbe96d9564dd
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_0 :: [5a9a634] Missing time zone for network: YouTube Red. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by tatsumasagc** [comment]
### INFO
Python Version: **2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.17134**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@5a9a634bc8af642c13a41b01affabbe96d9564dd
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_1 :: [5a9a634] Missing time zone for network: YouTube Red. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by tatsumasagc** [comment]
### INFO
Python Version: **2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.17134**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@5a9a634bc8af642c13a41b01affabbe96d9564dd
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_0 :: [5a9a634] Missing time zone for network: YouTube Red. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators
