### ISSUE TITLE
Sickrage can't connect to torrrent clients anymore (Transmission, Download Station)

### ISSUE THREAD

**Issue by bolhaskutya** [SickRage/SickRage#4766]
Sickrage doesn't send torrents to torrent clients anymore. It cannot connect to them. I tried with Transmission and Download Station. Could this be related to the DSM 6.1.7-15284 update?

**Transmission error**
```
2018-06-12 10:15:08 INFO     ThreadPoolExecutor-0_2 :: Request failed: [Errno 404] Not Found
```

**Download Station error**
```
2018-06-12 10:09:58 INFO     ThreadPoolExecutor-0_1 :: Request failed: HTTPConnectionPool(host='***********', port=5000): Max retries exceeded with url: /webapi/auth.cgi?session=DownloadStation&account=*****&version=2&format=cookie&passwd=******&api=SYNO.API.Auth&method=login (Caused by NewConnectionError(': Failed to establish a new connection: [Errno -2] Name or service not known',))
```

**Comment by deusxanime** [comment]
It doesn't seem to be working with rtorrent anymore either. I updated my rtorrent container which now uses v0.9.7 and SR seems to fail to send magnets to it. I haven't changed anything and if I go into the Config > Search Settings > Torrent Search and hit the "Test Connection" I still get the "Success: Connected and Authenticated" message, but still get these errors whenever it tries to push the magnet to it:

```
2018-06-14 14:32:10 WARNING SEARCHQUEUE-DAILY-SEARCH :: rTorrent: Unable to send Torrent
2018-06-14 14:32:10 WARNING SEARCHQUEUE-DAILY-SEARCH :: Error while sending torrent:
```

Something maybe change with rtorrent that SR needs to fix to work now?

**Comment by HavocNME** [comment]
I had the same issue on a brand new seedbox earlier today I'm assuming you to figured out that it doesn't like some characters in your password. I changed my password to something without + and & and was all good. I had a 23 random character password. My new password is 14 characters. However on my older seedbox I use the same 23 character password without issue so don't know why it all of a sudden doesn't like the password. Hope this helps anyone in the future.

**Comment by bolhaskutya** [comment]
My solution was different.

I use an internal domain on my network to access the nas. So I don't access the synology web interface via an IP address like 192.168.1.100, but rather synology.mynetwork.net. (configured by the router) I have set in sickrage 
the _Torrent host:port (URL to your Transmission client (e.g. http://localhost:9091))_ setting to my domain: synology.mynetwork.net and it didn't like it. Setting the ip address of the synology nas directly solved my problem.

Also disabling IPv6 in the synology network settings is a good idea, when sickrage is having connectivity issues.
