### ISSUE TITLE
Failed doing webui callback - TypeError: expected string or buffer

### ISSUE THREAD

**Issue by Spazholio** [SickRage/SickRage#4771]
**Branch/Commit**: master / 93923792e8908427344d6e01de968656cf096626
**OS**: Ubuntu 14.04
**Browser**: Chrome
**What you did**: Process item from sabnzbd to SickRage (automatically).  It's done this on 3 separate shows.
**What happened**: When I click on the entry in sabnzbd, it shows me this
```
Loading config from /home/spaz/.sickrage/autoProcessTV/autoProcessTV.cfg

Opening URL: https://192.168.1.225:8081/home/postprocess/processEpisode?nzbName=Jeopardy.2018.06.12.720p.HDTV.x264-NTb.nzb&quiet=1&dir=%2Fhome%2Fspaz%2FDownloads%2Ftv%2FJeopardy+2018+06+12+720p+HDTV+x264-NTb
Unable to open URL: HTTP Error 500: Internal Server Error
```
SickRage logs indicate what's pasted below.
**What you expected**: Shows to be sorted properly.  This was working as of 2 days ago, with zero changes made on my part.

**Logs**:
```
2018-06-13 18:25:34 ThreadPoolExecutor-0_0 :: [9392379] Failed doing webui callback: Traceback (most recent call last):
  File "/home/spaz/.sickrage/sickbeard/webserve.py", line 288, in async_call
    result = function(**kwargs)
  File "/home/spaz/.sickrage/sickbeard/webserve.py", line 2483, in processEpisode
    process_path = ss(kwargs.get('dir', xhtml_unescape(proc_dir)) or '')
  File "/home/spaz/.sickrage/lib/tornado/escape.py", line 68, in xhtml_unescape
    return re.sub(r"&(#?)(\w+?);", _convert_entity, _unicode(value))
  File "/usr/lib/python2.7/re.py", line 151, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer

2018-06-13 18:13:09 ThreadPoolExecutor-0_3 :: [9392379] Failed doing webui callback: Traceback (most recent call last):
  File "/home/spaz/.sickrage/sickbeard/webserve.py", line 288, in async_call
    result = function(**kwargs)
  File "/home/spaz/.sickrage/sickbeard/webserve.py", line 2483, in processEpisode
    process_path = ss(kwargs.get('dir', xhtml_unescape(proc_dir)) or '')
  File "/home/spaz/.sickrage/lib/tornado/escape.py", line 68, in xhtml_unescape
    return re.sub(r"&(#?)(\w+?);", _convert_entity, _unicode(value))
  File "/usr/lib/python2.7/re.py", line 151, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer
```

**Comment by chris41g** [comment]
im getting the same error when processing episodes

`2018-06-13 19:41:11 ThreadPoolExecutor-0_4 :: [9392379] Failed doing webui callback: Traceback (most recent call last):
File "C:\Program Files (x86)\SickBeard\sickbeard\webserve.py", line 288, in async_call
result = function(**kwargs)
File "C:\Program Files (x86)\SickBeard\sickbeard\webserve.py", line 2483, in processEpisode
process_path = ss(kwargs.get('dir', xhtml_unescape(proc_dir)) or '')
File "C:\Program Files (x86)\SickBeard\lib\tornado\escape.py", line 68, in xhtml_unescape
return re.sub(r"&(#?)(\w+?);", _convert_entity, _unicode(value))
File "C:\Python27\lib\re.py", line 155, in sub
return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer`

**Comment by Spazholio** [comment]
@chris41g I managed to get around this issue by downgrading to this commit: 39c5dc61ca66d1eea58e1cd0ea08a96a990c6e8a.  Seems like something along the way broke...something.  Don't forget to disable automatic upgrading (if you have it enabled) or you'll be right back where you started.

**Comment by phreaq** [comment]
just chiming in, I'm having the same issues, auto processing has recently failed. no changes on my part.

however, if I manually process the folder afterwards, it works without error.

**Comment by MilhouseVH** [comment]
25c30d049fc8f2ea1825b7101cd2b21b5e591b0e is the commit that introduces the problem.

**Comment by ctrlbrk42** [comment]
Same thing here, on Synology DSM 6.2.  Not sure how to downgrade to last commit in this scenario, if anyone can help...

**Comment by MilhouseVH** [comment]
Shutdown sickrage, then `git reset --hard 9b2acb13e7b66fe95bde68a6cbca618b336c4c45`, and restart sickrage.

**Comment by Fiat2LTC** [comment]
Sorry about that! Submitted a PR to fix

**Comment by ctrlbrk42** [comment]
@MilhouseVH do I need to be in a certain directory, or can I do it in /root?

**Comment by MilhouseVH** [comment]
@ctrlbrk42 you need to be in the sickrage git repository directory (assuming your installed sickrage is running out of a git repo).

On my Raspberry Pi (running Raspbian):
```
neil@raspberrypi ~ $ cd /opt/sickbeard
neil@raspberrypi /opt/sickbeard $ git remote -v
origin  https://github.com/SickRage/SickRage.git (fetch)
neil@raspberrypi /opt/sickbeard $ sudo systemctl stop sickbeard-daemon.service
neil@raspberrypi /opt/sickbeard $ git reset --hard 9b2acb13e7b66fe95bde68a6cbca618b336c4c45
HEAD is now at 9b2acb13e YggTorrent : Fix for session expiration (very short)
neil@raspberrypi /opt/sickbeard $ sudo systemctl start sickbeard-daemon.service
neil@raspberrypi /opt/sickbeard $
```

@Fiat2LTC : Thanks! :)

**Comment by gosku** [comment]
Same problem here, with sabnzbd communicating with sickrage, both successful and failed downloads

**Comment by Fiat2LTC** [comment]
The fix is here https://github.com/SickRage/SickRage/pull/4803

Just need someone to merge it.
@miigotu @SickRage2 ?

**Comment by dochyde** [comment]
I tried reverting as a temporary fix but then my notifications don't work anymore.
Any idea when this issue will be fixed please?
Manual intervention needed all the time, kind of defies the automation part of all this.

**Comment by TheHolyRoger** [comment]
Should be fixed for you all now! @dochyde @gosku @ctrlbrk42 @phreaq @Spazholio @Chris41g

**Comment by phreaq** [comment]
it's working, thanks!!!!!

**Comment by gosku** [comment]
it works, thank you guys, you are saving me soooo much time with this automation tool :+1:
