### ISSUE TITLE
[APP SUBMITTED]: ThreadPoolExecutor-0_0 :: [807c5ae] Missing time zone for network: YouTube Red. Check valid network is set in indexer (theTVDB) before filing issue.

### ISSUE THREAD

**Issue by ChromevoidGit** [SickRage/SickRage#4782]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-7-6.1.7601-SP1**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@807c5ae37ecd5af7483f06459c94788ee9db483d
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_0 :: [807c5ae] Missing time zone for network: YouTube Red. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by jgwallace3** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.17134**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@807c5ae37ecd5af7483f06459c94788ee9db483d
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_2 :: [807c5ae] Missing time zone for network: YouTube Red. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by Bogey** [comment]
### INFO
Python Version: **2.7.3 (default, Jun 21 2016, 20:38:54) [GCC 4.6.3]**
Operating System: **Linux-4.4.116.alpine.1-armv7l-with-debian-8.10**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@807c5ae37ecd5af7483f06459c94788ee9db483d
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_0 :: [807c5ae] Missing time zone for network: YouTube Red. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by edwinroos** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-2012Server-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@807c5ae37ecd5af7483f06459c94788ee9db483d
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_6 :: [807c5ae] Missing time zone for network: YouTube Red. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by kozz71** [comment]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 15:25:50) [GCC 4.8.3 20140106 (prerelease)]**
Operating System: **Linux-3.10.105-armv7l-with-glibc2.4**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@807c5ae37ecd5af7483f06459c94788ee9db483d
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_0 :: [807c5ae] Missing time zone for network: YouTube Red. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by m184711** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@807c5ae37ecd5af7483f06459c94788ee9db483d
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_0 :: [807c5ae] Missing time zone for network: YouTube Red. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by j0n0russo** [comment]
### INFO
Python Version: **2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]**
Operating System: **Linux-3.19.8-ckt22-custom-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@807c5ae37ecd5af7483f06459c94788ee9db483d
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_0 :: [807c5ae] Missing time zone for network: YouTube Red. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by kozz71** [comment]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 15:25:50) [GCC 4.8.3 20140106 (prerelease)]**
Operating System: **Linux-3.10.105-armv7l-with-glibc2.4**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@807c5ae37ecd5af7483f06459c94788ee9db483d
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_0 :: [807c5ae] Missing time zone for network: YouTube Red. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by bepece1** [comment]
### INFO
Python Version: **2.7.14 (default, Feb 22 2018, 21:59:41) [GCC 6.3.0]**
Operating System: **Linux-4.14.50-v7+-armv7l-with**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@807c5ae37ecd5af7483f06459c94788ee9db483d
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_2 :: [807c5ae] Missing time zone for network: YouTube Red. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by kozz71** [comment]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 15:25:50) [GCC 4.8.3 20140106 (prerelease)]**
Operating System: **Linux-3.10.105-armv7l-with-glibc2.4**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@807c5ae37ecd5af7483f06459c94788ee9db483d
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_0 :: [807c5ae] Missing time zone for network: YouTube Red. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by tatsumasagc** [comment]
### INFO
Python Version: **2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.17134**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@807c5ae37ecd5af7483f06459c94788ee9db483d
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_2 :: [807c5ae] Missing time zone for network: YouTube Red. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by iamthejustin** [comment]
**INFO**
Python Version: 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
Operating System: Windows-10-10.0.17134  
Locale: cp1252
Branch: master 
Commit: 807c5ae37ecd5af7483f06459c94788ee9db483d
No Log available with ERRORS:

**ERROR**
ThreadPoolExecutor-0_2 :: [807c5ae] Missing time zone for network: YouTube Red. Check valid network is set in indexer (theTVDB) before filing issue.

**Comment by prantzos** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-10-10.0.17134**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@807c5ae37ecd5af7483f06459c94788ee9db483d
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_1 :: [807c5ae] Missing time zone for network: YouTube Red. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators
