### ISSUE TITLE
Option to opt out of SSO

### ISSUE THREAD

**Issue by qbitza** [SickRage/SickRage#4804]
Please allow an option to opt out of SSO

**Comment by pselibas** [comment]
+1

**Comment by miigotu** [comment]
huh?

**Comment by OmgImAlexis** [comment]
@miigotu just checked the "fake" Sickrage forum he implimented single sign on using `auth.sickrage.ca`. 🙄 


@qbitza @pselibas you both need to reinstall Sickrage as you're using a fake version of it.

**Comment by pselibas** [comment]
Just to clarify, I got to this by using the sickrage/sickrage docker image. 
So if anyone is reading this... do not use that image.

**Comment by OmgImAlexis** [comment]
@pselibas yeah there isn't much that can be done about that since echelon(the one behind the fake verison) had the docker org before we could get our hands on it.
