### ISSUE TITLE
Search Providers Mako Error

### ISSUE THREAD

**Issue by ModuRaziel** [SickRage/SickRage#4817]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Master
OS: Windows 10, Mobile
Browser: Chrome/Firefox
What you did: Opened "Search Providers" config menu
What happened: Mako Error
What you expected: opening config page for Search Providers
Logs:
```
Logs do not generate any info but the bellow error comes up:

File C:/Programs/SickRage/SickRage/gui/slick/views/config_providers.mako:183, in render_pages:
${('', 'checked="checked"')[curNewznabProvider.enable_daily]}

TypeError: tuple indices must be integers, not unicode
```
Used to work without issue, version should not have changed for some time now. have tried reverting to previous version, but am not fluent enough with Git to get it to work so cannot confirm if older version also has issue

**Comment by mgaulton** [comment]
I'm getting the same result.

**Comment by daign2002** [comment]
same result, did a fresh install, worked fine, then restored a backup and it came back.

> File C:/SickRage/SickRage/gui/slick/views/config_providers.mako:183, in render_pages:
${('', 'checked="checked"')[curNewznabProvider.enable_daily]}

TypeError: tuple indices must be integers, not unicode

**Comment by boredsysadmin** [comment]
Same issue here:
  SickRage Info:
Branch: master
Commit: 807c5ae37ecd5af7483f06459c94788ee9db483d
Database Version: 44.0
  Python Version: 2.7.9 (default, Sep 9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]
  SSL Version: OpenSSL 1.0.2d 9 Jul 2015
  OS: FreeBSD-11.0-RELEASE-amd64-64bit-ELF
  Locale: en_US.UTF-8

**Comment by ravensorb** [comment]
is this a duplicate of #4721

**Comment by ModuRaziel** [comment]
appears fixed in latest release
