### ISSUE TITLE
API QQ

### ISSUE THREAD

**Issue by mgaulton** [SickRage/SickRage#4933]
I'm wanting to write a prequeue script for sabnzbd but need to convert the show name sab has to the indexerid so I can check if the episode is already downloaded in the preferred format. Sometimes I manually add something or add multiples in the hopes of getting a valid one :)

Is there a show name to indexerid api call? or another method to do the same?

**Comment by miigotu** [comment]
You can mess around with the api builder at: `/home/apibuilder`
I think what you need is to get the info for all shows in the list and parse it, you can sort by id or name:
`/api/{api_key}/?cmd=shows&sort=name`
`/api/{api_key}/?cmd=shows&sort=id`
