### ISSUE TITLE
Release Group not correctly identified because of "xpost" extension

### ISSUE THREAD

**Issue by W13N3N** [SickRage/SickRage#4941]
**Branch/Commit:** Master/0e727649748ec38c5bba69f3f97c9e7b794d56df
**OS:** Server 2016
**Browser:** Chrome
**What you did:** Episode Naming
**What happened:** it identifies the wrong Release Group

One of my indexers is nzb.su. They lately started adding "xpost" to there nzb/file naming.
For example; _Paradise PD S01E08 NF WEB-DL DDP5 1 x264-monkee-xpost_

I want the Release Group to be added to the filename when Sickrage is handling the episode naming. But when there's "xpost" in the end of the filename it identifies that as the Release Group instead of the actual Release Group, in this case "monkee".

Is there a way to tell Sickrage to ignore "xpost" while renaming to identify the correct Release Group? I don't want to blacklist the "xpost" releases in the search proces because of the huge availability of posts on nzb.su.

**Comment by BenjV** [comment]
The definition of a releasgroup in a filename is that it starts with the "-" character so SickRage rightly identifies it as a releasegroup.
You have to try persuade the posters of the file to keep their naming according the naming rules.

**Comment by W13N3N** [comment]
@BenjV Thanks for your response!

Since most of the posts on nzb.su ends with -xpost they probably won't change there naming convention. Because i recently upgraded my VIP there i've now managed to fix this with a script for NZBGet which removes the -xpost before adding the NZB to the que therefor Sickrage correctly naming the Release Group.

For those who have a similar problem; https://forum.nzbget.net/viewtopic.php?f=8&t=1795

**Comment by BenjV** [comment]
So at nzb.su they have no idea what they are doing, I would not want to pay such a company for a VIP account.

**Comment by W13N3N** [comment]
@BenjV ; Indeed. The problems started just after my renewal otherwise i didn't renew off-course :)
For now I've added another good indexer as primary.
