### ISSUE TITLE
[APP SUBMITTED]: ThreadPoolExecutor-0_0 :: [8292072] Missing time zone for network: YouTube Red. Check valid network is set in indexer (theTVDB) before filing issue.

### ISSUE THREAD

**Issue by ahummaida** [SickRage/SickRage#4958]
### INFO
Python Version: **2.7.12 (default, Aug 20 2016, 20:35:21) [GCC 5.2.0]**
Operating System: **Linux-4.2.8-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@829207271c18b0317f12f70fb01225941f0e6d4f
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_0 :: [8292072] Missing time zone for network: YouTube Red. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by prantzos** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-10-10.0.17134**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@829207271c18b0317f12f70fb01225941f0e6d4f
Link to Log: https://gist.github.com/ef22c045c49ac63ea203c5dc28c84e5b
### ERROR
```
POSTPROCESSOR-AUTO :: [8292072] 
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by prantzos** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-10-10.0.17134**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@829207271c18b0317f12f70fb01225941f0e6d4f
Link to Log: https://gist.github.com/9bbc23109500306418d251dcb918834b
### ERROR
```
POSTPROCESSOR-AUTO :: [8292072] 
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators
