### ISSUE TITLE
Pirate Bay switch .org to .asia

### ISSUE THREAD

**Issue by channingrossi** [SickRage/SickRage#4963]
Branch/Commit: v2018.09.17-1
OS: Mac OS 10.12
Browser: Google Chrome
What you did: Added Custom Search provider of thepiratebay.asia RSS 
What happened: Pirate Bay errors on Pirate.org since site is down. has been moved to thepiratebay.asia 

what you expected: Either thepiratebay.org to update to the .asia domain, or the custom URL to pick up torrents, which it does not

Logs:

```
2018-09-19 23:22:47 INFO FINDPROPERS :: [ThePirateBay] :: Request failed: HTTPSConnectionPool(host='thepiratebay.org', port=443): Read timed out. (read timeout=30)
```

**Comment by miigotu** [comment]
thepiratebay.org is still the correct address, in fact both work. When the custom URL fails it will try to fall back to the default.
