### ISSUE TITLE
[APP SUBMITTED]: CHECKVERSION :: [51328d1] git config remote.origin.url https://github.com/SickRage/SickRage.git returned code -11, treating as error : None

### ISSUE THREAD

**Issue by freeextreme** [SickRage/SickRage#4968]
### INFO
Python Version: **2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]**
Operating System: **Linux-4.4.59+-x86_64-with**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@51328d1fb61ebc9704934e3cf14425453196790d
No Log available with ERRORS:
### ERROR
```
CHECKVERSION :: [51328d1] git config remote.origin.url https://github.com/SickRage/SickRage.git returned code -11, treating as error : None
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by spotopolis** [comment]
### INFO
Python Version: **2.7.15 (default, Aug 16 2018, 14:17:09) [GCC 6.4.0]**
Operating System: **Linux-4.18.10-unRAID-x86_64-with**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@51328d1fb61ebc9704934e3cf14425453196790d
Link to Log: https://gist.github.com/8b676192e20e8b93625beae040938e78
### ERROR
```
CHECKVERSION :: [51328d1] git config remote.origin.url https://github.com/SickRage/SickRage.git returned code -11, treating as error : None
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators
