### ISSUE TITLE
Unpacking archives fails on freebsd

### ISSUE THREAD

**Issue by soend** [SickRage/SickRage#4975]
Branch/Commit:
OS: FreeBSD 11.2
Browser: Chrome
What you did: Unpack in post processing

I do have unrar installed and running in terminal works. User has all the permissions for the folders. When SickRage tries to unpack archive it fails with the error provided in the log. What else should i be checking to make it work?

Logs:
```
2018-09-28 21:58:55 INFO POSTPROCESSOR-AUTO :: Auto post processing task for /media/downloads completed
2018-09-28 21:58:55 INFO POSTPROCESSOR-AUTO :: my.cat.from.hell.s10e06.meow.mates.1080p.web.x264-caffeine.rar : Unpacking failed: Unpacking Failed with Invalid Rar Archive Usage. Is unrar installed and on the system PATH?
```

**Comment by miigotu** [comment]
unrar-nonfree

**Comment by soend** [comment]
For some reason i cant change the bsdtar to anything else in the post processing settings in web ui. Every time i save and refresh its changed back to bsdtar. Any reason this could be happening or just a bug?

**Comment by soend** [comment]
> unrar-nonfree

I dont think feebsd has that package. Atleast i cant find any information about it.

**Comment by soend** [comment]
Got it sorted. And again it actually was permission issue. Had to change the owner of the folder where the files where uncompressed in to the user running sickrage process. Maybe there could be better error message or better way of testing the uncompressing.
The way i found out the issue was permissions was that i tried to backup settings to the same folder and it failed with permissions denied error.
